"""Least-privilege Payroll authority permissions."""


class PayrollPermission:
    POLICY_READ = "COMPANY_PAYROLL_POLICY_READ"
    POLICY_MANAGE = "COMPANY_PAYROLL_POLICY_MANAGE"
    POLICY_APPROVE = "COMPANY_PAYROLL_POLICY_APPROVE"
    COMPENSATION_READ = "COMPANY_PAYROLL_COMPENSATION_READ"
    COMPENSATION_MANAGE = "COMPANY_PAYROLL_COMPENSATION_MANAGE"
    COMPENSATION_APPROVE = "COMPANY_PAYROLL_COMPENSATION_APPROVE"
    ADMISSION_REVIEW = "COMPANY_PAYROLL_ADMISSION_REVIEW"
    CALCULATION_EXECUTE = "COMPANY_PAYROLL_CALCULATION_EXECUTE"
    CALCULATION_READ = "COMPANY_PAYROLL_CALCULATION_READ"
    CALCULATION_REVIEW = "COMPANY_PAYROLL_CALCULATION_REVIEW"
    TAX_AUTHORITY_READ = "COMPANY_PAYROLL_TAX_AUTHORITY_READ"
    TAX_AUTHORITY_MANAGE = "COMPANY_PAYROLL_TAX_AUTHORITY_MANAGE"
    TAX_AUTHORITY_APPROVE = "COMPANY_PAYROLL_TAX_AUTHORITY_APPROVE"
    DEDUCTION_AUTHORITY_READ = "COMPANY_PAYROLL_DEDUCTION_AUTHORITY_READ"
    DEDUCTION_AUTHORITY_MANAGE = "COMPANY_PAYROLL_DEDUCTION_AUTHORITY_MANAGE"
    DEDUCTION_AUTHORITY_APPROVE = "COMPANY_PAYROLL_DEDUCTION_AUTHORITY_APPROVE"
    TAX_CALCULATION_EXECUTE = "COMPANY_PAYROLL_TAX_CALCULATION_EXECUTE"
    TAX_CALCULATION_READ = "COMPANY_PAYROLL_TAX_CALCULATION_READ"

    ALL = (
        POLICY_READ,
        POLICY_MANAGE,
        POLICY_APPROVE,
        COMPENSATION_READ,
        COMPENSATION_MANAGE,
        COMPENSATION_APPROVE,
        ADMISSION_REVIEW,
        CALCULATION_EXECUTE,
        CALCULATION_READ,
        CALCULATION_REVIEW,
        TAX_AUTHORITY_READ,
        TAX_AUTHORITY_MANAGE,
        TAX_AUTHORITY_APPROVE,
        DEDUCTION_AUTHORITY_READ,
        DEDUCTION_AUTHORITY_MANAGE,
        DEDUCTION_AUTHORITY_APPROVE,
        TAX_CALCULATION_EXECUTE,
        TAX_CALCULATION_READ,
    )
