"""Least-privilege Payroll authority permissions."""


class PayrollPermission:
    POLICY_READ = "COMPANY_PAYROLL_POLICY_READ"
    POLICY_MANAGE = "COMPANY_PAYROLL_POLICY_MANAGE"
    POLICY_APPROVE = "COMPANY_PAYROLL_POLICY_APPROVE"
    COMPENSATION_READ = "COMPANY_PAYROLL_COMPENSATION_READ"
    COMPENSATION_MANAGE = "COMPANY_PAYROLL_COMPENSATION_MANAGE"
    COMPENSATION_APPROVE = "COMPANY_PAYROLL_COMPENSATION_APPROVE"
    ADMISSION_REVIEW = "COMPANY_PAYROLL_ADMISSION_REVIEW"
    CALCULATION_EXECUTE = "COMPANY_PAYROLL_CALCULATION_EXECUTE"
    CALCULATION_READ = "COMPANY_PAYROLL_CALCULATION_READ"
    CALCULATION_REVIEW = "COMPANY_PAYROLL_CALCULATION_REVIEW"

    ALL = (
        POLICY_READ,
        POLICY_MANAGE,
        POLICY_APPROVE,
        COMPENSATION_READ,
        COMPENSATION_MANAGE,
        COMPENSATION_APPROVE,
        ADMISSION_REVIEW,
        CALCULATION_EXECUTE,
        CALCULATION_READ,
        CALCULATION_REVIEW,
    )
