"""Least-privilege Payroll authority permissions."""


class PayrollPermission:
    POLICY_READ = "COMPANY_PAYROLL_POLICY_READ"
    POLICY_MANAGE = "COMPANY_PAYROLL_POLICY_MANAGE"
    POLICY_APPROVE = "COMPANY_PAYROLL_POLICY_APPROVE"
    COMPENSATION_READ = "COMPANY_PAYROLL_COMPENSATION_READ"
    COMPENSATION_MANAGE = "COMPANY_PAYROLL_COMPENSATION_MANAGE"
    COMPENSATION_APPROVE = "COMPANY_PAYROLL_COMPENSATION_APPROVE"
    ADMISSION_REVIEW = "COMPANY_PAYROLL_ADMISSION_REVIEW"
    CALCULATION_EXECUTE = "COMPANY_PAYROLL_CALCULATION_EXECUTE"
    CALCULATION_READ = "COMPANY_PAYROLL_CALCULATION_READ"
    CALCULATION_REVIEW = "COMPANY_PAYROLL_CALCULATION_REVIEW"
    TAX_AUTHORITY_READ = "COMPANY_PAYROLL_TAX_AUTHORITY_READ"
    TAX_AUTHORITY_MANAGE = "COMPANY_PAYROLL_TAX_AUTHORITY_MANAGE"
    TAX_AUTHORITY_APPROVE = "COMPANY_PAYROLL_TAX_AUTHORITY_APPROVE"
    DEDUCTION_AUTHORITY_READ = "COMPANY_PAYROLL_DEDUCTION_AUTHORITY_READ"
    DEDUCTION_AUTHORITY_MANAGE = "COMPANY_PAYROLL_DEDUCTION_AUTHORITY_MANAGE"
    DEDUCTION_AUTHORITY_APPROVE = "COMPANY_PAYROLL_DEDUCTION_AUTHORITY_APPROVE"
    TAX_CALCULATION_EXECUTE = "COMPANY_PAYROLL_TAX_CALCULATION_EXECUTE"
    TAX_CALCULATION_READ = "COMPANY_PAYROLL_TAX_CALCULATION_READ"
    TAX_RESULT_READ = "COMPANY_PAYROLL_TAX_RESULT_READ"
    TAX_RESULT_REVIEW = "COMPANY_PAYROLL_TAX_RESULT_REVIEW"
    RUN_ASSEMBLE = "COMPANY_PAYROLL_RUN_ASSEMBLE"
    RUN_READ = "COMPANY_PAYROLL_RUN_READ"
    RUN_REVIEW = "COMPANY_PAYROLL_RUN_REVIEW"
    RUN_APPROVE = "COMPANY_PAYROLL_RUN_APPROVE"
    PAYMENT_INSTRUCTION_READ = "COMPANY_PAYROLL_PAYMENT_INSTRUCTION_READ"
    PAYMENT_INSTRUCTION_MANAGE = "COMPANY_PAYROLL_PAYMENT_INSTRUCTION_MANAGE"
    PAYMENT_RELEASE_ASSEMBLE = "COMPANY_PAYROLL_PAYMENT_RELEASE_ASSEMBLE"
    PAYMENT_RELEASE_READ = "COMPANY_PAYROLL_PAYMENT_RELEASE_READ"
    PAYMENT_RELEASE_REVIEW = "COMPANY_PAYROLL_PAYMENT_RELEASE_REVIEW"
    PAYMENT_RELEASE_APPROVE = "COMPANY_PAYROLL_PAYMENT_RELEASE_APPROVE"
    PAYMENT_EXECUTION_AUTHORIZE = "COMPANY_PAYROLL_PAYMENT_EXECUTION_AUTHORIZE"
    PAYMENT_EXECUTION_READ = "COMPANY_PAYROLL_PAYMENT_EXECUTION_READ"
    PAYMENT_SETTLEMENT_RECONCILE = "COMPANY_PAYROLL_PAYMENT_SETTLEMENT_RECONCILE"
    PAYMENT_EXECUTION_RECOVER = "COMPANY_PAYROLL_PAYMENT_EXECUTION_RECOVER"
    ACCOUNTING_POLICY_READ = "COMPANY_PAYROLL_ACCOUNTING_POLICY_READ"
    ACCOUNTING_POLICY_MANAGE = "COMPANY_PAYROLL_ACCOUNTING_POLICY_MANAGE"
    ACCOUNTING_POLICY_APPROVE = "COMPANY_PAYROLL_ACCOUNTING_POLICY_APPROVE"
    ACCOUNTING_MAPPING_READ = "COMPANY_PAYROLL_ACCOUNTING_MAPPING_READ"
    ACCOUNTING_MAPPING_MANAGE = "COMPANY_PAYROLL_ACCOUNTING_MAPPING_MANAGE"
    ACCOUNTING_MAPPING_APPROVE = "COMPANY_PAYROLL_ACCOUNTING_MAPPING_APPROVE"
    ACCOUNTING_PREPARE = "COMPANY_PAYROLL_ACCOUNTING_PREPARE"
    ADJUSTMENT_READ = "COMPANY_PAYROLL_ADJUSTMENT_READ"
    ADJUSTMENT_MANAGE = "COMPANY_PAYROLL_ADJUSTMENT_MANAGE"
    ADJUSTMENT_REVIEW = "COMPANY_PAYROLL_ADJUSTMENT_REVIEW"
    ADJUSTMENT_APPROVE = "COMPANY_PAYROLL_ADJUSTMENT_APPROVE"
    ADJUSTMENT_CALCULATE = "COMPANY_PAYROLL_ADJUSTMENT_CALCULATE"

    ALL = (
        POLICY_READ,
        POLICY_MANAGE,
        POLICY_APPROVE,
        COMPENSATION_READ,
        COMPENSATION_MANAGE,
        COMPENSATION_APPROVE,
        ADMISSION_REVIEW,
        CALCULATION_EXECUTE,
        CALCULATION_READ,
        CALCULATION_REVIEW,
        TAX_AUTHORITY_READ,
        TAX_AUTHORITY_MANAGE,
        TAX_AUTHORITY_APPROVE,
        DEDUCTION_AUTHORITY_READ,
        DEDUCTION_AUTHORITY_MANAGE,
        DEDUCTION_AUTHORITY_APPROVE,
        TAX_CALCULATION_EXECUTE,
        TAX_CALCULATION_READ,
        TAX_RESULT_READ,
        TAX_RESULT_REVIEW,
        RUN_ASSEMBLE,
        RUN_READ,
        RUN_REVIEW,
        RUN_APPROVE,
        PAYMENT_INSTRUCTION_READ,
        PAYMENT_INSTRUCTION_MANAGE,
        PAYMENT_RELEASE_ASSEMBLE,
        PAYMENT_RELEASE_READ,
        PAYMENT_RELEASE_REVIEW,
        PAYMENT_RELEASE_APPROVE,
        PAYMENT_EXECUTION_AUTHORIZE,
        PAYMENT_EXECUTION_READ,
        PAYMENT_SETTLEMENT_RECONCILE,
        PAYMENT_EXECUTION_RECOVER,
        ACCOUNTING_POLICY_READ,
        ACCOUNTING_POLICY_MANAGE,
        ACCOUNTING_POLICY_APPROVE,
        ACCOUNTING_MAPPING_READ,
        ACCOUNTING_MAPPING_MANAGE,
        ACCOUNTING_MAPPING_APPROVE,
        ACCOUNTING_PREPARE,
        ADJUSTMENT_READ,
        ADJUSTMENT_MANAGE,
        ADJUSTMENT_REVIEW,
        ADJUSTMENT_APPROVE,
        ADJUSTMENT_CALCULATE,
    )
