import { useState, type FormEvent } from "react";
import { useHasPermission } from "../auth";
import { useAPAging, useAPMutations } from "../hooks/useAccountsPayable";
import { Alert, Button, Card, CardContent, CardDescription, CardHeader, CardTitle, Input, Spinner } from "../ui";
import { ProcurementMatchWorkbench } from "../components/purchasing/ProcurementMatchWorkbench";
const today = () => new Date().toISOString().slice(0, 10);
export function AccountsPayableRoute() {
  const canRead = useHasPermission("COMPANY_ACCOUNTS_PAYABLE_READ"); const canManageVendors = useHasPermission("COMPANY_ACCOUNTS_PAYABLE_VENDOR_MANAGE"); const canReviewMatches = useHasPermission("COMPANY_ACCOUNTS_PAYABLE_MATCH_REVIEW");
  const [asOf, setAsOf] = useState(today()); const [vendor, setVendor] = useState({ code: "", legal_name: "", display_name: "", provenance: "manual" });
  const aging = useAPAging(asOf); const mutations = useAPMutations();
  if (!canRead) return <Alert variant="danger">You are not authorized to view Accounts Payable.</Alert>;
  const submitVendor = async (event: FormEvent) => { event.preventDefault(); await mutations.createVendor.mutateAsync(vendor); setVendor({ code: "", legal_name: "", display_name: "", provenance: "manual" }); };
  return <div className="mx-auto max-w-6xl space-y-6 pb-12"><header><p className="text-sm font-semibold text-action-primary">Financial Operations</p><h1 className="mt-1 text-2xl font-bold sm:text-3xl">Accounts Payable</h1><p className="mt-2 text-content-muted">Conventional vendor liabilities, credits, aging, and verified disbursement evidence. Company-card charges are not vendor bills.</p></header><Alert>AP is fail-closed: missing mappings, closed periods, duplicate evidence, and missing posting receipts remain explicit exceptions.</Alert>
  <Card><CardHeader><CardTitle>Open-item aging inputs</CardTitle><CardDescription>Presentation buckets are Finance-owned. Rows preserve bill and due-date evidence.</CardDescription></CardHeader><CardContent><label className="mb-3 block text-sm">As of <Input aria-label="Aging as of" type="date" value={asOf} onChange={(event) => setAsOf(event.target.value)} /></label>{aging.isPending ? <Spinner label="Loading AP aging" /> : aging.isError ? <Alert variant="danger">AP aging could not be loaded.</Alert> : aging.data?.length ? <ul className="space-y-2">{aging.data.map((row) => <li className="flex flex-wrap justify-between gap-2 rounded-lg border border-stroke p-3" key={row.bill_id}><span>{row.bill_number}</span><span>{row.open_amount} {row.currency} · {row.days_past_due} days past due · {row.status}</span></li>)}</ul> : <p className="text-content-muted">No conventional AP open items are recorded for this date. Missing evidence is never reported as zero.</p>}</CardContent></Card>
  <ProcurementMatchWorkbench canReview={canReviewMatches} />
  {canManageVendors && <Card><CardHeader><CardTitle>Create accounting vendor</CardTitle><CardDescription>Accounting identity is separate from Purchasing. Banking and tax credentials are not collected here.</CardDescription></CardHeader><CardContent><form className="grid gap-3 sm:grid-cols-2" onSubmit={(event) => void submitVendor(event)}><Input aria-label="Vendor code" required value={vendor.code} onChange={(event) => setVendor({...vendor, code:event.target.value})}/><Input aria-label="Legal name" required value={vendor.legal_name} onChange={(event) => setVendor({...vendor, legal_name:event.target.value})}/><Input aria-label="Display name" required value={vendor.display_name} onChange={(event) => setVendor({...vendor, display_name:event.target.value})}/><Button type="submit" loading={mutations.createVendor.isPending}>Create vendor</Button></form></CardContent></Card>}</div>;
}
