import { useState,type FormEvent } from "react";
import { useHasPermission } from "../auth";
import { useAsset,useAssetMutations,useAssets } from "../hooks/useAssets";
import { Alert,Badge,Button,Card,CardContent,CardDescription,CardHeader,CardTitle,Input,Spinner } from "../ui";

const labels:Record<string,string>={customer_equipment:"Customer Equipment",vehicle:"Fleet Vehicle",tool:"Tracked Tool",equipment:"Operational Equipment",other_supported_asset:"Other Asset"};
export function AssetsRoute(){
 const canRead=useHasPermission("COMPANY_ASSET_READ"),canManage=useHasPermission("COMPANY_ASSET_MANAGE");
 const [q,setQ]=useState(""),[selected,setSelected]=useState(""),[form,setForm]=useState({branch_id:"",asset_number:"",asset_class:"customer_equipment",display_name:""});
 const assets=useAssets(q),detail=useAsset(selected),mutations=useAssetMutations();
 if(!canRead)return <Alert variant="danger">You are not authorized to view operational Assets.</Alert>;
 const submit=async(e:FormEvent)=>{e.preventDefault();const row=await mutations.create.mutateAsync({...form,provenance:{source:"operator_recorded"},idempotency_key:crypto.randomUUID()});setSelected(row.id);};
 return <div className="mx-auto max-w-7xl space-y-6 pb-12"><header><p className="text-sm font-semibold text-action-primary">Operations</p><h1 className="text-3xl font-bold">Assets, Equipment & Fleet</h1><p className="text-content-muted">Provider-neutral physical identity, evidence, readiness, and custody. No Accounting or Inventory quantity authority.</p></header>
 <div className="grid gap-4 lg:grid-cols-[minmax(0,2fr)_minmax(18rem,1fr)]"><Card><CardHeader><CardTitle>Asset directory</CardTitle><CardDescription>Company-scoped results intentionally omit broad sensitive identifier search.</CardDescription></CardHeader><CardContent><Input aria-label="Search Assets" value={q} onChange={e=>setQ(e.target.value)} placeholder="Asset number or display name"/>{assets.isPending?<Spinner label="Loading Assets"/>:assets.isError?<Alert variant="danger">Asset authority is temporarily unavailable.</Alert>:<div className="mt-4 space-y-2">{assets.data?.map(a=><button className="min-h-11 w-full rounded-lg border border-stroke p-3 text-left focus-visible:outline focus-visible:outline-2 focus-visible:outline-focus" key={a.id} onClick={()=>setSelected(a.id)}><span className="flex justify-between gap-2"><strong>{a.asset_number} · {a.display_name}</strong><Badge>{a.lifecycle}</Badge></span><span className="text-sm text-content-muted">{labels[a.asset_class]} · Branch {a.branch_id}</span></button>)}{!assets.data?.length&&<p className="py-4 text-content-muted">No Assets match this authorized scope.</p>}</div>}</CardContent></Card>
 <Card><CardHeader><CardTitle>Evidence & readiness</CardTitle></CardHeader><CardContent>{!selected?<p className="text-content-muted">Select an Asset to inspect immutable evidence.</p>:detail.isPending?<Spinner label="Loading Asset evidence"/>:detail.isError||!detail.data?<Alert variant="danger">Asset evidence could not be reconciled.</Alert>:<div className="space-y-4"><div><strong>{detail.data.asset.display_name}</strong><p className="break-all text-sm text-content-muted">{detail.data.asset.id}</p></div><Alert variant={detail.data.readiness==="READY"?"success":"warning"}>{detail.data.readiness.replaceAll("_"," ")}{detail.data.readiness_reasons.length?`: ${detail.data.readiness_reasons.join("; ")}`:""}</Alert><section><h3 className="font-semibold">Relationships</h3>{detail.data.relationships.map(x=><p className="break-all text-sm" key={x.id}>{x.relationship_type.replaceAll("_"," ")} · {x.related_entity_id}</p>)}{!detail.data.relationships.length&&<p className="text-sm text-content-muted">No Customer, Location, Job, Employee, vehicle, or Inventory-location relationship recorded.</p>}</section><section><h3 className="font-semibold">History</h3>{detail.data.evidence.map(x=><div className="border-t border-stroke py-2 text-sm" key={x.id}>{x.evidence_type.replaceAll("_"," ")} · {x.state.replaceAll("_"," ")}<br/><span className="text-content-muted">{new Date(x.occurred_at).toLocaleString()}</span></div>)}{!detail.data.evidence.length&&<p className="text-sm text-content-muted">No supporting evidence recorded.</p>}</section></div>}</CardContent></Card></div>
 {canManage?<Card><CardHeader><CardTitle>Register Asset</CardTitle><CardDescription>Real identifiers are not required. Missing evidence remains unknown.</CardDescription></CardHeader><CardContent><form className="grid gap-3 sm:grid-cols-2" onSubmit={e=>void submit(e)}><Input required aria-label="Branch ID" value={form.branch_id} onChange={e=>setForm({...form,branch_id:e.target.value})}/><Input required aria-label="Asset number" value={form.asset_number} onChange={e=>setForm({...form,asset_number:e.target.value})}/><label className="text-sm font-medium">Asset class<select className="mt-1 min-h-11 w-full rounded-md border border-stroke bg-surface px-3" value={form.asset_class} onChange={e=>setForm({...form,asset_class:e.target.value})}>{Object.entries(labels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><Input required aria-label="Display name" value={form.display_name} onChange={e=>setForm({...form,display_name:e.target.value})}/><Button type="submit" loading={mutations.create.isPending}>Register Asset</Button></form>{mutations.create.isError&&<Alert variant="danger">Asset registration failed safely. Refresh current authority or correct the request.</Alert>}</CardContent></Card>:<Alert>Read-only access: Asset evidence is visible, but mutation controls require Asset management authority.</Alert>}</div>;
}
