import { useMemo, useState } from "react";
import { useHasPermission } from "../auth";
import type { EconomicsJob, EconomicsRollup, QualityState } from "../api/businessEconomics";
import { useEconomicsResult, useEconomicsWorkspace } from "../hooks/useBusinessEconomics";
import { Alert, Button, Card, CardContent, CardDescription, CardHeader, CardTitle, Input, Spinner } from "../ui";

const today = new Date().toISOString().slice(0, 10);
const monthStart = `${today.slice(0, 7)}-01`;
const money = (minor: number | null | undefined, currency = "USD") => minor == null ? "Unavailable" : new Intl.NumberFormat(undefined, { style: "currency", currency }).format(minor / 100);
const qualityLabel = (value: string) => value.replaceAll("_", " ");
const qualityTone = (value: QualityState) => value === "complete" ? "text-status-success" : value === "unavailable" || value === "conflicting" ? "text-status-danger" : "text-status-warning";

function RollupTable({ title, rows, currency }: { title: string; rows: EconomicsRollup[]; currency: string }) {
  return <Card><CardHeader><CardTitle>{title}</CardTitle><CardDescription>Admitted complete Jobs reconcile to these totals; incomplete Jobs remain counted.</CardDescription></CardHeader><CardContent>{rows.length ? <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left"><th>Group</th><th>Jobs</th><th>Revenue</th><th>Contribution</th><th>Evidence</th></tr></thead><tbody>{rows.map((row) => <tr className="border-b border-stroke" key={row.label}><td className="py-3 font-medium">{row.label}</td><td>{row.complete_jobs}/{row.jobs}</td><td>{money(row.revenue_minor, currency)}</td><td className={row.contribution_minor < 0 ? "text-status-danger" : ""}>{money(row.contribution_minor, currency)}</td><td className={`capitalize ${qualityTone(row.quality_state)}`}>{qualityLabel(row.quality_state)}</td></tr>)}</tbody></table></div> : <p className="text-content-muted">No classified admitted Jobs for this view.</p>}</CardContent></Card>;
}

function JobTable({ jobs, currency, onSelect }: { jobs: EconomicsJob[]; currency: string; onSelect: (id: string) => void }) {
  return <Card><CardHeader><CardTitle>Where are we making—or losing—money?</CardTitle><CardDescription>Job contribution uses economic recognition evidence, not cash collection. Select a Job to inspect why.</CardDescription></CardHeader><CardContent>{jobs.length ? <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead><tr className="text-left"><th>Job</th><th>Customer</th><th>Service</th><th>Revenue</th><th>Labor</th><th>Materials</th><th>Contribution</th><th>Confidence</th></tr></thead><tbody>{jobs.map((job) => <tr className="border-b border-stroke" key={job.result_id}><td className="py-3"><Button variant="ghost" onClick={() => onSelect(job.result_id)}>{job.job_number}</Button><div className="text-xs capitalize text-content-muted">{qualityLabel(job.job_status)}</div></td><td>{job.customer_name}</td><td>{job.service_category ?? "Unclassified"}</td><td>{money(job.revenue_minor, currency)}</td><td>{money(job.labor_minor, currency)}</td><td>{money(job.materials_minor, currency)}</td><td className={job.contribution_minor != null && job.contribution_minor < 0 ? "font-semibold text-status-danger" : "font-semibold"}>{money(job.contribution_minor, currency)}</td><td><span className={`capitalize ${qualityTone(job.quality_state)}`}>{qualityLabel(job.quality_state)}</span><div>{job.confidence_percent}%</div></td></tr>)}</tbody></table></div> : <p className="text-content-muted">No admitted Job profitability exists for this period.</p>}</CardContent></Card>;
}

export function BusinessEconomicsRoute() {
  const canRead = useHasPermission("COMPANY_ECONOMICS_MEASUREMENT_READ");
  const [start, setStart] = useState(monthStart); const [end, setEnd] = useState(today);
  const [scope, setScope] = useState({ start: monthStart, end: today }); const [selected, setSelected] = useState<string | null>(null);
  const workspace = useEconomicsWorkspace(scope.start, scope.end); const detail = useEconomicsResult(selected);
  const sortedLosses = useMemo(() => workspace.data?.jobs.filter((job) => job.contribution_minor != null && job.contribution_minor < 0) ?? [], [workspace.data]);
  if (!canRead) return <Alert variant="danger">You are not authorized to view Business Economics.</Alert>;
  if (workspace.isPending) return <Spinner label="Loading Business Economics" />;
  if (workspace.isError || !workspace.data) return <Alert variant="danger" title="Economics unavailable">Accepted profitability evidence could not be loaded. No value was inferred.</Alert>;
  const value = workspace.data; const currency = value.currency ?? "USD"; const directCost = value.totals ? value.totals.labor + value.totals.materials + value.totals.equipment + value.totals.truck : null;
  return <div className="mx-auto max-w-7xl space-y-6 pb-12"><header><p className="text-sm font-semibold text-action-primary">Owner Intelligence</p><h1 className="mt-1 text-2xl font-bold sm:text-3xl">Business Economics</h1><p className="mt-2 max-w-3xl text-content-muted">Authoritative profitability from admitted Jobs, revenue, labor, materials, and approved allocation evidence—with missing evidence kept visible.</p></header>
    <Card><CardContent className="pt-6"><form className="grid gap-3 sm:grid-cols-[1fr_1fr_auto]" onSubmit={(event) => { event.preventDefault(); setScope({ start, end }); setSelected(null); }}><Input aria-label="Start date" type="date" value={start} onChange={(event) => setStart(event.target.value)} /><Input aria-label="End date" type="date" value={end} onChange={(event) => setEnd(event.target.value)} /><Button type="submit">Compare period</Button></form></CardContent></Card>
    <Alert variant={value.quality_state === "complete" ? "success" : value.quality_state === "unavailable" || value.quality_state === "conflicting" ? "danger" : "warning"} title={`Evidence ${qualityLabel(value.quality_state)}`}>{value.explanation} {value.fully_allocated_available ? "Fully allocated profitability is available." : "Fully allocated profitability is unavailable until an approved indirect-cost policy is configured."}</Alert>
    <section aria-label="How are we doing?" className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Card><CardHeader><CardTitle>Revenue</CardTitle><CardDescription>Economically recognized</CardDescription></CardHeader><CardContent className="text-2xl font-bold">{money(value.totals?.revenue, currency)}</CardContent></Card><Card><CardHeader><CardTitle>Direct cost</CardTitle><CardDescription>Labor, material, equipment, truck</CardDescription></CardHeader><CardContent className="text-2xl font-bold">{money(directCost, currency)}</CardContent></Card><Card><CardHeader><CardTitle>Contribution</CardTitle><CardDescription>Before unavailable indirect allocation</CardDescription></CardHeader><CardContent className={`text-2xl font-bold ${(value.totals?.gross_profit ?? 0) < 0 ? "text-status-danger" : ""}`}>{money(value.totals?.gross_profit, currency)}</CardContent></Card><Card><CardHeader><CardTitle>Evidence coverage</CardTitle><CardDescription>Complete admitted Jobs</CardDescription></CardHeader><CardContent className="text-2xl font-bold">{value.complete_job_count}/{value.job_count}</CardContent></Card></section>
    <Card><CardHeader><CardTitle>What changed?</CardTitle><CardDescription>{value.prior_period.start} through {value.prior_period.end}</CardDescription></CardHeader><CardContent>{value.comparison.state === "available" ? <div className="grid gap-3 sm:grid-cols-4"><p>Revenue <strong className="block">{money(value.comparison.revenue_change_minor, currency)}</strong></p><p>Contribution <strong className="block">{money(value.comparison.contribution_change_minor, currency)}</strong></p><p>Labor <strong className="block">{money(value.comparison.labor_change_minor, currency)}</strong></p><p>Materials <strong className="block">{money(value.comparison.materials_change_minor, currency)}</strong></p><p className="sm:col-span-4 text-sm text-content-muted">{value.comparison.explanation}</p></div> : <p className="text-content-muted">{value.comparison.reason}</p>}</CardContent></Card>
    <JobTable jobs={value.jobs} currency={currency} onSelect={setSelected} />
    {sortedLosses.length ? <Alert variant="warning" title={`${sortedLosses.length} admitted Job(s) have negative contribution`}>This is an observed economic condition, not a causal diagnosis. Open each Job for evidence lineage.</Alert> : null}
    <section className="grid gap-4 xl:grid-cols-3"><RollupTable title="Service/category profitability" rows={value.service_categories} currency={currency}/><RollupTable title="Customer profitability" rows={value.customers} currency={currency}/><RollupTable title="Branch profitability" rows={value.branches} currency={currency}/></section>
    <section className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>Readiness</CardTitle><CardDescription>What prevents a more reliable answer?</CardDescription></CardHeader><CardContent><dl className="grid gap-2 text-sm"><div className="flex justify-between"><dt>Evidence</dt><dd className="capitalize">{qualityLabel(value.readiness.evidence)}</dd></div><div className="flex justify-between"><dt>Allocation policy</dt><dd className="capitalize">{qualityLabel(value.readiness.allocation_policy)}</dd></div><div className="flex justify-between"><dt>Job attribution</dt><dd className="capitalize">{qualityLabel(value.readiness.attribution)}</dd></div></dl>{value.readiness.policy_gaps.map((gap) => <p className="mt-3 text-sm" key={gap.gap_key}><strong>{qualityLabel(gap.gap_key)}:</strong> {gap.requirement}</p>)}</CardContent></Card><Card><CardHeader><CardTitle>Beacon-ready conditions</CardTitle><CardDescription>Safe findings only; Economics creates no workflow mutation.</CardDescription></CardHeader><CardContent>{value.beacon_conditions.length ? <ul className="list-disc space-y-2 pl-5">{value.beacon_conditions.map((condition) => <li key={condition.kind}>{qualityLabel(condition.kind)} · {condition.state}</li>)}</ul> : <p className="text-content-muted">No deterministic condition is present for this scope.</p>}</CardContent></Card></section>
    {selected ? <Card><CardHeader><CardTitle>Why does this number exist?</CardTitle><CardDescription>Accepted calculation, evidence, confidence, limitation, and digest lineage.</CardDescription></CardHeader><CardContent>{detail.isPending ? <Spinner label="Loading explanation"/> : detail.isError || !detail.data ? <Alert variant="danger">The result explanation could not be verified.</Alert> : <div className="space-y-4"><p>{detail.data.explanation?.answer ?? "Legacy result detail is unavailable; no explanation was fabricated."}</p><dl className="grid gap-2 text-sm sm:grid-cols-2"><div><dt className="text-content-muted">Completeness</dt><dd>{detail.data.quality?.completeness_percent ?? "Unavailable"}{detail.data.quality?.completeness_percent != null ? "%" : ""}</dd></div><div><dt className="text-content-muted">Freshness</dt><dd className="capitalize">{qualityLabel(detail.data.quality?.freshness_status ?? "unavailable")}</dd></div><div><dt className="text-content-muted">Missing evidence</dt><dd>{detail.data.quality?.missing_categories?.length ? detail.data.quality.missing_categories.map(qualityLabel).join(", ") : "None identified"}</dd></div><div><dt className="text-content-muted">Allocation authority</dt><dd>{detail.data.lineage.allocation_digests.length ? `${detail.data.lineage.allocation_digests.length} accepted allocation input(s)` : "No accepted allocation authority"}</dd></div></dl>{Object.entries(detail.data.components ?? {}).map(([name, component]) => <section className="border-t border-stroke pt-3" key={name}><h3 className="font-semibold capitalize">{qualityLabel(name)} · {money(component.amount_minor, detail.data!.currency)}</h3><p className="text-sm text-content-muted">{component.explanation}</p><p className="mt-1 text-xs">{component.evidence.length} source record(s) · {component.confidence_percent}% confidence</p>{component.evidence.length ? <p className="mt-1 text-xs text-content-muted">Authority: {[...new Set(component.evidence.map((item) => `${item.source_system} / ${item.record_type}`))].join(", ")}</p> : null}</section>)}<dl className="grid gap-2 border-t border-stroke pt-3 text-xs text-content-muted"><div><dt>Measurement package digest</dt><dd className="break-all">{detail.data.lineage.package_digest}</dd></div><div><dt>Computation digest</dt><dd className="break-all">{detail.data.lineage.computation_digest}</dd></div><div><dt>Result digest</dt><dd className="break-all">{detail.data.lineage.result_digest}</dd></div></dl></div>}</CardContent></Card> : null}
  </div>;
}
