import { Activity, Clock3, Factory, Gauge, ShieldAlert } from "lucide-react";
import { Link, useSearchParams } from "react-router";

import type { FactoryLane } from "../api/factoryControl";
import { useAuth } from "../auth";
import { useFactoryControlOverview, useFactoryLaneDrilldown } from "../hooks/useFactoryControl";
import { Alert, Badge, Card, CardContent, CardHeader, CardTitle, Spinner } from "../ui";

const percent = (value: number) => `${Math.max(0, Math.min(100, value)).toFixed(1)}%`;
const timestamp = (value?: string | null) => value ? new Date(value).toLocaleString() : "Not reported";
const duration = (seconds?: number | null) => seconds == null ? "Not reported" : `${Math.round(seconds / 60)} min`;
const measured = (status: string, value: string) => status === "MEASURED" ? value : "Not yet measured";

function Metric({ label, value }: { label: string; value: string }) {
  return <Card><CardContent className="pt-5"><p className="text-sm text-content-muted">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p></CardContent></Card>;
}

function LaneRow({ lane }: { lane: FactoryLane }) {
  return <tr className="border-t border-border-subtle">
    <td className="px-3 py-3 font-medium"><Link className="text-action-primary hover:underline" to={`/admin/factory-control?lane=${encodeURIComponent(lane.lane_code)}`}>{lane.lane_code}</Link></td>
    <td className="px-3 py-3">{lane.machine ?? "Not reported"}</td>
    <td className="px-3 py-3">{lane.current_assignment ?? lane.milestone_code ?? "Unassigned"}</td>
    <td className="px-3 py-3">{lane.next_queued_item ?? "None reported"}</td>
    <td className="px-3 py-3"><Badge>{lane.lifecycle_state.replaceAll("_", " ")}</Badge></td>
    <td className="px-3 py-3">{lane.controlling_enterprise ?? "Not reported"}</td>
    <td className="px-3 py-3">{lane.self_refill_health?.replaceAll("_", " ") ?? "Not reported"}</td>
    <td className="px-3 py-3"><Badge>{lane.sla_state.replaceAll("_", " ")}</Badge>{lane.idle_duration_seconds == null ? null : <span className="ml-2 text-xs text-content-muted">{duration(lane.idle_duration_seconds)}</span>}</td>
    <td className="px-3 py-3">{lane.queue_depth}</td>
    <td className="px-3 py-3 text-content-muted">{timestamp(lane.last_handoff_at)}</td>
  </tr>;
}

export function FactoryControlRoute() {
  const { permissionCodes = [] } = useAuth();
  const authorized = permissionCodes.includes("PLATFORM_FACTORY_CONTROL_READ");
  const [search] = useSearchParams();
  const selectedLane = search.get("lane") ?? undefined;
  const overview = useFactoryControlOverview({ lane: selectedLane }, authorized);
  const drilldown = useFactoryLaneDrilldown(selectedLane, authorized);
  if (!authorized) return <Alert variant="danger" title="Factory Control is private">Platform owner or administrator authority is required.</Alert>;
  if (overview.isPending) return <Spinner label="Loading Factory Control" />;
  if (overview.isError || !overview.data) return <Alert variant="danger" title="Factory telemetry unavailable">The authoritative overview could not be loaded. No progress or health values were inferred.</Alert>;
  const data = overview.data;
  const lanes = selectedLane ? data.lanes.filter((lane) => lane.lane_code === selectedLane) : data.lanes;
  return <div className="space-y-6">
    <header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-semibold text-action-primary">Private platform administration</p><h1 className="mt-1 text-heading-l">Factory Control</h1><p className="mt-2 max-w-3xl text-content-muted">Authoritative engineering throughput, gates, quality, and handoff health. Read-only; no dispatch or release action is available here.</p></div><div className="text-right text-xs text-content-muted"><p>As of {timestamp(data.generated_at)}</p><p>{data.roadmap_milestones} roadmap milestones</p><p className="font-mono">{data.roadmap_digest}</p></div></header>
    {data.telemetry_freshness === "NOT_YET_MEASURED" && <Alert variant="warning" title="Event telemetry not yet measured">Headline progress is calculated from the canonical roadmap. Event history, lane utilization, defects, velocity, and queue measurements remain unavailable until an explicitly authorized Factory controller publishes evidence.</Alert>}
    {selectedLane && <Alert variant="information" title="Drilldown active">Showing lane {selectedLane}. <Link className="underline" to="/admin/factory-control">Clear filter</Link></Alert>}
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Engineering Completion" value={`${percent(data.metrics.engineering_percent)} · ${data.metrics.engineering_count}/${data.metrics.represented_milestones}`} /><Metric label="Beta Operability" value={`${percent(data.metrics.beta_percent)} · ${data.metrics.beta_count}/${data.metrics.represented_milestones}`} /><Metric label="Owner Accepted" value={`${percent(data.metrics.owner_percent)} · ${data.metrics.owner_count}/${data.metrics.represented_milestones}`} /><Metric label="Full-System CLOSED" value={`${percent(data.metrics.closed_percent)} · ${data.metrics.closed_count}/${data.metrics.represented_milestones}`} /></section>
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Engineering remaining weight" value={String(data.metrics.engineering_remaining_weight)} /><Metric label="Human-gated remaining weight" value={String(data.metrics.human_gated_remaining_weight)} /><Metric label="Provider-gated remaining weight" value={String(data.metrics.provider_gated_remaining_weight)} /><Metric label="Weighted delivery" value={measured(data.metrics.velocity_history_status, percent(data.metrics.weighted_delivery_percent))} /></section>
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Open defects" value={measured(data.metrics.event_history_status, String(data.metrics.open_defects))} /><Metric label="Open gates" value={measured(data.metrics.event_history_status, String(data.metrics.open_gates))} /><Metric label="Queue depth" value={measured(data.metrics.lane_history_status, String(data.metrics.queue_depth))} /><Metric label="Effective utilization" value={measured(data.metrics.lane_history_status, percent(data.metrics.effective_utilization_percent))} /></section>
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="P0 backlog" value={String(data.p0_backlog ?? 0)} /><Metric label="P1 backlog" value={String(data.p1_backlog ?? 0)} /><Metric label="Human gates" value={String(data.human_gates ?? 0)} /><Metric label="Provider gates" value={String(data.provider_gates ?? 0)} /></section>
    <Card><CardHeader><CardTitle>Current bottleneck</CardTitle></CardHeader><CardContent>{data.current_bottleneck ? <div><p className="font-medium">{data.current_bottleneck.milestone_code} — {data.current_bottleneck.title}</p><p className="mt-1 text-sm text-content-muted">{data.current_bottleneck.next_admissible_action ?? "No next action recorded."}</p></div> : <p className="text-content-muted">No open roadmap bottleneck.</p>}</CardContent></Card>
    <Card><CardHeader><CardTitle>Active P0 milestones</CardTitle></CardHeader><CardContent><ol className="space-y-2">{data.active_p0.map((item) => <li key={item.milestone_code}><span className="font-medium">{item.milestone_code}</span><span className="text-content-muted"> · {item.lifecycle_status?.replaceAll("_", " ")}</span></li>)}</ol></CardContent></Card>
    <Card><CardHeader><CardTitle>Owner action queue</CardTitle></CardHeader><CardContent>{(data.owner_actions ?? []).length === 0 ? <p className="text-content-muted">No roadmap-backed owner actions.</p> : <ol className="space-y-3">{(data.owner_actions ?? []).map((item) => <li key={String(item.milestone_code)} className="border-l-2 border-border-subtle pl-3"><p className="font-medium">{String(item.action)}</p><p className="text-xs text-content-muted">{String(item.priority)} · {String(item.gate_type).replaceAll("_", " ")} · {String(item.workflow)}</p><p className="text-xs text-content-muted">Owner time: {item.estimated_owner_minutes == null ? "Not yet estimated" : `${String(item.estimated_owner_minutes)} min`}</p></li>)}</ol>}</CardContent></Card>
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><Factory size={18}/>Worker lanes</CardTitle></CardHeader><CardContent className="overflow-x-auto">{lanes.length === 0 ? <p className="text-content-muted">Worker lane telemetry is not yet measured.</p> : <table className="min-w-full text-left text-sm"><thead><tr><th className="px-3 py-2">Lane</th><th className="px-3 py-2">Machine</th><th className="px-3 py-2">Current assignment</th><th className="px-3 py-2">Next item</th><th className="px-3 py-2">State</th><th className="px-3 py-2">Controller</th><th className="px-3 py-2">Self-refill</th><th className="px-3 py-2">SLA</th><th className="px-3 py-2">Queue</th><th className="px-3 py-2">Last handoff</th></tr></thead><tbody>{lanes.map((lane) => <LaneRow key={lane.lane_code} lane={lane} />)}</tbody></table>}</CardContent></Card>
    {selectedLane && <Card><CardHeader><CardTitle>Lane event evidence</CardTitle></CardHeader><CardContent>{drilldown.isPending ? <Spinner label="Loading lane evidence" /> : drilldown.isError ? <Alert variant="danger" title="Lane evidence unavailable">No event history was inferred.</Alert> : <ol className="space-y-3">{drilldown.data?.events.map((event) => <li key={event.id} className="border-l-2 border-border-subtle pl-3"><p className="font-medium">{event.event_type.replaceAll("_", " ")}</p><p className="text-xs text-content-muted">{timestamp(event.occurred_at)} · {event.milestone_code ?? "No milestone"}</p></li>)}</ol>}</CardContent></Card>}
    <section className="grid gap-4 lg:grid-cols-3"><Card><CardHeader><CardTitle className="flex items-center gap-2"><Clock3 size={18}/>Flow</CardTitle></CardHeader><CardContent><p>Domain pickup: {measured(data.metrics.event_history_status, duration(data.metrics.domain_pickup_latency_seconds))}</p><p>Release pickup: {measured(data.metrics.event_history_status, duration(data.metrics.release_pickup_latency_seconds))}</p><p>Release latency: {measured(data.metrics.event_history_status, duration(data.metrics.release_latency_seconds))}</p><p>Eligible idle: {measured(data.metrics.lane_history_status, duration(data.metrics.eligible_idle_seconds))}</p></CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><ShieldAlert size={18}/>Quality</CardTitle></CardHeader><CardContent><p>Discovered: {measured(data.metrics.event_history_status, String(data.metrics.defects_discovered))}</p><p>Closed: {measured(data.metrics.event_history_status, String(data.metrics.defects_closed))}</p><p>Reopened: {measured(data.metrics.event_history_status, String(data.metrics.defects_reopened))}</p></CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><Gauge size={18}/>Delivery windows</CardTitle></CardHeader><CardContent><p>{measured(data.metrics.velocity_history_status, `1d ${percent(data.metrics.delivery_1d_percent)} · 3d ${percent(data.metrics.delivery_3d_percent)} · 7d ${percent(data.metrics.delivery_7d_percent)}`)}</p><p className="mt-2 flex items-center gap-2 text-content-muted"><Activity size={16}/>Controller evidence only</p></CardContent></Card></section>
    <Card><CardHeader><CardTitle>Scorecard rules</CardTitle></CardHeader><CardContent className="space-y-1 text-sm"><p>Every represented canonical milestone has equal weight. Canonically superseded milestones are excluded.</p><p>Engineering counts qualified implementation. Beta Operability requires current operator-workflow evidence; deployment alone does not count.</p><p>Owner Accepted requires recorded real acceptance. Full-System CLOSED requires the strict canonical close standard.</p></CardContent></Card>
    <Card><CardHeader><CardTitle>Recent milestone movement</CardTitle></CardHeader><CardContent>{data.recent_movements.length === 0 ? <p className="text-content-muted">Not yet measured. No authorized Factory events have been received.</p> : <ol className="space-y-2">{data.recent_movements.map((event) => <li key={event.id}><span className="font-medium">{event.event_type.replaceAll("_", " ")}</span><span className="text-content-muted"> · {event.milestone_code ?? "No milestone"} · {timestamp(event.occurred_at)}</span></li>)}</ol>}</CardContent></Card>
    <Card><CardHeader><CardTitle>Roadmap lifecycle</CardTitle></CardHeader><CardContent><div className="flex flex-wrap gap-2">{Object.entries(data.lifecycle_counts).map(([status, count]) => <Badge key={status}>{status.replaceAll("_", " ")}: {count}</Badge>)}</div></CardContent></Card>
  </div>;
}
