import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Link } from "react-router";
import { Activity, Building2, KeyRound, Link2, RefreshCw, ShieldCheck, Smartphone } from "lucide-react";

import { useAuth } from "../auth";
import { explainPermission, getIntegrationReadiness, getLaunchRoleMatrix, getSystemReadiness } from "../api/ownerOperations";
import { Alert, Badge, Card, Input, Spinner } from "../ui";

const statusVariant = (state: string) => state === "HEALTHY" || state === "READY" || state === "connected" || state === "ALLOWED" ? "success" as const : state === "DEGRADED" || state === "UNKNOWN" || state === "not_connected" ? "warning" as const : "neutral" as const;
const destinations = [
  ["Payroll readiness", "/payroll", "COMPANY_PAYROLL_REPORTING_READ"], ["Supply Chain", "/purchasing", "COMPANY_PURCHASING_READ"], ["Inventory", "/inventory", "COMPANY_INVENTORY_READ"], ["Accounting reports", "/financial-reports", "COMPANY_ACCOUNTING_REPORT_READ"], ["Workforce readiness", "/employees", "COMPANY_WORKFORCE_READ"], ["Audit History", "/audit", "COMPANY_AUDIT_READ"], ["Report Center", "/reports", ""],
] as const;

export function OwnerOperationsRoute() {
  const { activeCompany, permissionCodes = [], user } = useAuth();
  const permissions = useMemo(() => new Set(permissionCodes), [permissionCodes]);
  const health = useQuery({ queryKey: ["owner-system-readiness"], queryFn: getSystemReadiness });
  const roles = useQuery({ queryKey: ["owner-launch-role-matrix"], queryFn: getLaunchRoleMatrix });
  const integrations = useQuery({ queryKey: ["owner-integration-readiness"], queryFn: getIntegrationReadiness, enabled: permissions.has("COMPANY_ADMINISTER") });
  const [permissionCode, setPermissionCode] = useState(""); const [branchId, setBranchId] = useState("");
  const explanation = useQuery({ queryKey: ["permission-explanation", permissionCode, branchId], queryFn: () => explainPermission(permissionCode, branchId), enabled: false });
  return <div className="space-y-6">
    <header><p className="text-sm font-medium text-action-primary">Owner inspection</p><h2 className="mt-1 text-2xl font-bold sm:text-3xl">Enterprise operations readiness</h2><p className="mt-2 text-content-muted">Read-only evidence for system health, Company and Branch access, launch roles, integrations, and module authority. Inspection does not grant execution authority.</p></header>
    <div className="grid gap-4 lg:grid-cols-3">
      <Card className="p-5 lg:col-span-2"><div className="flex items-center justify-between gap-3"><h3 className="flex items-center gap-2 text-lg font-semibold"><Activity size={18}/>System health</h3>{health.data && <Badge variant={statusVariant(health.data.state)}>{health.data.state}</Badge>}</div>{health.isLoading && <Spinner label="Loading system readiness"/>}{health.isError && <Alert variant="danger">System readiness is temporarily unavailable.</Alert>}{health.data && <div className="mt-4 grid gap-2 sm:grid-cols-2">{health.data.components.map((item) => <div key={item.component} className="rounded-lg border border-stroke p-3"><div className="flex justify-between gap-2"><strong>{item.component}</strong><Badge variant={statusVariant(item.state)}>{item.state}</Badge></div><p className="mt-1 text-xs text-content-muted">{item.reason} · {item.classification}{item.required ? " · required" : " · degradable"}</p></div>)}</div>} {health.data && <p className="mt-4 text-xs text-content-muted">Release {health.data.version} · {health.data.environment} · observed {new Date(health.data.observed_at).toLocaleString()}</p>}</Card>
      <Card className="p-5"><h3 className="flex items-center gap-2 text-lg font-semibold"><Building2 size={18}/>Company and Branches</h3><p className="mt-3 font-semibold">{activeCompany?.name ?? "No active Company"}</p><p className="text-xs text-content-muted">{activeCompany?.code} · {activeCompany?.has_all_branch_access ? "All Branch authority" : "Explicit Branch grants"}</p><div className="mt-3 space-y-2">{activeCompany?.branches.map((branch) => <div key={branch.id} className="rounded-lg bg-surface-subtle p-3 text-sm"><strong>{branch.name}</strong><p className="text-xs text-content-muted">{branch.code}{branch.is_primary ? " · primary" : ""}</p></div>)}</div></Card>
    </div>
    <div className="grid gap-4 lg:grid-cols-2">
      <Card className="p-5"><h3 className="flex items-center gap-2 text-lg font-semibold"><Link2 size={18}/>Integration readiness</h3>{!permissions.has("COMPANY_ADMINISTER") ? <p className="mt-3 text-sm text-content-muted">Owner administration permission is required to inspect integration state.</p> : integrations.isLoading ? <Spinner label="Loading integrations"/> : integrations.isError ? <Alert variant="danger">Integration readiness is unavailable. No provider action was attempted.</Alert> : integrations.data && <div className="mt-4 space-y-3"><div className="flex justify-between rounded-lg border border-stroke p-3"><span>QuickBooks Development</span><Badge variant={statusVariant(integrations.data.qbo)}>{integrations.data.qbo}</Badge></div><div className="flex justify-between rounded-lg border border-stroke p-3"><span>HCP migration</span><Badge variant={statusVariant(integrations.data.migration.overall_status)}>{integrations.data.migration.overall_status}</Badge></div>{integrations.data.migration.owner_decisions.map((item) => <p key={item.decision} className="text-sm text-content-muted">{item.decision}: {item.state}</p>)}</div>}</Card>
      <Card className="p-5"><h3 className="flex items-center gap-2 text-lg font-semibold"><Smartphone size={18}/>Employee and mobile readiness</h3><p className="mt-3 text-sm text-content-muted">Current identity: {user?.display_name ?? "Unavailable"}. Mobile access requires an active Membership→Employee binding, Branch authority, and explicit own-data or field permissions.</p><div className="mt-3 flex flex-wrap gap-2">{["COMPANY_JOB_EXECUTE", "COMPANY_TIMEKEEPING_OWN_READ", "COMPANY_TIMEKEEPING_OWN_PUNCH"].map((code) => <Badge key={code} variant={permissions.has(code) ? "success" : "neutral"}>{permissions.has(code) ? "available" : "missing"}: {code}</Badge>)}</div><p className="mt-3 text-xs text-content-muted">This view never exposes passwords, tokens, signing material, Payroll values, or another Employee's data.</p></Card>
    </div>
    <Card className="p-5"><h3 className="flex items-center gap-2 text-lg font-semibold"><KeyRound size={18}/>Permission explainability</h3><form className="mt-4 grid gap-3 md:grid-cols-[1fr_1fr_auto]" onSubmit={(event) => { event.preventDefault(); void explanation.refetch(); }}><label className="text-sm"><span className="mb-1 block font-medium">Permission code</span><Input required value={permissionCode} onChange={(event) => setPermissionCode(event.target.value)} placeholder="COMPANY_JOB_READ"/></label><label className="text-sm"><span className="mb-1 block font-medium">Optional Branch ID</span><Input value={branchId} onChange={(event) => setBranchId(event.target.value)} placeholder="Branch UUID"/></label><button className="min-h-10 self-end rounded-lg bg-action-primary px-4 font-semibold text-white" type="submit">Explain access</button></form>{explanation.data && <div className="mt-4 rounded-lg border border-stroke p-4"><Badge variant={statusVariant(explanation.data.decision)}>{explanation.data.decision}</Badge><p className="mt-2 text-sm">{explanation.data.reasons.join(" · ")}</p></div>}{explanation.isError && <Alert variant="danger">Permission explanation requires a valid current authorization context and Branch identifier.</Alert>}</Card>
    <Card className="p-5"><h3 className="flex items-center gap-2 text-lg font-semibold"><ShieldCheck size={18}/>Canonical launch roles</h3>{roles.isLoading && <Spinner label="Loading launch roles"/>}{roles.isError && <Alert variant="danger">Role inspection requires role-read permission.</Alert>}{roles.data && <div className="mt-4 grid gap-3 md:grid-cols-2">{roles.data.map((role) => <details key={role.code} className="rounded-lg border border-stroke p-4"><summary className="cursor-pointer font-semibold">{role.code} · {role.permission_codes.length} permissions</summary><p className="mt-2 text-sm text-content-muted">{role.purpose}</p><ul className="mt-3 max-h-48 space-y-1 overflow-auto text-xs">{role.permission_codes.map((code) => <li key={code}><code>{code}</code></li>)}</ul></details>)}</div>}</Card>
    <Card className="p-5"><h3 className="text-lg font-semibold">Owning workspaces</h3><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{destinations.filter(([, , required]) => !required || permissions.has(required)).map(([label, path]) => <Link key={path} to={path} className="flex min-h-11 items-center justify-between rounded-lg border border-stroke px-3 text-sm font-semibold hover:bg-surface-subtle">{label}<RefreshCw size={15}/></Link>)}</div></Card>
  </div>;
}
