import { useState, type FormEvent } from "react";
import { useAuth, useHasPermission } from "../auth";
import { usePriceBook, usePriceBookMutations } from "../hooks/usePriceBook";
import { Alert, Badge, Button, Card, CardContent, CardDescription, CardHeader, CardTitle, Input, Select, Spinner } from "../ui";

export function PriceBookRoute() {
  const { activeCompany } = useAuth(); const canRead = useHasPermission("COMPANY_PRICE_BOOK_READ"); const canManage = useHasPermission("COMPANY_PRICE_BOOK_MANAGE"); const canActivate = useHasPermission("COMPANY_PRICE_BOOK_ACTIVATE"); const [branch, setBranch] = useState(""); const catalog = usePriceBook(branch || undefined, canRead); const mutations = usePriceBookMutations();
  const [category, setCategory] = useState({ code: "", name: "" });
  const [tax, setTax] = useState({ code: "", name: "", taxable: true });
  const [optionGroup, setOptionGroup] = useState({ code: "", name: "" });
  const [option, setOption] = useState({ groupId: "", serviceItemId: "", label: "", position: "1" });
  const [item, setItem] = useState({ category_id: "", code: "", name: "", customer_description: "" });
  const [draft, setDraft] = useState({ itemId: "", taxId: "", price: "", effective: "", componentType: "labor" as "labor" | "material", componentLabel: "", componentQuantity: "1", componentCost: "" });
  if (!activeCompany) return <Alert variant="danger">Select an accessible Company before opening Price Book.</Alert>;
  if (!canRead) return <Alert variant="danger">You are not authorized to view Price Book.</Alert>;
  const submitCategory = async (event: FormEvent) => { event.preventDefault(); await mutations.category.mutateAsync(category); setCategory({ code: "", name: "" }); };
  const submitTax = async (event: FormEvent) => { event.preventDefault(); await mutations.tax.mutateAsync(tax); setTax({ code: "", name: "", taxable: true }); };
  const submitOptionGroup = async (event: FormEvent) => { event.preventDefault(); await mutations.optionGroup.mutateAsync(optionGroup); setOptionGroup({ code: "", name: "" }); };
  const submitOption = async (event: FormEvent) => { event.preventDefault(); await mutations.option.mutateAsync({ groupId: option.groupId, data: { service_item_id: option.serviceItemId, label: option.label, position: Number(option.position) } }); setOption({ groupId: "", serviceItemId: "", label: "", position: "1" }); };
  const submitItem = async (event: FormEvent) => { event.preventDefault(); await mutations.item.mutateAsync({ ...item, branch_id: branch || undefined }); setItem({ category_id: "", code: "", name: "", customer_description: "" }); };
  const submitDraft = async (event: FormEvent) => { event.preventDefault(); await mutations.version.mutateAsync({ itemId: draft.itemId, data: { branch_id: branch || undefined, tax_classification_id: draft.taxId, currency: "USD", unit_price: draft.price, effective_at: new Date(draft.effective).toISOString(), components: [{ component_type: draft.componentType, label: draft.componentLabel, quantity: draft.componentQuantity, unit_cost: draft.componentCost || undefined }] } }); };
  return <div className="mx-auto max-w-6xl space-y-6 pb-10">
    <header><p className="text-sm font-semibold text-action-primary">Sales / Commercial Operations</p><h1 className="mt-1 text-2xl font-bold sm:text-3xl">Price Book</h1><p className="mt-2 text-content-muted">Create controlled service prices and activate immutable commercial versions.</p></header>
    <Card><CardHeader><CardTitle>Catalog scope</CardTitle><CardDescription>Company-wide items are visible in every Branch. Branch items remain local.</CardDescription></CardHeader><CardContent><Select aria-label="Price Book Branch" value={branch} onChange={(event) => setBranch(event.target.value)}><option value="">All Company prices</option>{activeCompany.branches.map((b) => <option key={b.id} value={b.id}>{b.name}</option>)}</Select></CardContent></Card>
    {catalog.isPending ? <Spinner label="Loading Price Book" /> : catalog.isError ? <Alert variant="danger">Price Book could not be loaded.</Alert> : <>
      {canManage && <section className="grid gap-4 lg:grid-cols-3">
        <Card><CardHeader><CardTitle>New category</CardTitle></CardHeader><CardContent><form className="space-y-3" onSubmit={(e) => void submitCategory(e)}><Input aria-label="Category code" placeholder="Code" value={category.code} onChange={(e) => setCategory({ ...category, code: e.target.value })} required /><Input aria-label="Category name" placeholder="Name" value={category.name} onChange={(e) => setCategory({ ...category, name: e.target.value })} required /><Button fullWidth type="submit" loading={mutations.category.isPending}>Create category</Button></form></CardContent></Card>
        <Card><CardHeader><CardTitle>New service item</CardTitle></CardHeader><CardContent><form className="space-y-3" onSubmit={(e) => void submitItem(e)}><Select aria-label="Service category" value={item.category_id} onChange={(e) => setItem({ ...item, category_id: e.target.value })} required><option value="">Category</option>{catalog.data?.categories.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</Select><Input aria-label="Service code" placeholder="Code" value={item.code} onChange={(e) => setItem({ ...item, code: e.target.value })} required /><Input aria-label="Service name" placeholder="Name" value={item.name} onChange={(e) => setItem({ ...item, name: e.target.value })} required /><Input aria-label="Customer description" placeholder="Customer description" value={item.customer_description} onChange={(e) => setItem({ ...item, customer_description: e.target.value })} required /><Button fullWidth type="submit" loading={mutations.item.isPending}>Create service item</Button></form></CardContent></Card>
        <Card><CardHeader><CardTitle>Draft price version</CardTitle></CardHeader><CardContent><form className="space-y-3" onSubmit={(e) => void submitDraft(e)}><Select aria-label="Price service item" value={draft.itemId} onChange={(e) => setDraft({ ...draft, itemId: e.target.value })} required><option value="">Service item</option>{catalog.data?.service_items.map((i) => <option key={i.id} value={i.id}>{i.name}</option>)}</Select><Select aria-label="Tax classification" value={draft.taxId} onChange={(e) => setDraft({ ...draft, taxId: e.target.value })} required><option value="">Tax classification</option>{catalog.data?.tax_classifications.map((t) => <option key={t.id} value={t.id}>{t.name}</option>)}</Select><Input aria-label="Unit price" type="number" min="0" step="0.0001" placeholder="Unit price" value={draft.price} onChange={(e) => setDraft({ ...draft, price: e.target.value })} required /><Input aria-label="Effective time" type="datetime-local" value={draft.effective} onChange={(e) => setDraft({ ...draft, effective: e.target.value })} required /><Select aria-label="Component type" value={draft.componentType} onChange={(e) => setDraft({ ...draft, componentType: e.target.value as "labor" | "material" })}><option value="labor">Labor</option><option value="material">Material</option></Select><Input aria-label="Component label" placeholder="Component label" value={draft.componentLabel} onChange={(e) => setDraft({ ...draft, componentLabel: e.target.value })} required /><Button fullWidth type="submit" loading={mutations.version.isPending}>Create draft</Button></form></CardContent></Card>
      </section>}
      {canManage && <section className="grid gap-4 lg:grid-cols-3">
        <Card><CardHeader><CardTitle>Tax classification</CardTitle><CardDescription>Define the internal tax treatment carried into snapshots.</CardDescription></CardHeader><CardContent><form className="space-y-3" onSubmit={(e) => void submitTax(e)}><Input aria-label="Tax code" placeholder="Code" value={tax.code} onChange={(e) => setTax({ ...tax, code: e.target.value })} required /><Input aria-label="Tax name" placeholder="Name" value={tax.name} onChange={(e) => setTax({ ...tax, name: e.target.value })} required /><label className="flex min-h-11 items-center gap-3"><input type="checkbox" checked={tax.taxable} onChange={(e) => setTax({ ...tax, taxable: e.target.checked })} />Taxable</label><Button fullWidth type="submit" loading={mutations.tax.isPending}>Create tax classification</Button></form></CardContent></Card>
        <Card><CardHeader><CardTitle>Customer option group</CardTitle><CardDescription>Group selectable service alternatives without changing estimate ownership.</CardDescription></CardHeader><CardContent><form className="space-y-3" onSubmit={(e) => void submitOptionGroup(e)}><Input aria-label="Option group code" placeholder="Code" value={optionGroup.code} onChange={(e) => setOptionGroup({ ...optionGroup, code: e.target.value })} required /><Input aria-label="Option group name" placeholder="Name" value={optionGroup.name} onChange={(e) => setOptionGroup({ ...optionGroup, name: e.target.value })} required /><Button fullWidth type="submit" loading={mutations.optionGroup.isPending}>Create option group</Button></form></CardContent></Card>
        <Card><CardHeader><CardTitle>Add customer option</CardTitle></CardHeader><CardContent><form className="space-y-3" onSubmit={(e) => void submitOption(e)}><Select aria-label="Option group" value={option.groupId} onChange={(e) => setOption({ ...option, groupId: e.target.value })} required><option value="">Option group</option>{catalog.data?.option_groups.map((group) => <option key={group.id} value={group.id}>{group.name}</option>)}</Select><Select aria-label="Option service item" value={option.serviceItemId} onChange={(e) => setOption({ ...option, serviceItemId: e.target.value })} required><option value="">Service item</option>{catalog.data?.service_items.map((service) => <option key={service.id} value={service.id}>{service.name}</option>)}</Select><Input aria-label="Option label" placeholder="Customer label" value={option.label} onChange={(e) => setOption({ ...option, label: e.target.value })} required /><Input aria-label="Option position" type="number" min="1" value={option.position} onChange={(e) => setOption({ ...option, position: e.target.value })} required /><Button fullWidth type="submit" loading={mutations.option.isPending}>Add option</Button></form></CardContent></Card>
      </section>}
      <Card><CardHeader><CardTitle>Service prices</CardTitle><CardDescription>Activation supersedes one overlapping active version transactionally.</CardDescription></CardHeader><CardContent><ul className="space-y-3">{catalog.data?.service_items.map((service) => { const versions = catalog.data.versions.filter((v) => v.service_item_id === service.id); return <li key={service.id} className="rounded-lg border border-stroke p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap gap-2"><strong>{service.name}</strong><code>{service.code}</code><Badge variant={service.status === "active" ? "success" : "neutral"}>{service.status}</Badge></div><p className="mt-1 text-sm text-content-muted">{service.customer_description}</p></div></div><div className="mt-3 grid gap-2">{versions.map((version) => <div key={version.id} className="flex flex-col gap-2 rounded-md bg-surface-muted p-3 sm:flex-row sm:items-center sm:justify-between"><span>Revision {version.revision} · {version.currency} {version.unit_price} · {version.status}</span>{canActivate && version.status === "draft" && <Button onClick={() => void mutations.activate.mutateAsync({ id: version.id, version: version.version })}>Activate version</Button>}</div>)}</div></li>; })}</ul></CardContent></Card>
    </>}
  </div>;
}
