import { useState, type FormEvent } from "react";
import type { CommercialPolicy, CommercialPolicyWrite } from "../../types/estimates";
import { Alert, Badge, Button, Card, CardContent, CardDescription, CardHeader, CardTitle, Input, Select } from "../../ui";

const required = ["discount", "price_override", "estimate_expiration", "rounding", "tax_readiness", "document_template", "delivery_readiness"];

export function CommercialReadiness({ branches, policies, canManage, pending, onSave }: { branches: readonly { id: string; name: string }[]; policies: readonly CommercialPolicy[]; canManage: boolean; pending: boolean; onSave: (input: CommercialPolicyWrite) => Promise<unknown> }) {
  const [form, setForm] = useState({ branch_id: "", policy_type: "discount", status: "unconfigured" as CommercialPolicy["status"], configuration: "{}", readiness_reason: "Company Commercial policy is not configured." });
  const [error, setError] = useState<string | null>(null);
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(null); try { const existing = policies.find((item) => item.branch_id === form.branch_id && item.policy_type === form.policy_type); await onSave({ ...form, configuration: JSON.parse(form.configuration) as Record<string, unknown>, expected_version: existing?.version, idempotency_key: crypto.randomUUID() }); } catch { setError("Commercial readiness was not saved. Refresh authoritative policy state and use valid JSON."); } };
  return <Card><CardHeader><CardTitle>Commercial policy readiness</CardTitle><CardDescription>Unknown Company values remain explicitly unconfigured. ACP does not invent discount, tax, expiration, legal, or delivery policy.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{required.map((type) => { const policy = policies.find((item) => item.policy_type === type); return <div className="rounded border border-stroke p-3" key={type}><div className="flex justify-between gap-2"><strong>{type.replaceAll("_", " ")}</strong><Badge>{policy?.status ?? "unconfigured"}</Badge></div><p className="mt-1 text-sm text-content-muted">{policy?.readiness_reason ?? "No authoritative value configured."}</p></div>; })}</div>{error && <Alert variant="danger">{error}</Alert>}{canManage && <form className="grid gap-2 md:grid-cols-3" onSubmit={(event) => void submit(event)}><Select required aria-label="Commercial policy Branch" value={form.branch_id} onChange={(event) => setForm({ ...form, branch_id: event.target.value })}><option value="">Branch</option>{branches.map((branch) => <option value={branch.id} key={branch.id}>{branch.name}</option>)}</Select><Select aria-label="Commercial policy type" value={form.policy_type} onChange={(event) => setForm({ ...form, policy_type: event.target.value })}>{required.map((type) => <option value={type} key={type}>{type.replaceAll("_", " ")}</option>)}</Select><Select aria-label="Commercial policy status" value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value as CommercialPolicy["status"], configuration: event.target.value === "unconfigured" ? "{}" : form.configuration })}><option value="unconfigured">Unconfigured</option><option value="draft">Draft</option><option value="active">Active</option><option value="inactive">Inactive</option></Select><Input aria-label="Commercial policy configuration JSON" value={form.configuration} onChange={(event) => setForm({ ...form, configuration: event.target.value })}/><Input aria-label="Commercial readiness reason" required value={form.readiness_reason} onChange={(event) => setForm({ ...form, readiness_reason: event.target.value })}/><Button type="submit" loading={pending}>Save readiness</Button></form>}</CardContent></Card>;
}
