import * as Crypto from "expo-crypto";
import { z } from "zod";
import type { ApiClient } from "./client";

const itineraryItemSchema = z.object({ appointment_id: z.string().uuid(), appointment_number: z.string(), job_id: z.string().uuid().nullable(), job_number: z.string().nullable(), job_status: z.string().nullable(), job_version: z.number().int().positive().nullable(), customer_display_name: z.string(), service_location_label: z.string(), window_start_at: z.string(), window_end_at: z.string(), assignment_status: z.string(), assignment_version: z.number().int().positive(), arrival_state: z.enum(["pending", "en_route", "arrived"]), field_execution_enabled: z.boolean() });
const itinerarySchema = z.object({ service_date: z.string(), technician_display_name: z.string(), items: z.array(itineraryItemSchema) });
export const fieldJobStateSchema = z.object({ job_id: z.string().uuid(), assignment_id: z.string().uuid(), work_summary_recorded: z.boolean(), customer_disposition: z.string().nullable(), completion_ready: z.boolean(), requirement_snapshot_version: z.number().int().positive().nullable(), missing_requirements: z.array(z.string()), commercial_authorization: z.enum(["accepted_estimate", "non_billable", "missing"]), non_billable_reason: z.string().nullable(), invoice_handoff_status: z.string().nullable(), invoice_id: z.string().uuid().nullable() });
const evidenceSchema = z.object({ kind: z.string(), state: z.string(), occurred_at: z.string(), protected_document_available: z.boolean() });
export const equipmentSchema = z.object({ job_id: z.string().uuid(), history_limit: z.number().int().positive(), attachment_upload_state: z.literal("source_required"), items: z.array(z.object({ asset_id: z.string().uuid(), display_name: z.string(), lifecycle: z.string(), manufacturer: z.string().nullable(), model: z.string().nullable(), installation_state: z.string().nullable(), warranty_state: z.string().nullable(), service_history: z.array(evidenceSchema), evidence: z.array(evidenceSchema) })) });
export const estimateSchema = z.object({ job_id: z.string().uuid(), available: z.boolean(), estimate_number: z.string().nullable(), estimate_status: z.string().nullable(), acceptance_status: z.string().nullable(), revision_number: z.number().int().positive().nullable(), revision_status: z.string().nullable(), proposal_title: z.string().nullable(), customer_message: z.string().nullable(), total_amount: z.coerce.number().nullable(), currency: z.string().nullable(), expires_at: z.string().nullable(), lines: z.array(z.object({ position: z.number().int().positive(), title: z.string(), description: z.string().nullable(), quantity: z.coerce.number(), line_total: z.coerce.number(), currency: z.string() })), customer_handoff_state: z.literal("server_authority_required") });
export const historySchema = z.object({ days: z.number().int(), limit: z.number().int(), items: z.array(z.object({ job_id: z.string().uuid(), job_number: z.string(), completed_at: z.string(), customer_display_name: z.string(), service_location_label: z.string() })) });
export const readinessSchema = z.object({ fleet: z.array(z.object({ asset_id: z.string().uuid(), display_name: z.string(), lifecycle: z.string(), readiness_state: z.string().nullable(), inspection_state: z.string().nullable(), maintenance_state: z.string().nullable(), out_of_service: z.boolean(), custody_state: z.string().nullable() })), workforce_profile_available: z.boolean(), branch_eligible: z.boolean(), availability_state: z.string().nullable(), inspection_interaction: z.enum(["policy_required", "source_required"]), notification_inbox: z.literal("source_required"), push_provider: z.literal("external_provider_required"), payment_collection: z.literal("not_authorized") });
export type ItineraryItem = z.infer<typeof itineraryItemSchema>; export type FieldJobState = z.infer<typeof fieldJobStateSchema>; export type FieldEquipment = z.infer<typeof equipmentSchema>; export type FieldEstimate = z.infer<typeof estimateSchema>; export type FieldHistory = z.infer<typeof historySchema>; export type FieldReadiness = z.infer<typeof readinessSchema>;
export type JobAction = "start" | "pause" | "resume" | "complete";
export interface FieldService {
  itinerary(serviceDate: string): Promise<z.infer<typeof itinerarySchema>>; state(jobId: string): Promise<FieldJobState>;
  arrival(appointmentId: string, state: "en_route" | "arrived", expectedVersion: number, idempotencyKey?: string): Promise<void>;
  transition(jobId: string, action: JobAction, expectedVersion: number): Promise<void>;
  workSummary(jobId: string, content: string, jobVersion: number, assignmentVersion: number, idempotencyKey: string): Promise<FieldJobState>;
  customerDisposition(jobId: string, disposition: "approved" | "unavailable" | "refused", customerName: string | null, reason: string | null, jobVersion: number, assignmentVersion: number, idempotencyKey: string): Promise<FieldJobState>;
  note(jobId: string, content: string, jobVersion: number, assignmentVersion: number): Promise<FieldJobState>;
  approval(jobId: string, disposition: "approved" | "unavailable" | "refused", jobVersion: number, assignmentVersion: number): Promise<FieldJobState>;
  refreshHandoff(jobId: string, jobVersion: number, assignmentVersion: number): Promise<FieldJobState>;
  equipment?(jobId: string): Promise<FieldEquipment>; estimate?(jobId: string): Promise<FieldEstimate>;
  history?(days?: number, limit?: number): Promise<FieldHistory>; readiness?(): Promise<FieldReadiness>;
}
const key = (operation: string) => `mobile-field:${operation}:${Crypto.randomUUID()}`;
export const fieldIdempotencyKey = key;
export function createFieldService(client: ApiClient): FieldService {
  return {
    itinerary: (date) => client.request(`/api/v1/technician/itinerary?service_date=${encodeURIComponent(date)}`, itinerarySchema),
    state: (job) => client.request(`/api/v1/technician/jobs/${encodeURIComponent(job)}`, fieldJobStateSchema),
    arrival: async (appointment, state, version, idempotencyKey) => { await client.request(`/api/v1/dispatch/appointments/${encodeURIComponent(appointment)}/assignment/arrival`, z.object({}).passthrough(), { method: "POST", body: JSON.stringify({ state, expected_version: version, idempotency_key: idempotencyKey ?? key(`arrival-${state}`) }) }); },
    transition: async (job, action, expectedVersion) => { await client.request(`/api/v1/jobs/${encodeURIComponent(job)}/${action}`, z.object({}).passthrough(), { method: "POST", body: JSON.stringify(action === "pause" ? { expected_version: expectedVersion, reason_code: "operational_hold" } : { expected_version: expectedVersion }) }); },
    workSummary: (job, content, jobVersion, assignmentVersion, idempotencyKey) => client.request(`/api/v1/technician/jobs/${encodeURIComponent(job)}/notes`, fieldJobStateSchema, { method: "POST", body: JSON.stringify({ note_type: "work_performed", content, expected_job_version: jobVersion, expected_assignment_version: assignmentVersion, idempotency_key: idempotencyKey }) }),
    customerDisposition: (job, disposition, customerName, reason, jobVersion, assignmentVersion, idempotencyKey) => client.request(`/api/v1/technician/jobs/${encodeURIComponent(job)}/customer-approval`, fieldJobStateSchema, { method: "POST", body: JSON.stringify({ disposition, customer_name: customerName, reason, expected_job_version: jobVersion, expected_assignment_version: assignmentVersion, idempotency_key: idempotencyKey }) }),
    note: (job, content, jobVersion, assignmentVersion) => client.request(`/api/v1/technician/jobs/${encodeURIComponent(job)}/notes`, fieldJobStateSchema, { method: "POST", body: JSON.stringify({ note_type: "work_performed", content, expected_job_version: jobVersion, expected_assignment_version: assignmentVersion, idempotency_key: key("work-summary") }) }),
    approval: (job, disposition, jobVersion, assignmentVersion) => client.request(`/api/v1/technician/jobs/${encodeURIComponent(job)}/customer-approval`, fieldJobStateSchema, { method: "POST", body: JSON.stringify({ disposition, customer_name: null, reason: null, expected_job_version: jobVersion, expected_assignment_version: assignmentVersion, idempotency_key: key(`approval-${disposition}`) }) }),
    refreshHandoff: (job, jobVersion, assignmentVersion) => client.request(`/api/v1/technician/jobs/${encodeURIComponent(job)}/invoice-handoff`, fieldJobStateSchema, { method: "POST", body: JSON.stringify({ expected_job_version: jobVersion, expected_assignment_version: assignmentVersion, idempotency_key: key("invoice-handoff") }) }),
    equipment: (job) => client.request(`/api/v1/technician/jobs/${encodeURIComponent(job)}/equipment`, equipmentSchema),
    estimate: (job) => client.request(`/api/v1/technician/jobs/${encodeURIComponent(job)}/estimate`, estimateSchema),
    history: (days = 30, limit = 20) => client.request(`/api/v1/technician/history?days=${days}&limit=${limit}`, historySchema),
    readiness: () => client.request("/api/v1/technician/readiness", readinessSchema),
  };
}
