import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { confirmDailyEquipment, getDailyEquipmentPrompt, getDispatchEquipmentReadiness, getEquipmentAttention, getEquipmentChecklistSetting, setEquipmentChecklistSetting, type EquipmentChecklistRequirement } from "../api/equipmentReadiness";

export const equipmentReadinessKeys = { all: ["equipment-readiness"] as const, setting: (id: string) => ["equipment-readiness", "setting", id] as const, prompt: (id: string, day: string) => ["equipment-readiness", "prompt", id, day] as const, attention: (branch?: string) => ["equipment-readiness", "attention", branch] as const, dispatch: (branch: string) => ["equipment-readiness", "dispatch", branch] as const };
export const useEquipmentChecklistSetting = (employeeId: string | null, enabled = true) => useQuery({ queryKey: equipmentReadinessKeys.setting(employeeId ?? ""), queryFn: () => getEquipmentChecklistSetting(employeeId!), enabled: enabled && Boolean(employeeId), retry: false });
export function useSetEquipmentChecklistSetting(employeeId: string | null) { const client = useQueryClient(); return useMutation({ mutationFn: (value: EquipmentChecklistRequirement) => setEquipmentChecklistSetting(employeeId!, value), onSuccess: (value) => client.setQueryData(equipmentReadinessKeys.setting(employeeId!), value) }); }
export const useDailyEquipmentPrompt = (employeeId: string | null, workDate: string, enabled = true) => useQuery({ queryKey: equipmentReadinessKeys.prompt(employeeId ?? "", workDate), queryFn: () => getDailyEquipmentPrompt(employeeId!, workDate), enabled: enabled && Boolean(employeeId), retry: false });
export function useConfirmDailyEquipment(employeeId: string | null, workDate: string) { const client = useQueryClient(); return useMutation({ mutationFn: confirmDailyEquipment, onSuccess: () => client.invalidateQueries({ queryKey: equipmentReadinessKeys.prompt(employeeId!, workDate) }) }); }
export const useEquipmentAttention = (branchId?: string, enabled = true) => useQuery({ queryKey: equipmentReadinessKeys.attention(branchId), queryFn: () => getEquipmentAttention(branchId), enabled, retry: false });
export const useDispatchEquipmentReadiness = (branchId: string, enabled = true) => useQuery({ queryKey: equipmentReadinessKeys.dispatch(branchId), queryFn: () => getDispatchEquipmentReadiness(branchId), enabled: enabled && Boolean(branchId), retry: false });
