class EmployeeOperationsPermission:
    OWN_DAY_READ = "COMPANY_EMPLOYEE_OPERATIONS_OWN_DAY_READ"
    OWN_LIA_READ = "COMPANY_EMPLOYEE_OPERATIONS_OWN_LIA_READ"

    ALL = frozenset({OWN_DAY_READ, OWN_LIA_READ})
