"""Narrow Company-scoped timekeeping permissions."""


class TimekeepingPermission:
    OWN_PUNCH = "COMPANY_TIMEKEEPING_OWN_PUNCH"
    OWN_READ = "COMPANY_TIMEKEEPING_OWN_READ"
    MANUAL_ENTRY = "COMPANY_TIMEKEEPING_MANUAL_ENTRY"
    CORRECT = "COMPANY_TIMEKEEPING_CORRECT"
    APPROVE = "COMPANY_TIMEKEEPING_APPROVE"
    ADMIN_READ = "COMPANY_TIMEKEEPING_ADMIN_READ"

    ALL = frozenset({OWN_PUNCH, OWN_READ, MANUAL_ENTRY, CORRECT, APPROVE, ADMIN_READ})
