import { apiClient } from "./client";

export type QualityState = "complete" | "partial" | "stale" | "conflicting" | "unavailable";
export interface EconomicsTotals { revenue: number; labor: number; materials: number; equipment: number; truck: number; overhead: number | null; gross_profit: number; net_profit: number | null }
export interface EconomicsJob { result_id: string; job_id: string; job_number: string; job_status: string; branch_name: string; customer_name: string; service_category: string | null; currency: string; revenue_minor: number | null; labor_minor: number | null; materials_minor: number | null; other_direct_cost_minor: number | null; contribution_minor: number | null; net_profit_minor: number | null; margin_basis_points: number | null; quality_state: QualityState; confidence_percent: number; missing_categories: string[] }
export interface EconomicsRollup { label: string; jobs: number; complete_jobs: number; revenue_minor: number; contribution_minor: number; quality_state: QualityState }
export interface EconomicsWorkspace { period: { start: string; end: string }; prior_period: { start: string; end: string }; quality_state: QualityState; currency: string | null; source_result_count: number; excluded_job_count: number; job_count: number; complete_job_count: number; unclassified_job_count: number; totals: EconomicsTotals | null; jobs: EconomicsJob[]; service_categories: EconomicsRollup[]; customers: EconomicsRollup[]; branches: EconomicsRollup[]; fully_allocated_available: boolean; explanation: string; comparison: { state: "available" | "unavailable"; reason?: string; revenue_change_minor?: number; contribution_change_minor?: number; labor_change_minor?: number; materials_change_minor?: number; explanation?: string }; readiness: { evidence: string; allocation_policy: string; attribution: string; policy_gaps: { gap_key: string; requirement: string; state: string }[] }; beacon_conditions: { kind: string; state: string }[] }
export interface EconomicsResultDetail { id: string; subject_id: string; scope: string; period_start: string; period_end: string; currency: string; components: Record<string, { state: string; amount_minor: number | null; confidence_percent: number; explanation: string; evidence: { owner: string; source_system: string; record_type: string; record_id: string; content_digest: string }[] }> | null; quality: Record<string, unknown> | null; explanation: { answer: string; findings: { kind: string; summary: string; explanation: string }[]; limitations: string[] } | null; lineage: Record<string, string | string[]> }

export async function getEconomicsWorkspace(start: string, end: string) { return (await apiClient.get<EconomicsWorkspace>("/api/v1/business-economics/workspace", { params: { start, end } })).data; }
export async function getEconomicsResult(resultId: string) { return (await apiClient.get<EconomicsResultDetail>(`/api/v1/business-economics/results/${resultId}`)).data; }
