export interface BankAccount {
  id: string; institution_name: string; account_name: string; account_type: string;
  connection_id: string | null; branch_id: string | null; ledger_account_id: string | null;
  account_subtype: string | null; ownership_scope: string;
  masked_identity: string; currency: string; status: string; source_system: string;
  source_version: string; source_digest: string; source_as_of: string;
  opening_balance: string | null; opening_balance_date: string | null;
}
export interface ReconciliationActor { display_name: string; occurred_at: string; }
export interface Reconciliation { id: string; statement_identity: string; period_start: string; period_end: string; ending_balance: string; book_balance: string; cleared_total: string; outstanding_total: string; difference: string; status: string; cleared_transaction_ids: string[]; outstanding_items: Record<string, unknown>[]; source_evidence: Record<string, unknown>; preparer_user_id: string; reviewer_user_id: string | null; prepared_at: string; submitted_at: string | null; closed_at: string | null; evidence_digest: string; version: number; prepared_by: ReconciliationActor; reviewed_by: ReconciliationActor | null; }
export interface ReconciliationPrepare { statement_identity: string; period_start: string; period_end: string; ending_balance: string; book_balance: string; cleared_total: string; outstanding_total: string; cleared_transaction_ids: string[]; outstanding_items: Record<string, unknown>[]; source_evidence: Record<string, unknown>; }
export interface BankSummary { account: BankAccount; imported_count: number; matched_count: number; unmatched_count: number; review_required_count: number; transfer_candidate_count: number; active_reconciliation_state: string; current_difference: string | null; last_reconciled_through: string | null; latest_closed_reconciliation: Reconciliation | null; connection_status: string; mapping_state: string; current_balance: string | null; available_balance: string | null; balance_as_of: string | null; }
export interface BankConnection { id: string; company_id: string; branch_id: string | null; provider: string; provider_institution_id: string; institution_name: string; consent_status: string; status: string; provider_version: string | null; source_as_of: string | null; last_successful_sync_at: string | null; last_error_code: string | null; account_count: number; }
export interface BankTransaction { id: string; bank_account_id: string; external_transaction_id: string; posted_date: string; effective_date: string | null; amount: string; currency: string; direction: string; kind: string; description: string; memo: string | null; state: string; source_as_of: string; }
export interface ImportTransaction { source_system: string; external_transaction_id: string; related_identity?: string | null; group_key?: string | null; source_version: string; source_digest: string; acquired_at: string; source_as_of: string; posted_date: string; effective_date?: string | null; amount: string; currency: string; direction: string; kind: string; description: string; memo?: string | null; state?: string; }
export interface ImportRequest { statement_identity: string; period_start: string; period_end: string; opening_balance: string | null; ending_balance: string | null; transactions: ImportTransaction[]; }
export interface ImportDisposition { source_system: string; source_identity: string; disposition: string; reason: string; }
export interface ImportPreview extends ImportRequest { bank_account_id: string; transaction_count: number; new_count: number; replay_count: number; duplicate_count: number; conflict_count: number; invalid_count: number; preview_digest: string; dispositions: ImportDisposition[]; }
export interface ImportConfirm { preview_digest: string; persisted_count: number; replay_count: number; quarantined_count: number; dispositions: ImportDisposition[]; }
export interface MatchReview { transaction: BankTransaction; match_id: string | null; match_state: string; target_type: string | null; target_identity: string | null; reason_code: string; deterministic: boolean; }
export interface Drilldown { transaction: BankTransaction; match: MatchReview; bank_account_id: string; ledger_account_id: string | null; target_reference: string | null; source_system: string; source_digest: string; }
export interface ReconciliationPreview { bank_account_id: string; statement_identity: string; period_start: string; period_end: string; beginning_balance: string; ending_balance: string; book_balance: string; cleared_total: string; outstanding_total: string; difference: string; unresolved_exceptions: number; can_close: boolean; blocker_reasons: string[]; }
export interface CashFlowSection { amount: string; journal_ids: string[]; }
export interface CashFlow { period_start: string; period_end: string; basis: string; cutoff: string; completeness: string; beginning_cash: string; operating_activities: CashFlowSection; investing_activities: CashFlowSection; financing_activities: CashFlowSection; unclassified_amount: string; unclassified_journal_ids: string[]; net_change: string; ending_cash: string; canonical_bank_cash: string | null; difference: string | null; tie_status: string; }
