export interface PriceBookCategory { id: string; company_id: string; parent_id: string | null; code: string; name: string; description: string | null; status: string; version: number }
export interface TaxClassification { id: string; company_id: string; code: string; name: string; taxable: boolean; status: string; version: number }
export interface PriceBookServiceItem { id: string; company_id: string; branch_id: string | null; category_id: string; code: string; name: string; customer_description: string; status: string; current_version_id: string | null; version: number }
export interface PriceBookComponent { id: string; component_type: "labor" | "material"; code: string | null; label: string; quantity: string; position: number }
export interface PriceBookVersion { id: string; company_id: string; service_item_id: string; branch_id: string | null; tax_classification_id: string; revision: number; currency: string; unit_price: string; effective_at: string; expires_at: string | null; status: string; rounding_mode: string; version: number; components: PriceBookComponent[] }
export interface PriceBookOptionGroup { id: string; company_id: string; code: string; name: string; minimum_selections: number; maximum_selections: number; status: string }
export interface PriceBookOption { id: string; company_id: string; option_group_id: string; service_item_id: string; label: string; position: number }
export interface PriceBookCatalog { categories: PriceBookCategory[]; tax_classifications: TaxClassification[]; service_items: PriceBookServiceItem[]; versions: PriceBookVersion[]; option_groups: PriceBookOptionGroup[]; options: PriceBookOption[] }
export interface PriceBookSnapshot { id: string; service_item_id: string; quantity: string; unit_price: string; extended_amount: string; currency: string; digest: string }
