import { act, fireEvent, render, screen, waitFor } from "@testing-library/react-native";
import { AppState } from "react-native";
import { ApiFailure } from "../src/api/types";
import { LiaScreen } from "../src/screens/LiaScreen";
import { createLiaService } from "../src/api/lia";
import type { LiaResponse, LiaService } from "../src/api/lia";

const response: LiaResponse = {
  request_id: "10000000-0000-4000-8000-000000000001", conversation_id: "20000000-0000-4000-8000-000000000001", classification: "KNOWN", authority: "ACP_AUTHORITATIVE", answer: "Your next assigned appointment is synthetic.", response_mode: "NORMAL", evidence: [{ domain: "employee-operations", label: "My authorized assigned work", authority: "EMPLOYEE.DAY.v1", observed_at: "2026-09-16T12:00:00Z", freshness: "CURRENT_QUERY", evidence_digest: "a".repeat(64), branch_ids: [], limitations: ["Only your active assignments are included."] }], limitations: [], navigation: [], completeness: "COMPLETE_FOR_EMPLOYEE_SAFE_ADAPTERS", freshness: "CURRENT_QUERY", provider: "deterministic-acp", provider_version: "v1", policy_version: "LIA.EMPLOYEE_SAFE.v1", evidence_digest: "a".repeat(64), authorization_version: 1, company_id: "30000000-0000-4000-8000-000000000001", branch_ids: [], source_systems: ["employee-operations"], missing_evidence: [], safe_next_action: "Open My Day", as_of: "2026-09-16T12:00:00Z", generated_at: "2026-09-16T12:00:00Z", temporal: null,
};
function service() { return { ask: jest.fn(async () => response) } satisfies LiaService; }

describe("employee-safe Mobile LIA", () => {
  it("uses only the employee-safe endpoint", async () => { const client = { request: jest.fn(async () => response) }; await createLiaService(client as never).ask("What is my next job?"); const calls = client.request.mock.calls as unknown[][]; expect(calls[0]?.[0]).toBe("/api/v1/lia/employee/ask"); expect(calls.some(([path]) => path === "/api/v1/lia/ask")).toBe(false); });
  it("renders server-owned clarification and translation without promoting an unconfirmed fact", async () => { const lia = service(); lia.ask.mockResolvedValueOnce({ ...response, csr_dispatch: { contract_version: "lia.csr.dispatch.copilot.v1", reasoning_id: "40000000-0000-4000-8000-000000000001", reasoning_revision: 1, reasoning_digest: "b".repeat(64), customer_branch: { state: "AMBIGUOUS", missing_fields: [], next_questions: [], limitations: [] }, speech_interpretations: [{ state: "CONFIRM_RECOMMENDED", heard_text: "water backs up", possible_meaning: "Water backs up into the bathtub when the toilet is flushed.", suggested_confirmation: "Just to make sure I understand—water comes up in the bathtub when you flush?", source_language: "en-US", interpreted_language: null, translation_state: "NOT_TRANSLATED", translation_provenance: null, as_of: "2026-09-30T15:00:00Z", confirmed: false, owning_fact_type: "service_problem", context: {} }], clarification_required: true, translation_available: false, recommendation_state: "PROVISIONAL", primary_ghost_slot: null, alternates: [], constrained_options: [], facts: [], interpretation: "clarification required", recommendation: "confirm", why: [], as_of: "2026-09-30T15:00:00Z", expires_at: "2026-09-30T15:05:00Z", action_metadata: [], limitations: ["Unconfirmed speech interpretations require confirmation."], mutation_authority: "none" } }); render(<LiaScreen service={lia} />); fireEvent.changeText(screen.getByLabelText("Ask LIA a question"), "What did the caller say?"); fireEvent.press(screen.getByLabelText("Send question to Employee-safe LIA")); expect(await screen.findByText("Low confidence — confirm this detail")).toBeOnTheScreen(); expect(screen.getByText(/Heard: water backs up/)).toBeOnTheScreen(); fireEvent.press(screen.getByLabelText("Clarify this spoken detail")); expect(screen.getByDisplayValue(/Just to make sure I understand/)).toBeOnTheScreen(); fireEvent.press(screen.getByLabelText("Translate this spoken detail")); expect(screen.getByDisplayValue(/Translate this service problem/)).toBeOnTheScreen(); });
  it("submits through the employee-safe service and preserves conversation continuity", async () => {
    const lia = service(); render(<LiaScreen service={lia} />);
    fireEvent.changeText(screen.getByLabelText("Ask LIA a question"), "What is my next job?"); fireEvent.press(screen.getByLabelText("Send question to Employee-safe LIA"));
    expect(await screen.findByText(response.answer)).toBeOnTheScreen();
    expect(lia.ask).toHaveBeenCalledWith("What is my next job?", undefined);
    fireEvent.changeText(screen.getByLabelText("Ask LIA a question"), "And the next one?"); fireEvent.press(screen.getByLabelText("Send question to Employee-safe LIA"));
    await waitFor(() => expect(lia.ask).toHaveBeenLastCalledWith("And the next one?", response.conversation_id));
  });
  it("renders compact provenance and expandable evidence", async () => { const lia = service(); render(<LiaScreen service={lia} />); fireEvent.changeText(screen.getByLabelText("Ask LIA a question"), "What is my next job?"); fireEvent.press(screen.getByLabelText("Send question to Employee-safe LIA")); await screen.findByText(/CURRENT QUERY/); fireEvent.press(screen.getByLabelText("Show LIA evidence")); expect(await screen.findByText(/Source:.*EMPLOYEE\.DAY\.v1/)).toBeOnTheScreen(); });
  it("speaks the bounded presentation in cancellable thought groups", async () => { const lia = service(); const speech = { speak: jest.fn(), stop: jest.fn() }; render(<LiaScreen service={lia} speech={speech} />); fireEvent.changeText(screen.getByLabelText("Ask LIA a question"), "What is my next job?"); fireEvent.press(screen.getByLabelText("Send question to Employee-safe LIA")); await screen.findByText(response.answer); fireEvent.press(screen.getByLabelText("Speak this LIA answer")); expect(speech.speak).toHaveBeenCalledWith("Your next assigned appointment is synthetic.", expect.objectContaining({ language: "en-US", rate: expect.any(Number), pitch: expect.any(Number), onDone: expect.any(Function) })); fireEvent.press(screen.getByLabelText("Stop LIA playback")); expect(speech.stop).toHaveBeenCalled(); fireEvent.press(screen.getByLabelText("Speak this LIA answer")); expect(speech.speak).toHaveBeenCalledTimes(2); });
  it("stops speech when the app leaves the foreground", async () => { const lia = service(); const speech = { speak: jest.fn(), stop: jest.fn() }; const listener = jest.spyOn(AppState, "addEventListener"); render(<LiaScreen service={lia} speech={speech} />); fireEvent.changeText(screen.getByLabelText("Ask LIA a question"), "What is my next job?"); fireEvent.press(screen.getByLabelText("Send question to Employee-safe LIA")); await screen.findByText(response.answer); fireEvent.press(screen.getByLabelText("Speak this LIA answer")); const callback = listener.mock.calls.at(-1)?.[1]; expect(callback).toBeDefined(); act(() => callback?.("background")); expect(speech.stop).toHaveBeenCalled(); listener.mockRestore(); });
  it("cancels playback when a new answer arrives or the screen unmounts", async () => { const lia = service(); const speech = { speak: jest.fn(), stop: jest.fn() }; const view = render(<LiaScreen service={lia} speech={speech} />); fireEvent.changeText(screen.getByLabelText("Ask LIA a question"), "What is my next job?"); fireEvent.press(screen.getByLabelText("Send question to Employee-safe LIA")); await screen.findByText(response.answer); fireEvent.press(screen.getByLabelText("Speak this LIA answer")); fireEvent.changeText(screen.getByLabelText("Ask LIA a question"), "What is my schedule?"); fireEvent.press(screen.getByLabelText("Send question to Employee-safe LIA")); await waitFor(() => expect(speech.stop).toHaveBeenCalled()); view.unmount(); expect(speech.stop.mock.calls.length).toBeGreaterThanOrEqual(2); });
  it("reports native speech failure without hiding the authorized answer", async () => { const lia = service(); const speech = { speak: jest.fn(() => { throw new Error("native unavailable"); }), stop: jest.fn() }; render(<LiaScreen service={lia} speech={speech} />); fireEvent.changeText(screen.getByLabelText("Ask LIA a question"), "What is my next job?"); fireEvent.press(screen.getByLabelText("Send question to Employee-safe LIA")); await screen.findByText(response.answer); fireEvent.press(screen.getByLabelText("Speak this LIA answer")); expect(await screen.findByText(/Spoken playback is unavailable/)).toBeOnTheScreen(); });
  it("keeps authorization, network, and malformed responses safe", async () => {
    for (const [error, expected] of [[new ApiFailure("forbidden", "denied"), /not available with your current Employee permissions/], [new ApiFailure("offline", "offline"), /offline/], [new ApiFailure("malformed_response", "bad"), /unavailable response/] ] as const) { const lia = service(); lia.ask.mockRejectedValueOnce(error); const view = render(<LiaScreen service={lia} />); fireEvent.changeText(screen.getByLabelText("Ask LIA a question"), "What is my next job?"); fireEvent.press(screen.getByLabelText("Send question to Employee-safe LIA")); expect(await screen.findByText(expected)).toBeOnTheScreen(); view.unmount(); }
  });
});
