import { act, fireEvent, render, screen, waitFor } from "@testing-library/react-native";
import { ApiFailure } from "../src/api/types";
import type { PunchAction, PunchState, Timecard, TimekeepingService } from "../src/api/timekeeping";
import { TimeScreen } from "../src/screens/TimeScreen";

jest.mock("expo-crypto", () => ({ randomUUID: jest.fn(() => "opaque-idempotency-key") }));
const states: Record<PunchState["state"], PunchState> = {
  not_clocked_in: { state: "not_clocked_in", last_action: "clock_out", occurred_at: "2026-08-27T21:00:00Z", server_observed_at: "2026-08-28T12:00:00Z", elapsed_seconds: null },
  clocked_in: { state: "clocked_in", last_action: "clock_in", occurred_at: "2026-08-28T12:00:00Z", server_observed_at: "2026-08-28T12:01:00Z", elapsed_seconds: 60 },
  on_break: { state: "on_break", last_action: "break_start", occurred_at: "2026-08-28T16:00:00Z", server_observed_at: "2026-08-28T16:01:00Z", elapsed_seconds: 14460 },
};
const emptyCard = (state = states.not_clocked_in): Timecard => ({ employee_id: "synthetic-employee", punch_state: state, pay_period: { id: "synthetic-period", period_start: "2026-08-24", period_end: "2026-08-30", processing_date: "2026-09-01", payday: "2026-09-04", timezone: "America/New_York", schedule_definition_id: "synthetic", schedule_version: 1 }, entries: [] });
function harness(initial: PunchState = states.not_clocked_in, connected = true) {
  let current = initial; let listener: ((value: boolean) => void) | undefined;
  const network = { isConnected: jest.fn(async () => connected), subscribe: jest.fn((next: (value: boolean) => void) => { listener = next; return () => undefined; }) };
  const service: TimekeepingService = { state: jest.fn(async () => current), timecard: jest.fn(async () => emptyCard(current)), punch: jest.fn(async (action: PunchAction) => { current = action === "clock_in" || action === "break_end" ? states.clocked_in : action === "break_start" ? states.on_break : states.not_clocked_in; return { punch_id: "synthetic-punch", action, occurred_at: current.occurred_at!, state: current, completed_entry: null }; }) };
  return { service, network, setConnected(value: boolean) { connected = value; listener?.(value); } };
}

describe("native employee timeclock", () => {
  it("renders Clock In while authoritatively clocked out and sends no identity or timestamp", async () => { const h = harness(); render(<TimeScreen service={h.service} network={h.network} canPunch />); expect(await screen.findByText("Clock In")).toBeEnabled(); fireEvent.press(screen.getByText("Clock In")); await waitFor(() => expect(h.service.punch).toHaveBeenCalledWith("clock_in", "opaque-idempotency-key")); expect(JSON.stringify((h.service.punch as jest.Mock).mock.calls)).not.toMatch(/employee|occurred_at|timestamp/); });
  it("uses authoritative Clock In response", async () => { const h = harness(); render(<TimeScreen service={h.service} network={h.network} canPunch />); fireEvent.press(await screen.findByText("Clock In")); expect(await screen.findByText("Clocked in")).toBeOnTheScreen(); });
  it("offers Start Break and Clock Out while clocked in", async () => { const h = harness(states.clocked_in); render(<TimeScreen service={h.service} network={h.network} canPunch />); expect(await screen.findByText("Start Break")).toBeEnabled(); expect(screen.getByText("Clock Out")).toBeEnabled(); });
  it.each([["Start Break", "break_start", "On break"], ["End Break", "break_end", "Clocked in"], ["Clock Out", "clock_out", "Clocked out"]] as const)("performs %s", async (label, action, expected) => { const initial = action === "break_end" ? states.on_break : states.clocked_in; const h = harness(initial); render(<TimeScreen service={h.service} network={h.network} canPunch />); fireEvent.press(await screen.findByText(label)); await waitFor(() => expect(h.service.punch).toHaveBeenCalledWith(action, expect.any(String))); expect(await screen.findByText(expected)).toBeOnTheScreen(); });
  it("prevents duplicate taps while a punch is pending", async () => { const h = harness(); let resolve!: () => void; (h.service.punch as jest.Mock).mockImplementation(() => new Promise((done) => { resolve = () => done({ punch_id: "p", action: "clock_in", occurred_at: "2026-08-28T12:00:00Z", state: states.clocked_in, completed_entry: null }); })); render(<TimeScreen service={h.service} network={h.network} canPunch />); const button = await screen.findByText("Clock In"); fireEvent.press(button); await waitFor(() => expect(h.service.punch).toHaveBeenCalledTimes(1)); fireEvent.press(button); expect(h.service.punch).toHaveBeenCalledTimes(1); await act(async () => resolve()); });
  it("recovers uncertain response and reuses the same logical command key", async () => { const h = harness(); (h.service.punch as jest.Mock).mockRejectedValueOnce(new ApiFailure("timeout", "lost response")); render(<TimeScreen service={h.service} network={h.network} canPunch />); fireEvent.press(await screen.findByText("Clock In")); expect(await screen.findByText(/not confirmed/)).toBeOnTheScreen(); fireEvent.press(screen.getByText("Clock In")); await waitFor(() => expect(h.service.punch).toHaveBeenCalledTimes(2)); expect((h.service.punch as jest.Mock).mock.calls[0][1]).toBe((h.service.punch as jest.Mock).mock.calls[1][1]); });
  it("prohibits offline punch and refreshes on restoration", async () => { const h = harness(states.not_clocked_in, false); render(<TimeScreen service={h.service} network={h.network} canPunch />); expect(await screen.findByText(/offline/i)).toBeOnTheScreen(); expect(h.service.punch).not.toHaveBeenCalled(); h.setConnected(true); await waitFor(() => expect(h.service.state).toHaveBeenCalled()); });
  it.each([["unauthenticated", /session has expired/i], ["forbidden", /do not have permission/i], ["not_ready", /not ready/i]] as const)("handles %s safely", async (kind, message) => { const h = harness(); (h.service.state as jest.Mock).mockRejectedValue(new ApiFailure(kind, kind)); render(<TimeScreen service={h.service} network={h.network} canPunch />); expect(await screen.findByText(message)).toBeOnTheScreen(); });
  it("refreshes authoritative state after conflict", async () => { const h = harness(states.clocked_in); (h.service.punch as jest.Mock).mockRejectedValueOnce(new ApiFailure("conflict", "changed")); render(<TimeScreen service={h.service} network={h.network} canPunch />); fireEvent.press(await screen.findByText("Start Break")); expect(await screen.findByText(/status changed/i)).toBeOnTheScreen(); expect(h.service.state).toHaveBeenCalledTimes(2); });
  it("fails safely on malformed response", async () => { const h = harness(); (h.service.state as jest.Mock).mockRejectedValue(new ApiFailure("malformed_response", "bad")); render(<TimeScreen service={h.service} network={h.network} canPunch />); expect(await screen.findByText(/Unable to load/)).toBeOnTheScreen(); });
  it("distinguishes authorized manual entry without compensation content", async () => { const h = harness(); (h.service.timecard as jest.Mock).mockResolvedValue({ ...emptyCard(), entries: [{ entry_id: "entry", revision_id: "revision", revision_number: 1, work_date: "2026-08-28", timezone: "America/New_York", provenance: "authorized_manual_entry", start_at: "2026-08-28T12:00:00Z", end_at: "2026-08-28T13:00:00Z", approved_duration_minutes: 60, state: "approved", supersedes_revision_id: null, correction_reason: null, approved_at: "2026-08-28T14:00:00Z" }] }); render(<TimeScreen service={h.service} network={h.network} canPunch />); expect(await screen.findByText("Authorized manual entry")).toBeOnTheScreen(); expect(screen.queryByText(/compensation|payroll|rate|wage/i)).not.toBeOnTheScreen(); });
  it("provides accessible action labels and permission UX", async () => { const h = harness(); const { rerender } = render(<TimeScreen service={h.service} network={h.network} canPunch />); expect(await screen.findByLabelText("Clock in using server time")).toBeOnTheScreen(); rerender(<TimeScreen service={h.service} network={h.network} canPunch={false} />); expect(await screen.findByText(/Punch actions are not available/)).toBeOnTheScreen(); });
  it("keeps the last-confirmed state stale and disables mutation during a transient 502", async () => { const h = harness(); render(<TimeScreen service={h.service} network={h.network} canPunch />); await screen.findByText("Clock In"); (h.service.state as jest.Mock).mockRejectedValueOnce(new ApiFailure("unavailable", "502")); await act(async () => screen.getByTestId("time-scroll").props.refreshControl.props.onRefresh()); expect(await screen.findByText("LAST CONFIRMED — STALE")).toBeOnTheScreen(); expect(screen.getByText("Clock In")).toBeDisabled(); expect(h.service.punch).not.toHaveBeenCalled(); await act(async () => screen.getByTestId("time-scroll").props.refreshControl.props.onRefresh()); await waitFor(() => expect(screen.getByText("Clock In")).toBeEnabled()); });
});
