class AdministrationPermission:
    MEMBERSHIP_READ = "COMPANY_MEMBERSHIP_READ"
    MEMBERSHIP_MANAGE = "COMPANY_MEMBERSHIP_MANAGE"
    BRANCH_ACCESS_MANAGE = "COMPANY_BRANCH_ACCESS_MANAGE"
    ROLE_READ = "COMPANY_ROLE_READ"
    ROLE_MANAGE = "COMPANY_ROLE_MANAGE"
    PERMISSION_MANAGE = "COMPANY_PERMISSION_MANAGE"
    COMPANY_ADMINISTER = "COMPANY_ADMINISTER"

    ALL = frozenset(
        {
            MEMBERSHIP_READ,
            MEMBERSHIP_MANAGE,
            BRANCH_ACCESS_MANAGE,
            ROLE_READ,
            ROLE_MANAGE,
            PERMISSION_MANAGE,
            COMPANY_ADMINISTER,
        }
    )


class CustomerPermission:
    READ = "COMPANY_CUSTOMER_READ"
    MANAGE = "COMPANY_CUSTOMER_MANAGE"

    ALL = frozenset({READ, MANAGE})


class LaunchPlatformPermission:
    AUDIT_READ = "COMPANY_AUDIT_READ"

    ALL = frozenset({AUDIT_READ})


class AnalyticsPermission:
    READ = "COMPANY_ANALYTICS_READ"

    ALL = frozenset({READ})


class BeaconPermission:
    REVIEW = "COMPANY_BEACON_REVIEW"

    ALL = frozenset({REVIEW})


class SchedulingPermission:
    READ = "COMPANY_SCHEDULING_READ"
    MANAGE = "COMPANY_SCHEDULING_MANAGE"

    ALL = frozenset({READ, MANAGE})


class JobPermission:
    READ = "COMPANY_JOB_READ"
    MANAGE = "COMPANY_JOB_MANAGE"
    EXECUTE = "COMPANY_JOB_EXECUTE"

    ALL = frozenset({READ, MANAGE, EXECUTE})


class DispatchPermission:
    READ = "COMPANY_DISPATCH_READ"
    MANAGE = "COMPANY_DISPATCH_MANAGE"

    ALL = frozenset({READ, MANAGE})


class InventoryPermission:
    READ = "COMPANY_INVENTORY_READ"
    MANAGE = "COMPANY_INVENTORY_MANAGE"
    MOVE = "COMPANY_INVENTORY_MOVE"
    RESERVE = "COMPANY_INVENTORY_RESERVE"

    ALL = frozenset({READ, MANAGE, MOVE, RESERVE})


class AccountingPermission:
    READ = "COMPANY_ACCOUNTING_READ"
    JOURNAL_PREPARE = "COMPANY_ACCOUNTING_JOURNAL_PREPARE"
    JOURNAL_POST = "COMPANY_ACCOUNTING_JOURNAL_POST"
    PERIOD_MANAGE = "COMPANY_ACCOUNTING_PERIOD_MANAGE"
    JOURNAL_REVERSE = "COMPANY_ACCOUNTING_JOURNAL_REVERSE"
    RECONCILE = "COMPANY_ACCOUNTING_RECONCILE"
    FINANCE_APPROVE = "COMPANY_ACCOUNTING_FINANCE_APPROVE"
    OPENING_STATE_APPROVE = "COMPANY_ACCOUNTING_OPENING_STATE_APPROVE"
    REPORT_READ = "COMPANY_ACCOUNTING_REPORT_READ"

    ALL = frozenset(
        {
            READ,
            JOURNAL_PREPARE,
            JOURNAL_POST,
            PERIOD_MANAGE,
            JOURNAL_REVERSE,
            RECONCILE,
            FINANCE_APPROVE,
            OPENING_STATE_APPROVE,
            REPORT_READ,
        }
    )


class PriceBookPermission:
    READ = "COMPANY_PRICE_BOOK_READ"
    MANAGE = "COMPANY_PRICE_BOOK_MANAGE"
    ACTIVATE = "COMPANY_PRICE_BOOK_ACTIVATE"

    ALL = frozenset({READ, MANAGE, ACTIVATE})


class CommunicationsPermission:
    READ = "COMPANY_COMMUNICATIONS_READ"
    MANAGE = "COMPANY_COMMUNICATIONS_MANAGE"

    ALL = frozenset({READ, MANAGE})


class EstimatePermission:
    READ = "COMPANY_ESTIMATE_READ"
    MANAGE = "COMPANY_ESTIMATE_MANAGE"

    ALL = frozenset({READ, MANAGE})


class InvoicePermission:
    READ = "COMPANY_INVOICE_READ"
    MANAGE = "COMPANY_INVOICE_MANAGE"
    ISSUE = "COMPANY_INVOICE_ISSUE"
    ADJUST = "COMPANY_INVOICE_ADJUST"
    APPLY_PAYMENT = "COMPANY_INVOICE_APPLY_PAYMENT"

    ALL = frozenset({READ, MANAGE, ISSUE, ADJUST, APPLY_PAYMENT})


class PaymentPermission:
    READ = "COMPANY_PAYMENT_READ"
    COLLECT = "COMPANY_PAYMENT_COLLECT"
    APPLY = "COMPANY_PAYMENT_APPLY"
    REFUND = "COMPANY_PAYMENT_REFUND"
    DEPOSIT_MANAGE = "COMPANY_PAYMENT_DEPOSIT_MANAGE"
    RECONCILE = "COMPANY_PAYMENT_RECONCILE"
    FINANCE_APPROVE = "COMPANY_PAYMENT_FINANCE_APPROVE"

    ALL = frozenset({READ, COLLECT, APPLY, REFUND, DEPOSIT_MANAGE, RECONCILE, FINANCE_APPROVE})


class EngineeringCommandPermission:
    READ = "COMPANY_ENGINEERING_COMMAND_READ"
    MANAGE = "COMPANY_ENGINEERING_COMMAND_MANAGE"
    APPROVE = "COMPANY_ENGINEERING_COMMAND_APPROVE"

    ALL = frozenset({READ, MANAGE, APPROVE})


class EngineeringExecutionPermission:
    REQUEST = "COMPANY_ENGINEERING_EXECUTION_REQUEST"

    ALL = frozenset({REQUEST})


class EngineeringCapacityPermission:
    READ = "COMPANY_ENGINEERING_CAPACITY_READ"
    MANAGE = "COMPANY_ENGINEERING_CAPACITY_MANAGE"

    ALL = frozenset({READ, MANAGE})


class EngineeringRepositoryOperationPermission:
    READ = "COMPANY_ENGINEERING_REPOSITORY_OPERATION_READ"
    EXECUTE = "COMPANY_ENGINEERING_REPOSITORY_OPERATION_EXECUTE"

    ALL = frozenset({READ, EXECUTE})


class WorkerControlPermission:
    MANAGE = "COMPANY_ENGINEERING_WORKER_MANAGE"

    ALL = frozenset({MANAGE})


class WorkerIdentityPermission:
    MANAGE = "COMPANY_WORKER_IDENTITY_MANAGE"

    ALL = frozenset({MANAGE})
