class AdministrationPermission:
    MEMBERSHIP_READ = "COMPANY_MEMBERSHIP_READ"
    MEMBERSHIP_MANAGE = "COMPANY_MEMBERSHIP_MANAGE"
    BRANCH_ACCESS_MANAGE = "COMPANY_BRANCH_ACCESS_MANAGE"
    ROLE_READ = "COMPANY_ROLE_READ"
    ROLE_MANAGE = "COMPANY_ROLE_MANAGE"
    PERMISSION_MANAGE = "COMPANY_PERMISSION_MANAGE"
    COMPANY_ADMINISTER = "COMPANY_ADMINISTER"

    ALL = frozenset(
        {
            MEMBERSHIP_READ,
            MEMBERSHIP_MANAGE,
            BRANCH_ACCESS_MANAGE,
            ROLE_READ,
            ROLE_MANAGE,
            PERMISSION_MANAGE,
            COMPANY_ADMINISTER,
        }
    )


class CustomerPermission:
    READ = "COMPANY_CUSTOMER_READ"
    MANAGE = "COMPANY_CUSTOMER_MANAGE"

    ALL = frozenset({READ, MANAGE})


class AnalyticsPermission:
    READ = "COMPANY_ANALYTICS_READ"

    ALL = frozenset({READ})
