class AdministrationPermission:
    MEMBERSHIP_READ = "COMPANY_MEMBERSHIP_READ"
    MEMBERSHIP_MANAGE = "COMPANY_MEMBERSHIP_MANAGE"
    BRANCH_ACCESS_MANAGE = "COMPANY_BRANCH_ACCESS_MANAGE"
    ROLE_READ = "COMPANY_ROLE_READ"
    ROLE_MANAGE = "COMPANY_ROLE_MANAGE"
    PERMISSION_MANAGE = "COMPANY_PERMISSION_MANAGE"
    COMPANY_ADMINISTER = "COMPANY_ADMINISTER"
    IDENTITY_ONBOARDING_MANAGE = "COMPANY_IDENTITY_ONBOARDING_MANAGE"

    ALL = frozenset(
        {
            MEMBERSHIP_READ,
            MEMBERSHIP_MANAGE,
            BRANCH_ACCESS_MANAGE,
            ROLE_READ,
            ROLE_MANAGE,
            PERMISSION_MANAGE,
            COMPANY_ADMINISTER,
            IDENTITY_ONBOARDING_MANAGE,
        }
    )


class CustomerPermission:
    READ = "COMPANY_CUSTOMER_READ"
    MANAGE = "COMPANY_CUSTOMER_MANAGE"

    ALL = frozenset({READ, MANAGE})


class ServiceAgreementPermission:
    READ = "COMPANY_SERVICE_AGREEMENT_READ"
    MANAGE = "COMPANY_SERVICE_AGREEMENT_MANAGE"
    PLAN_MANAGE = "COMPANY_SERVICE_AGREEMENT_PLAN_MANAGE"
    REPORT = "COMPANY_SERVICE_AGREEMENT_REPORT"
    ALL = frozenset({READ, MANAGE, PLAN_MANAGE, REPORT})


class LaunchPlatformPermission:
    AUDIT_READ = "COMPANY_AUDIT_READ"

    ALL = frozenset({AUDIT_READ})


class AnalyticsPermission:
    READ = "COMPANY_ANALYTICS_READ"

    ALL = frozenset({READ})


class LuminaryPermission:
    READ = "COMPANY_LUMINARY_READ"
    ANALYZE = "COMPANY_LUMINARY_ANALYZE"

    ALL = frozenset({READ, ANALYZE})


class BeaconPermission:
    REVIEW = "COMPANY_BEACON_REVIEW"
    OWN = "COMPANY_BEACON_OWN"
    ASSIGN = "COMPANY_BEACON_ASSIGN"

    ALL = frozenset({REVIEW, OWN, ASSIGN})


class MigrationPermission:
    EXECUTE_REHEARSAL = "COMPANY_MIGRATION_REHEARSAL_EXECUTE"

    ALL = frozenset({EXECUTE_REHEARSAL})


class SchedulingPermission:
    READ = "COMPANY_SCHEDULING_READ"
    MANAGE = "COMPANY_SCHEDULING_MANAGE"

    ALL = frozenset({READ, MANAGE})


class JobPermission:
    READ = "COMPANY_JOB_READ"
    MANAGE = "COMPANY_JOB_MANAGE"
    EXECUTE = "COMPANY_JOB_EXECUTE"

    ALL = frozenset({READ, MANAGE, EXECUTE})


class DispatchPermission:
    READ = "COMPANY_DISPATCH_READ"
    MANAGE = "COMPANY_DISPATCH_MANAGE"

    ALL = frozenset({READ, MANAGE})


class WorkforcePermission:
    READ = "COMPANY_WORKFORCE_READ"
    MANAGE = "COMPANY_WORKFORCE_MANAGE"
    CAPABILITY_MANAGE = "COMPANY_WORKFORCE_CAPABILITY_MANAGE"
    CERTIFICATION_MANAGE = "COMPANY_WORKFORCE_CERTIFICATION_MANAGE"
    AVAILABILITY_MANAGE = "COMPANY_WORKFORCE_AVAILABILITY_MANAGE"
    PERFORMANCE_READ = "COMPANY_WORKFORCE_PERFORMANCE_READ"

    ALL = frozenset(
        {
            READ,
            MANAGE,
            CAPABILITY_MANAGE,
            CERTIFICATION_MANAGE,
            AVAILABILITY_MANAGE,
            PERFORMANCE_READ,
        }
    )


class InventoryPermission:
    READ = "COMPANY_INVENTORY_READ"
    MANAGE = "COMPANY_INVENTORY_MANAGE"
    MOVE = "COMPANY_INVENTORY_MOVE"
    RESERVE = "COMPANY_INVENTORY_RESERVE"
    ADJUST = "COMPANY_INVENTORY_ADJUST"
    COUNT = "COMPANY_INVENTORY_COUNT"

    ALL = frozenset({READ, MANAGE, MOVE, RESERVE, ADJUST, COUNT})


class PurchasingPermission:
    READ = "COMPANY_PURCHASING_READ"
    MANAGE = "COMPANY_PURCHASING_MANAGE"
    APPROVE = "COMPANY_PURCHASING_APPROVE"
    ISSUE = "COMPANY_PURCHASING_ISSUE"
    RECEIVE = "COMPANY_PURCHASING_RECEIVE"
    RESOLVE_DISCREPANCY = "COMPANY_PURCHASING_RESOLVE_DISCREPANCY"
    RETURN_CREATE = "COMPANY_PURCHASING_RETURN_CREATE"
    RETURN_AUTHORIZE = "COMPANY_PURCHASING_RETURN_AUTHORIZE"
    RETURN_MOVE = "COMPANY_PURCHASING_RETURN_MOVE"
    RETURN_CLOSE = "COMPANY_PURCHASING_RETURN_CLOSE"
    CHANGE_REQUEST = "COMPANY_PURCHASING_CHANGE_REQUEST"
    CHANGE_APPROVE = "COMPANY_PURCHASING_CHANGE_APPROVE"
    CLOSE = "COMPANY_PURCHASING_CLOSE"
    CANCEL = "COMPANY_PURCHASING_CANCEL"

    ALL = frozenset(
        {
            READ,
            MANAGE,
            APPROVE,
            ISSUE,
            RECEIVE,
            RESOLVE_DISCREPANCY,
            RETURN_CREATE,
            RETURN_AUTHORIZE,
            RETURN_MOVE,
            RETURN_CLOSE,
            CHANGE_REQUEST,
            CHANGE_APPROVE,
            CLOSE,
            CANCEL,
        }
    )


class AccountingPermission:
    READ = "COMPANY_ACCOUNTING_READ"
    JOURNAL_PREPARE = "COMPANY_ACCOUNTING_JOURNAL_PREPARE"
    JOURNAL_POST = "COMPANY_ACCOUNTING_JOURNAL_POST"
    PERIOD_MANAGE = "COMPANY_ACCOUNTING_PERIOD_MANAGE"
    JOURNAL_REVERSE = "COMPANY_ACCOUNTING_JOURNAL_REVERSE"
    RECONCILE = "COMPANY_ACCOUNTING_RECONCILE"
    FINANCE_APPROVE = "COMPANY_ACCOUNTING_FINANCE_APPROVE"
    OPENING_STATE_APPROVE = "COMPANY_ACCOUNTING_OPENING_STATE_APPROVE"
    REPORT_READ = "COMPANY_ACCOUNTING_REPORT_READ"

    ALL = frozenset(
        {
            READ,
            JOURNAL_PREPARE,
            JOURNAL_POST,
            PERIOD_MANAGE,
            JOURNAL_REVERSE,
            RECONCILE,
            FINANCE_APPROVE,
            OPENING_STATE_APPROVE,
            REPORT_READ,
        }
    )


class EconomicsPolicyPermission:
    READ = "COMPANY_ECONOMICS_POLICY_READ"
    DRAFT = "COMPANY_ECONOMICS_POLICY_DRAFT"
    APPROVE = "COMPANY_ECONOMICS_POLICY_APPROVE"
    RETIRE = "COMPANY_ECONOMICS_POLICY_RETIRE"
    MEASUREMENT_READ = "COMPANY_ECONOMICS_MEASUREMENT_READ"
    MEASUREMENT_EXECUTE = "COMPANY_ECONOMICS_MEASUREMENT_EXECUTE"

    ALL = frozenset(
        {READ, DRAFT, APPROVE, RETIRE, MEASUREMENT_READ, MEASUREMENT_EXECUTE}
    )


class PriceBookPermission:
    READ = "COMPANY_PRICE_BOOK_READ"
    MANAGE = "COMPANY_PRICE_BOOK_MANAGE"
    ACTIVATE = "COMPANY_PRICE_BOOK_ACTIVATE"

    ALL = frozenset({READ, MANAGE, ACTIVATE})


class CommunicationsPermission:
    READ = "COMPANY_COMMUNICATIONS_READ"
    MANAGE = "COMPANY_COMMUNICATIONS_MANAGE"

    ALL = frozenset({READ, MANAGE})


class EstimatePermission:
    READ = "COMPANY_ESTIMATE_READ"
    MANAGE = "COMPANY_ESTIMATE_MANAGE"

    ALL = frozenset({READ, MANAGE})


class InvoicePermission:
    READ = "COMPANY_INVOICE_READ"
    MANAGE = "COMPANY_INVOICE_MANAGE"
    ISSUE = "COMPANY_INVOICE_ISSUE"
    ADJUST = "COMPANY_INVOICE_ADJUST"
    APPLY_PAYMENT = "COMPANY_INVOICE_APPLY_PAYMENT"

    ALL = frozenset({READ, MANAGE, ISSUE, ADJUST, APPLY_PAYMENT})


class PaymentPermission:
    READ = "COMPANY_PAYMENT_READ"
    COLLECT = "COMPANY_PAYMENT_COLLECT"
    APPLY = "COMPANY_PAYMENT_APPLY"
    REFUND = "COMPANY_PAYMENT_REFUND"
    DEPOSIT_MANAGE = "COMPANY_PAYMENT_DEPOSIT_MANAGE"
    RECONCILE = "COMPANY_PAYMENT_RECONCILE"
    FINANCE_APPROVE = "COMPANY_PAYMENT_FINANCE_APPROVE"

    ALL = frozenset(
        {READ, COLLECT, APPLY, REFUND, DEPOSIT_MANAGE, RECONCILE, FINANCE_APPROVE}
    )


class AccountsPayablePermission:
    READ = "COMPANY_ACCOUNTS_PAYABLE_READ"
    VENDOR_MANAGE = "COMPANY_ACCOUNTS_PAYABLE_VENDOR_MANAGE"
    BILL_PREPARE = "COMPANY_ACCOUNTS_PAYABLE_BILL_PREPARE"
    BILL_APPROVE = "COMPANY_ACCOUNTS_PAYABLE_BILL_APPROVE"
    CREDIT_MANAGE = "COMPANY_ACCOUNTS_PAYABLE_CREDIT_MANAGE"
    DISBURSEMENT_RECORD = "COMPANY_ACCOUNTS_PAYABLE_DISBURSEMENT_RECORD"
    RECONCILE = "COMPANY_ACCOUNTS_PAYABLE_RECONCILE"
    REPORT_READ = "COMPANY_ACCOUNTS_PAYABLE_REPORT_READ"
    MATCH_REVIEW = "COMPANY_ACCOUNTS_PAYABLE_MATCH_REVIEW"

    ALL = frozenset(
        {
            READ,
            VENDOR_MANAGE,
            BILL_PREPARE,
            BILL_APPROVE,
            CREDIT_MANAGE,
            DISBURSEMENT_RECORD,
            RECONCILE,
            REPORT_READ,
            MATCH_REVIEW,
        }
    )


class EngineeringCommandPermission:
    READ = "COMPANY_ENGINEERING_COMMAND_READ"
    MANAGE = "COMPANY_ENGINEERING_COMMAND_MANAGE"
    APPROVE = "COMPANY_ENGINEERING_COMMAND_APPROVE"

    ALL = frozenset({READ, MANAGE, APPROVE})


class EngineeringExecutionPermission:
    REQUEST = "COMPANY_ENGINEERING_EXECUTION_REQUEST"

    ALL = frozenset({REQUEST})


class EngineeringCapacityPermission:
    READ = "COMPANY_ENGINEERING_CAPACITY_READ"
    MANAGE = "COMPANY_ENGINEERING_CAPACITY_MANAGE"

    ALL = frozenset({READ, MANAGE})


class EngineeringRepositoryOperationPermission:
    READ = "COMPANY_ENGINEERING_REPOSITORY_OPERATION_READ"
    EXECUTE = "COMPANY_ENGINEERING_REPOSITORY_OPERATION_EXECUTE"

    ALL = frozenset({READ, EXECUTE})


class WorkerControlPermission:
    MANAGE = "COMPANY_ENGINEERING_WORKER_MANAGE"
    RECOVERY_ACKNOWLEDGE = "COMPANY_ENGINEERING_WORKER_RECOVERY_ACKNOWLEDGE"

    ALL = frozenset({MANAGE, RECOVERY_ACKNOWLEDGE})


class WorkerIdentityPermission:
    MANAGE = "COMPANY_WORKER_IDENTITY_MANAGE"

    ALL = frozenset({MANAGE})
