import { StyleSheet, Text } from "react-native";
import { PrimaryButton } from "../components/PrimaryButton";
import { Screen } from "../components/Screen";
import { colors } from "../design/tokens";
import type { AppEnvironment } from "../config/environment";
import { safeBuildIdentity } from "../diagnostics/buildIdentity";
import { fieldReadinessSummary } from "../field/productReadiness";
export function AccountScreen({ identity, environment, onLogout }: { identity: { displayName: string; login: string } | null; environment: AppEnvironment; onLogout(): Promise<void> }) { const build = safeBuildIdentity(environment); const health = fieldReadinessSummary(); return <Screen><Text accessibilityRole="header" style={styles.title}>Account</Text>{identity && <><Text style={styles.name}>{identity.displayName}</Text><Text style={styles.body}>{identity.login}</Text></>}<Text style={styles.body}>Your ACP session, Company, Branch, and employee permissions are verified by ACP Enterprise.</Text><Text accessibilityLabel={`ACP Employee ${build.version}, build ${build.build}, ${build.environment} environment`} style={styles.build}>ACP Employee {build.version} ({build.build}) · {build.environment.toUpperCase()}</Text><Text style={styles.compatibility}>Contract {build.compatibilityVersion} · {health.ready} mobile capabilities ready · {health.gated} awaiting source or external authority</Text><Text style={styles.body}>If access changed, close and reopen ACP Employee or reconnect to refresh authority.</Text><PrimaryButton label="Sign Out" accessibilityLabel="Sign out and clear this device session" onPress={() => void onLogout()} /></Screen>; }
const styles = StyleSheet.create({ title: { fontSize: 30, fontWeight: "800", color: colors.text }, name: { fontSize: 21, fontWeight: "700", color: colors.text }, body: { fontSize: 17, lineHeight: 24, color: colors.text }, build: { fontSize: 15, fontWeight: "700", color: colors.brandDark }, compatibility: { fontSize: 14, color: colors.muted } });
