import { useEffect, useState } from "react";
import { FlatList, RefreshControl, StyleSheet, Text, View } from "react-native";
import type { JobWorkedInterval, PunchAction, PunchState, TimeEntry, TimekeepingService } from "../api/timekeeping";
import { PrimaryButton } from "../components/PrimaryButton";
import { colors, spacing } from "../design/tokens";
import type { NetworkMonitor } from "../network/networkMonitor";
import { useTimeclock } from "../timeclock/useTimeclock";

function labelForState(state: PunchState["state"]) { return state === "not_clocked_in" ? "Clocked out" : state === "clocked_in" ? "Clocked in" : "On break"; }
function formatServerTime(value: string | null, timezone?: string) { if (!value) return "Not available"; return new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short", timeZone: timezone }).format(new Date(value)); }
function duration(entry: TimeEntry) { if (entry.approved_duration_minutes !== null) return `${Math.floor(entry.approved_duration_minutes / 60)}h ${entry.approved_duration_minutes % 60}m`; if (entry.start_at && entry.end_at) return `${Math.round((Date.parse(entry.end_at) - Date.parse(entry.start_at)) / 60000)} minutes`; return "In progress"; }
function entryMinutes(entry: TimeEntry) { if (entry.approved_duration_minutes !== null) return entry.approved_duration_minutes; if (entry.start_at && entry.end_at) return Math.max(0, Math.round((Date.parse(entry.end_at) - Date.parse(entry.start_at)) / 60000)); return 0; }
function durationLabel(seconds: number) { const hours = Math.floor(seconds / 3600); const minutes = Math.floor((seconds % 3600) / 60); const remainder = seconds % 60; return hours ? `${hours}h ${minutes}m` : `${minutes}m ${remainder}s`; }
function ActiveElapsed({ state }: { state: PunchState }) { const [now, setNow] = useState(() => Date.parse(state.server_observed_at)); useEffect(() => { if (state.state !== "clocked_in") return; const timer = setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(timer); }, [state.state]); if (state.elapsed_seconds === null || state.state === "not_clocked_in") return null; const observed = Date.parse(state.server_observed_at); const extra = state.state === "clocked_in" && Number.isFinite(observed) ? Math.max(0, Math.floor((now - observed) / 1000)) : 0; return <Text accessibilityLabel={`Elapsed Workday time ${durationLabel(state.elapsed_seconds + extra)}`}>Elapsed: {durationLabel(state.elapsed_seconds + extra)}</Text>; }
function Entry({ entry }: { entry: TimeEntry }) { const manual = entry.provenance === "authorized_manual_entry"; return <View accessible accessibilityLabel={`${manual ? "Authorized manual entry" : "Employee punch"}, ${entry.work_date}, ${entry.state}`} style={styles.entry}><Text style={styles.entryTitle}>{entry.work_date}</Text><Text>{manual ? "Authorized manual entry" : "Employee punch"}</Text><Text>{formatServerTime(entry.start_at, entry.timezone)} – {formatServerTime(entry.end_at, entry.timezone)}</Text><Text>{duration(entry)} · {entry.state}</Text>{entry.supersedes_revision_id && <Text>Corrected entry</Text>}</View>; }
function JobInterval({ interval }: { interval: JobWorkedInterval }) { const minutes = Math.floor(interval.duration_seconds / 60); const seconds = interval.duration_seconds % 60; return <View accessible accessibilityLabel={`Job work interval, ${interval.correction_state}, ${interval.validity}`} style={styles.jobEntry}><Text style={styles.entryTitle}>Job work evidence</Text><Text>{formatServerTime(interval.start_at)} – {formatServerTime(interval.stop_at)}</Text><Text>{minutes}m {seconds}s · {interval.correction_state}</Text>{interval.validity !== "valid" && <Text accessibilityRole="alert">Office review required</Text>}<Text style={styles.independence}>This interval identifies Job work; My Time remains independently authoritative.</Text></View>; }
function Actions({ state, disabled, onPunch }: { state: PunchState["state"]; disabled: boolean; onPunch(action: PunchAction): void }) { if (state === "not_clocked_in") return <PrimaryButton label="Clock In" accessibilityLabel="Clock in using server time" disabled={disabled} onPress={() => onPunch("clock_in")} />; if (state === "on_break") return <PrimaryButton label="End Break" accessibilityLabel="End break using server time" disabled={disabled} onPress={() => onPunch("break_end")} />; return <View style={styles.actions}><PrimaryButton label="Start Break" accessibilityLabel="Start break using server time" disabled={disabled} onPress={() => onPunch("break_start")} /><PrimaryButton label="Clock Out" accessibilityLabel="Clock out using server time" disabled={disabled} onPress={() => onPunch("clock_out")} /></View>; }

export function TimeScreen({ service, network, canPunch }: { service: TimekeepingService; network: NetworkMonitor; canPunch: boolean }) {
  const clock = useTimeclock(service, network); const stale = clock.status === "offline" || clock.status === "error";
  const periodMinutes = clock.timecard?.entries.reduce((total, entry) => total + entryMinutes(entry), 0) ?? 0;
  const jobSeconds = clock.timecard?.job_intervals.filter((interval) => interval.validity === "valid" && interval.correction_state !== "superseded").reduce((total, interval) => total + interval.duration_seconds, 0) ?? 0;
  return <FlatList testID="time-scroll" style={styles.safe} contentContainerStyle={styles.body} data={clock.timecard?.entries ?? []} initialNumToRender={20} maxToRenderPerBatch={20} windowSize={7} keyExtractor={(entry) => entry.revision_id} renderItem={({ item }) => <Entry entry={item} />} refreshControl={<RefreshControl refreshing={clock.status === "loading" || clock.status === "recovering"} onRefresh={() => void clock.refresh()} accessibilityLabel="Refresh authoritative time status" />} ListHeaderComponent={<>
    <Text accessibilityRole="header" style={styles.title}>My Time</Text>
    <Text style={styles.independence}>Clocking in or out changes My Time only. It does not start or complete a Job.</Text>
    {clock.message && <Text accessibilityRole="alert" style={styles.message}>{clock.message}</Text>}
    {!clock.punchState && clock.status === "loading" && <Text accessibilityLabel="Loading authoritative time status">Loading time status…</Text>}
    {clock.punchState && <View accessible accessibilityLabel={`Current authoritative state: ${labelForState(clock.punchState.state)}${stale ? ", stale" : ""}`} style={styles.status}><Text style={styles.kicker}>{stale ? "LAST CONFIRMED — STALE" : "CURRENT STATUS"}</Text><Text style={styles.state}>{labelForState(clock.punchState.state)}</Text><ActiveElapsed state={clock.punchState} /><Text>Last transition: {formatServerTime(clock.punchState.occurred_at)}</Text><Text>Server checked: {formatServerTime(clock.punchState.server_observed_at)}</Text><Text style={styles.independence}>Elapsed time is a live display from the last server-confirmed state; ACP server evidence remains authoritative.</Text></View>}
    {clock.punchState && canPunch && <Actions state={clock.punchState.state} disabled={clock.busy || stale || clock.status !== "ready"} onPunch={(action) => void clock.punch(action)} />}
    {clock.punchState && !canPunch && <Text accessibilityRole="alert">Punch actions are not available for your account.</Text>}
    <Text accessibilityRole="header" style={styles.sectionTitle}>Current period</Text>
    {clock.timecard?.pay_period && <><Text>{clock.timecard.pay_period.period_start} through {clock.timecard.pay_period.period_end} · {clock.timecard.pay_period.timezone}</Text><Text style={styles.total}>Recorded period total: {Math.floor(periodMinutes / 60)}h {periodMinutes % 60}m</Text></>}
    {clock.timecard?.entries.length === 0 && <Text>No time entries are available for this period.</Text>}
  </>} ListFooterComponent={clock.timecard?.job_intervals.length ? <View style={styles.jobEvidence}><Text accessibilityRole="header" style={styles.sectionTitle}>Job work intervals</Text><Text style={styles.total}>Confirmed Jobsite Hours: {durationLabel(jobSeconds)}</Text>{clock.timecard.job_intervals.map((interval) => <JobInterval key={interval.revision_id} interval={interval} />)}</View> : null} />;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.canvas }, body: { padding: spacing.lg, gap: spacing.md }, title: { fontSize: 30, fontWeight: "800", color: colors.text }, independence: { color: colors.muted, fontSize: 15, lineHeight: 22 }, sectionTitle: { fontSize: 22, fontWeight: "700", color: colors.text, marginTop: spacing.md }, status: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: 14, padding: spacing.lg, gap: spacing.sm }, kicker: { fontSize: 13, fontWeight: "700", color: colors.muted }, state: { fontSize: 28, fontWeight: "800", color: colors.text }, total: { color: colors.brandDark, fontSize: 17, fontWeight: "700" }, message: { fontSize: 16, color: colors.text }, actions: { gap: spacing.md }, entry: { backgroundColor: colors.surface, borderRadius: 12, padding: spacing.md, gap: spacing.xs, borderLeftWidth: 5, borderLeftColor: colors.brand }, jobEntry: { backgroundColor: colors.surface, borderRadius: 12, padding: spacing.md, gap: spacing.xs, borderLeftWidth: 5, borderLeftColor: colors.brandDark }, jobEvidence: { gap: spacing.md }, entryTitle: { fontSize: 18, fontWeight: "700", color: colors.text } });
