export type ReadinessClassification =
  | "ENGINEERING_READY"
  | "READY_FOR_DEVICE_ACCEPTANCE"
  | "SOURCE_REQUIRED"
  | "POLICY_REQUIRED"
  | "PROVIDER_REQUIRED"
  | "TOOLCHAIN_REQUIRED"
  | "EXTERNAL_GATE"
  | "DEPENDENCY_BLOCKED";

export type OfflineMutationPolicy =
  | "ONLINE_REQUIRED"
  | "SAFE_IDEMPOTENT_RETRY_AFTER_RECONCILIATION"
  | "UNSUPPORTED_OFFLINE";

export const FIELD_PRODUCT_READINESS = {
  SIGN_IN: "ENGINEERING_READY",
  MY_DAY: "ENGINEERING_READY",
  ASSIGNED_JOBS: "ENGINEERING_READY",
  JOB_DETAIL: "ENGINEERING_READY",
  CUSTOMER_LOCATION: "ENGINEERING_READY",
  ON_MY_WAY: "READY_FOR_DEVICE_ACCEPTANCE",
  ARRIVAL: "READY_FOR_DEVICE_ACCEPTANCE",
  START_WORK: "READY_FOR_DEVICE_ACCEPTANCE",
  PAUSE_RESUME: "READY_FOR_DEVICE_ACCEPTANCE",
  FIELD_SUMMARY: "READY_FOR_DEVICE_ACCEPTANCE",
  FIELD_PHOTOS: "SOURCE_REQUIRED",
  EQUIPMENT: "SOURCE_REQUIRED",
  SERVICE_HISTORY: "SOURCE_REQUIRED",
  WARRANTY_READINESS: "SOURCE_REQUIRED",
  FLEET_CONTEXT: "SOURCE_REQUIRED",
  INSPECTIONS: "POLICY_REQUIRED",
  ESTIMATE_CREATION: "SOURCE_REQUIRED",
  PRICE_BOOK: "SOURCE_REQUIRED",
  ESTIMATE_PRESENTATION: "SOURCE_REQUIRED",
  ESTIMATE_DELIVERY: "SOURCE_REQUIRED",
  CUSTOMER_AUTHORIZATION: "SOURCE_REQUIRED",
  JOB_COMPLETION: "READY_FOR_DEVICE_ACCEPTANCE",
  WORK_COMPLETED_COMMUNICATION: "PROVIDER_REQUIRED",
  INVOICE_HANDOFF: "READY_FOR_DEVICE_ACCEPTANCE",
  INVOICE_DELIVERY: "SOURCE_REQUIRED",
  PAYMENT_STATE: "SOURCE_REQUIRED",
  TIMEKEEPING: "ENGINEERING_READY",
  BREAKS: "ENGINEERING_READY",
  COMPLETED_JOB_HISTORY: "SOURCE_REQUIRED",
  NOTIFICATIONS: "SOURCE_REQUIRED",
  OFFLINE_READ_ONLY: "ENGINEERING_READY",
  MUTATION_RECOVERY: "ENGINEERING_READY",
  DYNAMIC_PERMISSIONS: "ENGINEERING_READY",
  ACCOUNT: "ENGINEERING_READY",
  NATIVE_IOS_BUILD: "ENGINEERING_READY",
  PHYSICAL_IPHONE_ACCEPTANCE: "READY_FOR_DEVICE_ACCEPTANCE",
  APPLE_SIGNING: "EXTERNAL_GATE",
  TESTFLIGHT: "EXTERNAL_GATE",
} as const satisfies Record<string, ReadinessClassification>;

export const FIELD_MUTATION_OFFLINE_POLICY = {
  ON_MY_WAY: "SAFE_IDEMPOTENT_RETRY_AFTER_RECONCILIATION",
  ARRIVAL: "SAFE_IDEMPOTENT_RETRY_AFTER_RECONCILIATION",
  START_WORK: "SAFE_IDEMPOTENT_RETRY_AFTER_RECONCILIATION",
  PAUSE_RESUME: "SAFE_IDEMPOTENT_RETRY_AFTER_RECONCILIATION",
  FIELD_SUMMARY: "SAFE_IDEMPOTENT_RETRY_AFTER_RECONCILIATION",
  CUSTOMER_DISPOSITION: "SAFE_IDEMPOTENT_RETRY_AFTER_RECONCILIATION",
  JOB_COMPLETION: "SAFE_IDEMPOTENT_RETRY_AFTER_RECONCILIATION",
  INVOICE_HANDOFF: "SAFE_IDEMPOTENT_RETRY_AFTER_RECONCILIATION",
  FIELD_PHOTO: "UNSUPPORTED_OFFLINE",
  ESTIMATE_ACTION: "UNSUPPORTED_OFFLINE",
  CUSTOMER_COMMUNICATION: "UNSUPPORTED_OFFLINE",
  TIMEKEEPING_PUNCH: "SAFE_IDEMPOTENT_RETRY_AFTER_RECONCILIATION",
} as const satisfies Record<string, OfflineMutationPolicy>;

export function fieldReadinessSummary() {
  const values = Object.values(FIELD_PRODUCT_READINESS);
  return {
    ready: values.filter((value) => value === "ENGINEERING_READY" || value === "READY_FOR_DEVICE_ACCEPTANCE").length,
    gated: values.filter((value) => value !== "ENGINEERING_READY" && value !== "READY_FOR_DEVICE_ACCEPTANCE").length,
  };
}
