"""create Payroll remittance foundation

Revision ID: 11a6e01206c0
Revises: d1u3q5s7v942
Create Date: 2026-08-29 16:51:10.146558

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '11a6e01206c0'
down_revision: str | Sequence[str] | None = 'd1u3q5s7v942'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_remittance_destinations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('destination_type', sa.String(length=48), nullable=False),
    sa.Column('jurisdiction_reference', sa.String(length=120), nullable=True),
    sa.Column('protected_reference', sa.String(length=160), nullable=False),
    sa.Column('masked_display', sa.String(length=80), nullable=False),
    sa.Column('effective_start', sa.Date(), nullable=False),
    sa.Column('effective_end', sa.Date(), nullable=True),
    sa.Column('lifecycle', sa.String(length=16), nullable=False),
    sa.Column('destination_identity', sa.String(length=128), nullable=False),
    sa.Column('destination_digest', sa.String(length=64), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('approved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("lifecycle IN ('draft','approved','superseded','revoked','expired')", name='ck_payroll_remittance_destination_lifecycle'),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'destination_identity', name='uq_payroll_remittance_destination_identity')
    )
    op.create_table('payroll_remittance_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('classification', sa.String(length=48), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('aggregation_permitted', sa.Boolean(), nullable=False),
    sa.Column('due_days_after_period', sa.Integer(), nullable=True),
    sa.Column('destination_required', sa.Boolean(), nullable=False),
    sa.Column('accounting_consequence', sa.String(length=48), nullable=False),
    sa.Column('effective_start', sa.Date(), nullable=False),
    sa.Column('effective_end', sa.Date(), nullable=True),
    sa.Column('lifecycle', sa.String(length=16), nullable=False),
    sa.Column('evidence_digest', sa.String(length=64), nullable=False),
    sa.Column('policy_digest', sa.String(length=64), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('approved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("lifecycle IN ('draft','approved','superseded','retired')", name='ck_payroll_remittance_policy_lifecycle'),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'classification', 'version', name='uq_payroll_remittance_policy_version'),
    sa.UniqueConstraint('company_id', 'policy_digest', name='uq_payroll_remittance_policy_digest')
    )
    op.create_index('ix_payroll_remittance_policy_resolve', 'payroll_remittance_policies', ['company_id', 'classification', 'lifecycle', 'effective_start', 'effective_end'], unique=False)
    op.create_table('payroll_remittance_obligations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('payroll_run_id', sa.UUID(), nullable=False),
    sa.Column('pay_period_id', sa.UUID(), nullable=False),
    sa.Column('classification', sa.String(length=48), nullable=False),
    sa.Column('source_digest', sa.String(length=64), nullable=False),
    sa.Column('contribution_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('policy_digest', sa.String(length=64), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=True),
    sa.Column('destination_digest', sa.String(length=64), nullable=True),
    sa.Column('obligation_start', sa.Date(), nullable=False),
    sa.Column('obligation_end', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('settled_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('lifecycle', sa.String(length=32), nullable=False),
    sa.Column('obligation_identity', sa.String(length=128), nullable=False),
    sa.Column('obligation_digest', sa.String(length=64), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('supersedes_obligation_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("lifecycle IN ('identified','ready_for_review','under_review','approved_for_remittance','instruction_prepared','submission_pending','submitted','provider_acknowledged','settlement_pending','partially_settled','settled','blocked','rejected','failed','uncertain','superseded','voided','returned','reversed')", name='ck_payroll_remittance_obligation_lifecycle'),
    sa.ForeignKeyConstraint(['company_id', 'payroll_run_id'], ['payroll_runs.company_id', 'payroll_runs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['destination_id'], ['payroll_remittance_destinations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['policy_id'], ['payroll_remittance_policies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supersedes_obligation_id'], ['payroll_remittance_obligations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'id', name='uq_payroll_remittance_obligation_company_id'),
    sa.UniqueConstraint('company_id', 'obligation_digest', name='uq_payroll_remittance_obligation_digest'),
    sa.UniqueConstraint('company_id', 'obligation_identity', name='uq_payroll_remittance_obligation_identity'),
    sa.UniqueConstraint('supersedes_obligation_id', name='uq_payroll_remittance_obligation_successor')
    )
    op.create_index('uq_payroll_remittance_active_source', 'payroll_remittance_obligations', ['company_id', 'payroll_run_id', 'classification'], unique=True, postgresql_where=sa.text("lifecycle NOT IN ('superseded','voided','returned','reversed')"))
    op.create_table('payroll_remittance_instructions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('obligation_id', sa.UUID(), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('provider_identity', sa.String(length=80), nullable=False),
    sa.Column('provider_version', sa.String(length=40), nullable=False),
    sa.Column('idempotency_identity', sa.String(length=128), nullable=False),
    sa.Column('instruction_identity', sa.String(length=128), nullable=False),
    sa.Column('instruction_digest', sa.String(length=64), nullable=False),
    sa.Column('lifecycle', sa.String(length=32), nullable=False),
    sa.Column('request_digest', sa.String(length=64), nullable=True),
    sa.Column('response_digest', sa.String(length=64), nullable=True),
    sa.Column('provider_reference', sa.String(length=160), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id', 'obligation_id'], ['payroll_remittance_obligations.company_id', 'payroll_remittance_obligations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['destination_id'], ['payroll_remittance_destinations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'id', name='uq_payroll_remittance_instruction_company_id'),
    sa.UniqueConstraint('instruction_digest', name='uq_payroll_remittance_instruction_digest'),
    sa.UniqueConstraint('obligation_id', name='uq_payroll_remittance_instruction_obligation')
    )
    op.create_table('payroll_remittance_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('obligation_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(length=24), nullable=False),
    sa.Column('reason_code', sa.String(length=80), nullable=False),
    sa.Column('safe_note', sa.Text(), nullable=True),
    sa.Column('obligation_digest', sa.String(length=64), nullable=False),
    sa.Column('review_digest', sa.String(length=64), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'obligation_id'], ['payroll_remittance_obligations.company_id', 'payroll_remittance_obligations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('obligation_id', 'sequence', name='uq_payroll_remittance_review_sequence'),
    sa.UniqueConstraint('review_digest', name='uq_payroll_remittance_review_digest')
    )
    op.create_table('payroll_remittance_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('instruction_id', sa.UUID(), nullable=False),
    sa.Column('evidence_type', sa.String(length=24), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('provider_safe_reference', sa.String(length=160), nullable=False),
    sa.Column('evidence_digest', sa.String(length=64), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_by_user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id', 'instruction_id'], ['payroll_remittance_instructions.company_id', 'payroll_remittance_instructions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instruction_id', 'evidence_digest', name='uq_payroll_remittance_evidence_digest')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payroll_remittance_evidence')
    op.drop_table('payroll_remittance_reviews')
    op.drop_table('payroll_remittance_instructions')
    op.drop_index('uq_payroll_remittance_active_source', table_name='payroll_remittance_obligations', postgresql_where=sa.text("lifecycle NOT IN ('superseded','voided','returned','reversed')"))
    op.drop_table('payroll_remittance_obligations')
    op.drop_index('ix_payroll_remittance_policy_resolve', table_name='payroll_remittance_policies')
    op.drop_table('payroll_remittance_policies')
    op.drop_table('payroll_remittance_destinations')
    # ### end Alembic commands ###
