"""create business events table

Revision ID: 218775b8a49c
Revises: 
Create Date: 2026-07-16 16:03:32.573612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '218775b8a49c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correlation_id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_events_branch_id'), 'business_events', ['branch_id'], unique=False)
    op.create_index(op.f('ix_business_events_company_id'), 'business_events', ['company_id'], unique=False)
    op.create_index(op.f('ix_business_events_correlation_id'), 'business_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_business_events_entity_id'), 'business_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_business_events_entity_type'), 'business_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_business_events_event_type'), 'business_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_business_events_occurred_at'), 'business_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_business_events_user_id'), 'business_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_business_events_user_id'), table_name='business_events')
    op.drop_index(op.f('ix_business_events_occurred_at'), table_name='business_events')
    op.drop_index(op.f('ix_business_events_event_type'), table_name='business_events')
    op.drop_index(op.f('ix_business_events_entity_type'), table_name='business_events')
    op.drop_index(op.f('ix_business_events_entity_id'), table_name='business_events')
    op.drop_index(op.f('ix_business_events_correlation_id'), table_name='business_events')
    op.drop_index(op.f('ix_business_events_company_id'), table_name='business_events')
    op.drop_index(op.f('ix_business_events_branch_id'), table_name='business_events')
    op.drop_table('business_events')
    # ### end Alembic commands ###
