"""complete payroll compliance experience authority

Revision ID: 99abf7192edf
Revises: 17g2i67862h6
Create Date: 2026-08-30 13:07:52.420362

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "99abf7192edf"
down_revision: str | Sequence[str] | None = "17g2i67862h6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payroll_compliance_schemas",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("jurisdiction_reference", sa.String(length=120), nullable=False),
        sa.Column("package_family", sa.String(length=80), nullable=False),
        sa.Column("tax_year", sa.Integer(), nullable=False),
        sa.Column("quarter", sa.Integer(), nullable=True),
        sa.Column("schema_version", sa.String(length=80), nullable=False),
        sa.Column("rule_version", sa.String(length=80), nullable=False),
        sa.Column(
            "required_evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "legal_content_slots",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("effective_start", sa.Date(), nullable=False),
        sa.Column("effective_end", sa.Date(), nullable=True),
        sa.Column("schema_identity", sa.String(length=128), nullable=False),
        sa.Column("schema_digest", sa.String(length=64), nullable=False),
        sa.Column("lifecycle", sa.String(length=16), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.Column("approved_by_user_id", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "lifecycle IN ('draft','approved','superseded','retired')",
            name="ck_payroll_compliance_schema_lifecycle",
        ),
        sa.CheckConstraint(
            "effective_end IS NULL OR effective_end >= effective_start",
            name="ck_payroll_compliance_schema_interval",
        ),
        sa.CheckConstraint(
            "quarter IS NULL OR quarter BETWEEN 1 AND 4",
            name="ck_payroll_compliance_schema_quarter",
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_user_id"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "company_id",
            "schema_identity",
            name="uq_payroll_compliance_schema_identity",
        ),
    )
    op.create_index(
        "ix_payroll_compliance_schema_resolution",
        "payroll_compliance_schemas",
        [
            "company_id",
            "jurisdiction_reference",
            "package_family",
            "tax_year",
            "quarter",
            "lifecycle",
        ],
        unique=False,
    )
    op.create_table(
        "payroll_reporting_artifacts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("source_type", sa.String(length=24), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("source_digest", sa.String(length=64), nullable=False),
        sa.Column("render_version", sa.String(length=80), nullable=False),
        sa.Column("media_type", sa.String(length=80), nullable=False),
        sa.Column("artifact_identity", sa.String(length=128), nullable=False),
        sa.Column("artifact_digest", sa.String(length=64), nullable=False),
        sa.Column("storage_reference", sa.String(length=128), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("lifecycle", sa.String(length=16), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "lifecycle IN ('generated','retained','superseded','voided')",
            name="ck_payroll_reporting_artifact_lifecycle",
        ),
        sa.CheckConstraint(
            "source_type IN ('report','filing_package')",
            name="ck_payroll_reporting_artifact_source",
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "company_id",
            "artifact_identity",
            name="uq_payroll_reporting_artifact_identity",
        ),
        sa.UniqueConstraint(
            "company_id",
            "storage_reference",
            name="uq_payroll_reporting_artifact_storage",
        ),
    )
    op.create_index(
        "ix_payroll_reporting_artifact_source",
        "payroll_reporting_artifacts",
        ["company_id", "source_type", "source_id"],
        unique=False,
    )
    op.add_column(
        "payroll_filing_packages",
        sa.Column("compliance_schema_id", sa.UUID(), nullable=True),
    )
    op.add_column(
        "payroll_filing_packages",
        sa.Column("supersedes_package_id", sa.UUID(), nullable=True),
    )
    op.add_column(
        "payroll_filing_packages",
        sa.Column("amendment_evidence_digest", sa.String(length=64), nullable=True),
    )
    op.create_foreign_key(
        "fk_payroll_filing_package_predecessor",
        "payroll_filing_packages",
        "payroll_filing_packages",
        ["supersedes_package_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        "fk_payroll_filing_package_compliance_schema",
        "payroll_filing_packages",
        "payroll_compliance_schemas",
        ["compliance_schema_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_payroll_filing_package_compliance_schema",
        "payroll_filing_packages",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_payroll_filing_package_predecessor",
        "payroll_filing_packages",
        type_="foreignkey",
    )
    op.drop_column("payroll_filing_packages", "amendment_evidence_digest")
    op.drop_column("payroll_filing_packages", "supersedes_package_id")
    op.drop_column("payroll_filing_packages", "compliance_schema_id")
    op.execute("DROP INDEX IF EXISTS ix_payroll_reporting_artifact_source")
    op.drop_table("payroll_reporting_artifacts")
    op.drop_index(
        "ix_payroll_compliance_schema_resolution",
        table_name="payroll_compliance_schemas",
    )
    op.drop_table("payroll_compliance_schemas")
    # ### end Alembic commands ###
