"""complete business economics owner experience

Revision ID: b0ff279c5aeb
Revises: 17g2i67862h6
Create Date: 2026-08-30 13:42:12.693560

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b0ff279c5aeb"
down_revision: Union[str, Sequence[str], None] = "17g2i67862h6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "economics_profitability_results",
        sa.Column("components", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "economics_profitability_results",
        sa.Column("quality", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "economics_profitability_results",
        sa.Column(
            "explanation", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("economics_profitability_results", "explanation")
    op.drop_column("economics_profitability_results", "quality")
    op.drop_column("economics_profitability_results", "components")
    # ### end Alembic commands ###
