"""persist admitted economics profitability

Revision ID: cb4c29cf0e3c
Revises: ed6ce4a21942
Create Date: 2026-08-29 18:20:38.276161

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb4c29cf0e3c'
down_revision: str | Sequence[str] | None = 'ed6ce4a21942'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('economics_profitability_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('subject_kind', sa.String(length=32), nullable=False),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('basis', sa.String(length=32), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('admission_id', sa.String(length=128), nullable=False),
    sa.Column('admission_digest', sa.String(length=64), nullable=False),
    sa.Column('package_id', sa.String(length=128), nullable=False),
    sa.Column('package_digest', sa.String(length=64), nullable=False),
    sa.Column('computation_digest', sa.String(length=64), nullable=False),
    sa.Column('result_identity', sa.String(length=128), nullable=False),
    sa.Column('result_digest', sa.String(length=64), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('acquisition_digests', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('allocation_digests', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('explanation_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('lifecycle', sa.String(length=16), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("lifecycle IN ('admitted','superseded','voided')", name='ck_eco_profitability_result_lifecycle'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'result_identity', name='uq_eco_profitability_result_identity')
    )
    op.create_index('ix_eco_profitability_result_subject', 'economics_profitability_results', ['company_id', 'subject_id', 'period_start', 'period_end'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_eco_profitability_result_subject', table_name='economics_profitability_results')
    op.drop_table('economics_profitability_results')
    # ### end Alembic commands ###
