"""create payroll reporting authority

Revision ID: dbb3f829f4dc
Revises: 14d9f34539f3
Create Date: 2026-08-29 18:10:42.397777

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'dbb3f829f4dc'
down_revision: str | Sequence[str] | None = '15e0g45640f4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_history_coverage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('coverage_start', sa.Date(), nullable=False),
    sa.Column('coverage_end', sa.Date(), nullable=False),
    sa.Column('source_authority', sa.String(length=80), nullable=False),
    sa.Column('source_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.Column('coverage_identity', sa.String(length=128), nullable=False),
    sa.Column('evidence_digest', sa.String(length=64), nullable=False),
    sa.Column('lifecycle', sa.String(length=16), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('approved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("lifecycle IN ('draft','approved','superseded','retired')", name='ck_payroll_history_coverage_lifecycle'),
    sa.CheckConstraint('coverage_end >= coverage_start', name='ck_payroll_history_coverage_interval'),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'coverage_identity', name='uq_payroll_history_coverage_identity')
    )
    op.create_index('ix_payroll_history_coverage_resolution', 'payroll_history_coverage', ['company_id', 'lifecycle', 'coverage_start', 'coverage_end'], unique=False)
    op.create_table('payroll_reporting_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=True),
    sa.Column('period_identity', sa.String(length=120), nullable=False),
    sa.Column('period_kind', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('totals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_digests', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('coverage_evidence_id', sa.String(length=128), nullable=True),
    sa.Column('blockers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reconciliation_digest', sa.String(length=64), nullable=False),
    sa.Column('report_identity', sa.String(length=128), nullable=False),
    sa.Column('report_digest', sa.String(length=64), nullable=False),
    sa.Column('definition_version', sa.String(length=80), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("period_kind IN ('pay_period','quarter','year')", name='ck_payroll_reporting_period_kind'),
    sa.CheckConstraint("state IN ('authoritative','partial','unavailable','conflicting')", name='ck_payroll_reporting_state'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'report_identity', name='uq_payroll_reporting_identity')
    )
    op.create_index('ix_payroll_reporting_period', 'payroll_reporting_snapshots', ['company_id', 'period_start', 'period_end', 'employee_id'], unique=False)
    op.create_table('payroll_filing_packages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('reporting_snapshot_id', sa.UUID(), nullable=False),
    sa.Column('reporting_digest', sa.String(length=64), nullable=False),
    sa.Column('configuration_id', sa.String(length=128), nullable=False),
    sa.Column('configuration_digest', sa.String(length=64), nullable=False),
    sa.Column('jurisdiction_reference', sa.String(length=120), nullable=False),
    sa.Column('package_type', sa.String(length=80), nullable=False),
    sa.Column('schema_version', sa.String(length=80), nullable=False),
    sa.Column('payload_digest', sa.String(length=64), nullable=False),
    sa.Column('package_identity', sa.String(length=128), nullable=False),
    sa.Column('package_digest', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("state IN ('prepared_not_submitted','superseded','voided')", name='ck_payroll_filing_package_state'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reporting_snapshot_id'], ['payroll_reporting_snapshots.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'package_identity', name='uq_payroll_filing_package_identity')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payroll_filing_packages')
    op.drop_index('ix_payroll_reporting_period', table_name='payroll_reporting_snapshots')
    op.drop_table('payroll_reporting_snapshots')
    op.drop_index('ix_payroll_history_coverage_resolution', table_name='payroll_history_coverage')
    op.drop_table('payroll_history_coverage')
    # ### end Alembic commands ###
