"""bind authoritative YTD to pay statements

Revision ID: ed6ce4a21942
Revises: dbb3f829f4dc
Create Date: 2026-08-29 18:14:28.513110

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ed6ce4a21942'
down_revision: str | Sequence[str] | None = 'dbb3f829f4dc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payroll_pay_statements', sa.Column('reporting_snapshot_id', sa.UUID(), nullable=True))
    op.add_column('payroll_pay_statements', sa.Column('reporting_digest', sa.String(length=64), nullable=True))
    op.create_foreign_key(None, 'payroll_pay_statements', 'payroll_reporting_snapshots', ['reporting_snapshot_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payroll_pay_statements', type_='foreignkey')
    op.drop_column('payroll_pay_statements', 'reporting_digest')
    op.drop_column('payroll_pay_statements', 'reporting_snapshot_id')
    # ### end Alembic commands ###
