"""create service agreement product authority

Revision ID: g5e4c93b0f6d
Revises: f4d3b82a9e5c
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="g5e4c93b0f6d"; down_revision="f4d3b82a9e5c"; branch_labels=None; depends_on=None

def upgrade():
    op.create_table("service_agreement_plans",
      sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("company_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("companies.id",ondelete="RESTRICT"),nullable=False),sa.Column("branch_id",postgresql.UUID(as_uuid=True)),sa.Column("code",sa.String(80),nullable=False),sa.Column("name",sa.String(160),nullable=False),sa.Column("version",sa.Integer(),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("currency",sa.String(3),nullable=False),sa.Column("price_amount",sa.Numeric(18,2)),sa.Column("billing_cadence",sa.String(20),nullable=False),sa.Column("duration_months",sa.Integer(),nullable=False),sa.Column("included_visits",sa.Integer(),nullable=False),sa.Column("benefits",sa.JSON(),nullable=False),sa.Column("renewal_policy",sa.JSON(),nullable=False),sa.Column("cancellation_policy",sa.JSON(),nullable=False),sa.Column("definition_digest",sa.String(64),nullable=False),sa.Column("created_by_user_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("activated_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.CheckConstraint("status IN ('draft','active','superseded','inactive')",name="ck_agreement_plans_status"),sa.CheckConstraint("version >= 1 AND duration_months > 0 AND included_visits >= 0",name="ck_agreement_plans_values"),sa.CheckConstraint("billing_cadence IN ('unconfigured','monthly','annual','single')",name="ck_agreement_plans_cadence"),sa.UniqueConstraint("company_id","code","version",name="uq_agreement_plans_code_version"))
    op.create_table("service_agreements",
      sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("company_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("companies.id",ondelete="RESTRICT"),nullable=False),sa.Column("branch_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("customer_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("customers.id",ondelete="RESTRICT"),nullable=False),sa.Column("plan_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("service_agreement_plans.id",ondelete="RESTRICT"),nullable=False),sa.Column("agreement_number",sa.String(40),nullable=False),sa.Column("status",sa.String(24),nullable=False),sa.Column("start_date",sa.Date(),nullable=False),sa.Column("end_date",sa.Date(),nullable=False),sa.Column("plan_snapshot",sa.JSON(),nullable=False),sa.Column("evidence_digest",sa.String(64),nullable=False),sa.Column("idempotency_key",sa.String(160),nullable=False),sa.Column("version",sa.Integer(),nullable=False),sa.Column("cancellation_reason",sa.Text()),sa.Column("created_by_user_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.ForeignKeyConstraint(["company_id","branch_id"],["branches.company_id","branches.id"],name="fk_service_agreements_branch",ondelete="RESTRICT"),sa.CheckConstraint("status IN ('draft','pending_activation','active','renewal_pending','renewed','cancelled','expired','suspended')",name="ck_service_agreements_status"),sa.CheckConstraint("version >= 1 AND end_date >= start_date",name="ck_service_agreements_values"),sa.UniqueConstraint("company_id","agreement_number",name="uq_service_agreements_number"),sa.UniqueConstraint("company_id","idempotency_key",name="uq_service_agreements_idempotency"))
    op.create_table("service_agreement_coverage",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("company_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("companies.id",ondelete="RESTRICT"),nullable=False),sa.Column("agreement_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("service_agreements.id",ondelete="RESTRICT"),nullable=False),sa.Column("service_location_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("service_locations.id",ondelete="RESTRICT"),nullable=False),sa.Column("effective_from",sa.Date(),nullable=False),sa.Column("effective_to",sa.Date(),nullable=False),sa.UniqueConstraint("company_id","agreement_id","service_location_id",name="uq_agreement_coverage_location"))
    op.create_table("service_agreement_entitlements",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("company_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("companies.id",ondelete="RESTRICT"),nullable=False),sa.Column("branch_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("agreement_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("service_agreements.id",ondelete="RESTRICT"),nullable=False),sa.Column("service_location_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("service_locations.id",ondelete="RESTRICT"),nullable=False),sa.Column("sequence",sa.Integer(),nullable=False),sa.Column("service_category",sa.String(100),nullable=False),sa.Column("eligible_from",sa.Date(),nullable=False),sa.Column("eligible_to",sa.Date(),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("appointment_id",postgresql.UUID(as_uuid=True)),sa.Column("job_id",postgresql.UUID(as_uuid=True)),sa.Column("source_digest",sa.String(64),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.CheckConstraint("status IN ('due','scheduled','completed','expired','cancelled','blocked')",name="ck_agreement_entitlements_status"),sa.UniqueConstraint("company_id","agreement_id","service_location_id","sequence",name="uq_agreement_entitlement_sequence"))
def downgrade():
    op.drop_table("service_agreement_entitlements"); op.drop_table("service_agreement_coverage"); op.drop_table("service_agreements"); op.drop_table("service_agreement_plans")
