"""add service agreement lifecycle and billing evidence

Revision ID: h6f5d04c1a7e
Revises: g5e4c93b0f6d
Create Date: 2026-08-30 16:36:34.899089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'h6f5d04c1a7e'
down_revision: Union[str, Sequence[str], None] = 'g5e4c93b0f6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_agreement_billing_occurrences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('agreement_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('payment_state', sa.String(length=32), nullable=False),
    sa.Column('evidence_digest', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('unconfigured','ready','invoiced','cancelled','reconciliation_required')", name='ck_agreement_billing_status'),
    sa.ForeignKeyConstraint(['agreement_id'], ['service_agreements.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'agreement_id', 'period_start', name='uq_agreement_billing_period'),
    sa.UniqueConstraint('company_id', 'idempotency_key', name='uq_agreement_billing_idempotency')
    )
    op.create_table('service_agreement_lifecycle_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('agreement_id', sa.UUID(), nullable=False),
    sa.Column('entitlement_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('prior_status', sa.String(length=24), nullable=False),
    sa.Column('resulting_status', sa.String(length=24), nullable=False),
    sa.Column('request_digest', sa.String(length=64), nullable=False),
    sa.Column('evidence_digest', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("action IN ('activate','renewal_review','renew','cancel','expire','generate_entitlements','schedule_link','job_link','consume','reverse_consumption','billing_ready')", name='ck_agreement_evidence_action'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['agreement_id'], ['service_agreements.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['entitlement_id'], ['service_agreement_entitlements.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'idempotency_key', name='uq_agreement_evidence_idempotency')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_agreement_lifecycle_evidence')
    op.drop_table('service_agreement_billing_occurrences')
    # ### end Alembic commands ###
