"""make agreement plan commands idempotent

Revision ID: j8h7f26e3c9a
Revises: i7g6e15d2b8f
Create Date: 2026-08-30 17:54:56.205533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'j8h7f26e3c9a'
down_revision: Union[str, Sequence[str], None] = 'i7g6e15d2b8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_agreement_plans', sa.Column('idempotency_key', sa.String(length=160), nullable=False))
    op.create_unique_constraint('uq_agreement_plans_idempotency', 'service_agreement_plans', ['company_id', 'idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_agreement_plans_idempotency', 'service_agreement_plans', type_='unique')
    op.drop_column('service_agreement_plans', 'idempotency_key')
    # ### end Alembic commands ###
