"""add service agreement renewal lineage

Revision ID: k3s5a7g9r123
Revises: k2s4a6g8r012
Create Date: 2026-08-30 17:51:16.202791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'k3s5a7g9r123'
down_revision: Union[str, Sequence[str], None] = 'k2s4a6g8r012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_agreements', sa.Column('predecessor_agreement_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'service_agreements', 'service_agreements', ['predecessor_agreement_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service_agreements', type_='foreignkey')
    op.drop_column('service_agreements', 'predecessor_agreement_id')
    # ### end Alembic commands ###
