"""make agreement plan commands idempotent

Revision ID: k4s6a8g0r234
Revises: k3s5a7g9r123
Create Date: 2026-08-30 17:54:56.205533

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "k4s6a8g0r234"
down_revision: str | Sequence[str] | None = "k3s5a7g9r123"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_agreement_plans",
        sa.Column("idempotency_key", sa.String(length=160), nullable=False),
    )
    op.create_unique_constraint(
        "uq_agreement_plans_idempotency",
        "service_agreement_plans",
        ["company_id", "idempotency_key"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_agreement_plans_idempotency", "service_agreement_plans", type_="unique"
    )
    op.drop_column("service_agreement_plans", "idempotency_key")
    # ### end Alembic commands ###
