"""create invoice accounts receivable foundation

Revision ID: w8m0i2k4n619
Revises: w8m0i2e4f619
Create Date: 2026-08-13 22:41:52.250797

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "w8m0i2k4n619"
down_revision: str | Sequence[str] | None = "w8m0i2e4f619"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invoice_number_sequences",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("last_value", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("last_value >= 0", name="ck_invoice_sequence"),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("company_id"),
    )
    op.create_table(
        "invoice_payment_receipt_evidence",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("receipt_id", sa.UUID(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("verified_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column(
            "available_amount", sa.Numeric(precision=18, scale=2), nullable=False
        ),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("evidence_digest", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "verified_amount > 0 AND available_amount >= 0 AND available_amount <= verified_amount",
            name="ck_invoice_receipts_amount",
        ),
        sa.ForeignKeyConstraint(
            ["company_id", "branch_id"],
            ["branches.company_id", "branches.id"],
            name="fk_invoice_receipts_branch",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "company_id", "receipt_id", name="uq_invoice_receipts_source"
        ),
    )
    op.create_table(
        "ar_ledger_entries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("invoice_id", sa.UUID(), nullable=False),
        sa.Column("entry_type", sa.String(length=32), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("source_version", sa.Integer(), nullable=False),
        sa.Column("reason_code", sa.String(length=80), nullable=True),
        sa.Column("idempotency_key", sa.String(length=160), nullable=False),
        sa.Column("actor_user_id", sa.UUID(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "entry_type IN ('obligation','credit_memo','write_off','void','payment_application','application_reversal','write_off_reversal')",
            name="ck_ar_entries_type",
        ),
        sa.CheckConstraint("amount <> 0", name="ck_ar_entries_amount"),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["company_id", "branch_id"],
            ["branches.company_id", "branches.id"],
            name="fk_ar_entries_branch",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id", "invoice_id"],
            ["invoices.company_id", "invoices.id"],
            name="fk_ar_entries_invoice",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "company_id", "idempotency_key", name="uq_ar_entries_idempotency"
        ),
    )
    op.create_index(
        "ix_ar_entries_invoice_time",
        "ar_ledger_entries",
        ["company_id", "invoice_id", "occurred_at", "id"],
        unique=False,
    )
    op.create_table(
        "invoice_accounting_posting_receipts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("invoice_id", sa.UUID(), nullable=False),
        sa.Column("source_event_id", sa.UUID(), nullable=False),
        sa.Column("journal_id", sa.UUID(), nullable=False),
        sa.Column("journal_version", sa.Integer(), nullable=False),
        sa.Column("policy_version", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('posted','reversed','reconciliation_required')",
            name="ck_invoice_posting_receipts_status",
        ),
        sa.ForeignKeyConstraint(
            ["company_id", "branch_id"],
            ["branches.company_id", "branches.id"],
            name="fk_invoice_posting_receipts_branch",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id", "invoice_id"],
            ["invoices.company_id", "invoices.id"],
            name="fk_invoice_posting_receipts_invoice",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "company_id", "source_event_id", name="uq_invoice_posting_receipts_event"
        ),
    )
    op.create_table(
        "invoice_idempotency",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=160), nullable=False),
        sa.Column("operation", sa.String(length=64), nullable=False),
        sa.Column("request_digest", sa.String(length=64), nullable=False),
        sa.Column("invoice_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["invoice_id"], ["invoices.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "company_id", "idempotency_key", name="uq_invoice_idempotency_key"
        ),
    )
    op.add_column(
        "invoice_line_items", sa.Column("estimate_line_id", sa.UUID(), nullable=True)
    )
    op.add_column(
        "invoice_line_items", sa.Column("snapshot_id", sa.UUID(), nullable=True)
    )
    op.add_column(
        "invoice_line_items",
        sa.Column("snapshot_digest", sa.String(length=64), nullable=True),
    )
    op.add_column(
        "invoice_line_items", sa.Column("title", sa.String(length=240), nullable=True)
    )
    op.add_column(
        "invoice_line_items",
        sa.Column(
            "discount_allocation", sa.Numeric(precision=18, scale=2), nullable=True
        ),
    )
    op.add_column(
        "invoice_line_items",
        sa.Column("discounted_basis", sa.Numeric(precision=18, scale=2), nullable=True),
    )
    op.add_column(
        "invoice_line_items", sa.Column("taxable", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "invoice_line_items",
        sa.Column("tax_classification_id", sa.UUID(), nullable=True),
    )
    op.add_column(
        "invoice_line_items", sa.Column("tax_policy_id", sa.UUID(), nullable=True)
    )
    op.add_column(
        "invoice_line_items",
        sa.Column("tax_policy_version", sa.Integer(), nullable=True),
    )
    op.add_column(
        "invoice_line_items",
        sa.Column("tax_rate_basis_points", sa.Integer(), nullable=True),
    )
    op.add_column(
        "invoice_line_items",
        sa.Column("tax_amount", sa.Numeric(precision=18, scale=2), nullable=True),
    )
    op.add_column(
        "invoice_line_items", sa.Column("currency", sa.String(length=3), nullable=True)
    )
    op.add_column("invoice_line_items", sa.Column("evidence", sa.JSON(), nullable=True))
    op.add_column(
        "invoice_line_items",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.execute(
        "UPDATE invoice_line_items SET title = description, evidence = '{\"legacy_evidence_missing\": true}'::json, created_at = CURRENT_TIMESTAMP"
    )
    op.alter_column("invoice_line_items", "title", nullable=False)
    op.alter_column("invoice_line_items", "evidence", nullable=False)
    op.alter_column("invoice_line_items", "created_at", nullable=False)
    op.alter_column(
        "invoice_line_items",
        "quantity",
        existing_type=sa.NUMERIC(precision=12, scale=3),
        type_=sa.Numeric(precision=18, scale=6),
        existing_nullable=False,
    )
    op.alter_column(
        "invoice_line_items",
        "unit_price",
        existing_type=sa.NUMERIC(precision=14, scale=2),
        type_=sa.Numeric(precision=18, scale=4),
        existing_nullable=False,
    )
    op.alter_column(
        "invoice_line_items",
        "total_amount",
        existing_type=sa.NUMERIC(precision=14, scale=2),
        type_=sa.Numeric(precision=18, scale=2),
        existing_nullable=False,
    )
    op.create_unique_constraint(
        "uq_invoice_lines_position",
        "invoice_line_items",
        ["company_id", "invoice_id", "position"],
    )
    op.create_foreign_key(
        "fk_invoice_lines_company",
        "invoice_line_items",
        "companies",
        ["company_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_check_constraint(
        "ck_invoice_lines_amounts",
        "invoice_line_items",
        "position >= 1 AND quantity > 0 AND unit_price >= 0 AND total_amount >= 0",
    )
    op.create_check_constraint(
        "ck_invoice_lines_calculations",
        "invoice_line_items",
        "discount_allocation >= 0 AND discounted_basis >= 0 AND tax_amount >= 0",
    )
    op.add_column("invoices", sa.Column("estimate_id", sa.UUID(), nullable=True))
    op.add_column(
        "invoices", sa.Column("estimate_revision_id", sa.UUID(), nullable=True)
    )
    op.add_column(
        "invoices", sa.Column("accounting_status", sa.String(length=32), nullable=True)
    )
    op.add_column("invoices", sa.Column("issue_date", sa.Date(), nullable=True))
    op.add_column("invoices", sa.Column("due_date", sa.Date(), nullable=True))
    op.add_column("invoices", sa.Column("terms", sa.Text(), nullable=True))
    op.add_column(
        "invoices",
        sa.Column("discount_amount", sa.Numeric(precision=18, scale=2), nullable=True),
    )
    op.add_column(
        "invoices",
        sa.Column("taxable_basis", sa.Numeric(precision=18, scale=2), nullable=True),
    )
    op.add_column(
        "invoices",
        sa.Column("open_amount", sa.Numeric(precision=18, scale=2), nullable=True),
    )
    op.add_column(
        "invoices", sa.Column("calculation_digest", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "invoices", sa.Column("legacy_evidence_missing", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "invoices",
        sa.Column(
            "identity_origin",
            sa.String(length=32),
            nullable=True,
            server_default="native",
        ),
    )
    op.add_column("invoices", sa.Column("version", sa.Integer(), nullable=True))
    op.add_column("invoices", sa.Column("updated_by_user_id", sa.UUID(), nullable=True))
    op.add_column(
        "invoices", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.execute("""
        DO $$ BEGIN
          IF EXISTS (
            SELECT 1
            FROM invoices i
            WHERE NOT EXISTS (
              SELECT 1
              FROM operational_migration_invoice_source_identities source
              WHERE source.company_id = i.company_id
                AND source.branch_id = i.branch_id
                AND source.invoice_id = i.id
                AND source.customer_id = i.customer_id
                AND source.service_location_id = i.service_location_id
            )
          ) THEN
            RAISE EXCEPTION 'Pre-contract Invoice lacks authoritative migration source provenance';
          END IF;
        END $$
    """)
    op.execute("""
        UPDATE invoices
        SET accounting_status = 'reconciliation_required',
            issue_date = COALESCE(issued_at::date, created_at::date),
            due_date = COALESCE(due_on, issued_at::date, created_at::date),
            terms = 'Legacy invoice terms require source reconciliation',
            discount_amount = 0,
            open_amount = total_amount,
            calculation_digest = lpad(md5(id::text || invoice_number), 64, '0'),
            legacy_evidence_missing = true,
            identity_origin = 'grandfathered_legacy',
            version = 1,
            updated_by_user_id = created_by_user_id,
            updated_at = created_at
    """)
    for column in (
        "accounting_status",
        "issue_date",
        "due_date",
        "terms",
        "discount_amount",
        "open_amount",
        "calculation_digest",
        "legacy_evidence_missing",
        "identity_origin",
        "version",
        "updated_by_user_id",
        "updated_at",
    ):
        op.alter_column("invoices", column, nullable=False)
    op.drop_constraint("ck_invoices_status", "invoices", type_="check")
    op.drop_constraint("ck_invoices_amounts", "invoices", type_="check")
    op.alter_column(
        "invoices",
        "status",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=24),
        existing_nullable=False,
    )
    op.alter_column(
        "invoices",
        "subtotal_amount",
        existing_type=sa.NUMERIC(precision=14, scale=2),
        type_=sa.Numeric(precision=18, scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "invoices",
        "tax_amount",
        existing_type=sa.NUMERIC(precision=14, scale=2),
        type_=sa.Numeric(precision=18, scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "invoices",
        "total_amount",
        existing_type=sa.NUMERIC(precision=14, scale=2),
        type_=sa.Numeric(precision=18, scale=2),
        existing_nullable=False,
    )
    op.create_index(
        "ix_invoices_company_branch_status_due",
        "invoices",
        ["company_id", "branch_id", "status", "due_date"],
        unique=False,
    )
    op.create_index(
        "ix_invoices_company_customer_due",
        "invoices",
        ["company_id", "customer_id", "due_date"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_invoices_company_number", "invoices", ["company_id", "invoice_number"]
    )
    op.create_unique_constraint(
        "uq_invoices_estimate_revision",
        "invoices",
        ["company_id", "estimate_revision_id"],
    )
    op.drop_constraint(
        op.f("invoices_service_location_id_fkey"), "invoices", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_invoices_branch",
        "invoices",
        "branches",
        ["company_id", "branch_id"],
        ["company_id", "id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        "fk_invoices_company",
        "invoices",
        "companies",
        ["company_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        "fk_invoices_location_customer",
        "invoices",
        "service_locations",
        ["service_location_id", "customer_id"],
        ["id", "customer_id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        "fk_invoices_updated_by",
        "invoices",
        "users",
        ["updated_by_user_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        "fk_invoices_estimate",
        "invoices",
        "estimate_proposals",
        ["company_id", "estimate_id"],
        ["company_id", "id"],
        ondelete="RESTRICT",
    )
    op.create_check_constraint(
        "ck_invoices_accounting_status",
        "invoices",
        "accounting_status IN ('pending','posted','reversed','reconciliation_required')",
    )
    op.create_check_constraint(
        "ck_invoices_currency", "invoices", "currency ~ '^[A-Z]{3}$'"
    )
    op.create_check_constraint(
        "ck_invoices_dates", "invoices", "due_date >= issue_date"
    )
    op.create_check_constraint(
        "ck_invoices_number",
        "invoices",
        "(identity_origin = 'native' AND invoice_number ~ '^INV-[0-9]{6,}$') "
        "OR (identity_origin = 'grandfathered_legacy' AND legacy_evidence_missing = true)",
    )
    op.create_check_constraint(
        "ck_invoices_identity_origin",
        "invoices",
        "identity_origin IN ('native','grandfathered_legacy')",
    )
    op.create_check_constraint("ck_invoices_version", "invoices", "version >= 1")
    op.create_check_constraint(
        "ck_invoices_status",
        "invoices",
        "status IN ('draft','cancelled','issued','partially_paid','adjusted','paid','voided')",
    )
    op.create_check_constraint(
        "ck_invoices_amounts",
        "invoices",
        "subtotal_amount >= 0 AND discount_amount >= 0 AND tax_amount >= 0 AND total_amount >= 0 AND open_amount >= 0",
    )
    op.execute("""
        CREATE FUNCTION prevent_invoice_financial_evidence_mutation()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          RAISE EXCEPTION 'invoice financial evidence is append-only';
        END;
        $$
    """)
    for table_name in (
        "ar_ledger_entries",
        "invoice_idempotency",
        "invoice_accounting_posting_receipts",
    ):
        op.execute(f"""
            CREATE TRIGGER tr_{table_name}_append_only
            BEFORE UPDATE OR DELETE ON {table_name}
            FOR EACH ROW EXECUTE FUNCTION prevent_invoice_financial_evidence_mutation()
        """)
    op.execute("""
        CREATE FUNCTION enforce_invoice_identity_provenance()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          IF TG_OP = 'UPDATE' AND (
            NEW.identity_origin IS DISTINCT FROM OLD.identity_origin
            OR NEW.invoice_number IS DISTINCT FROM OLD.invoice_number
          ) THEN
            RAISE EXCEPTION 'invoice identity provenance is immutable';
          END IF;
          IF NEW.identity_origin = 'grandfathered_legacy' AND NOT EXISTS (
            SELECT 1
            FROM operational_migration_invoice_source_identities source
            WHERE source.company_id = NEW.company_id
              AND source.branch_id = NEW.branch_id
              AND source.invoice_id = NEW.id
              AND source.customer_id = NEW.customer_id
              AND source.service_location_id = NEW.service_location_id
          ) THEN
            RAISE EXCEPTION 'grandfathered Invoice requires authoritative migration source provenance';
          END IF;
          RETURN NEW;
        END;
        $$
    """)
    op.execute("""
        CREATE CONSTRAINT TRIGGER tr_invoices_identity_provenance
        AFTER INSERT OR UPDATE ON invoices
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW EXECUTE FUNCTION enforce_invoice_identity_provenance()
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("""
        DO $$ BEGIN
          IF EXISTS (SELECT 1 FROM invoices WHERE legacy_evidence_missing = false)
             OR EXISTS (SELECT 1 FROM ar_ledger_entries) THEN
            RAISE EXCEPTION 'Invoice/AR evidence exists; downgrade would destroy financial history';
          END IF;
        END $$
    """)
    op.execute("DROP TRIGGER tr_invoices_identity_provenance ON invoices")
    op.execute("DROP FUNCTION enforce_invoice_identity_provenance")
    for table_name in (
        "ar_ledger_entries",
        "invoice_idempotency",
        "invoice_accounting_posting_receipts",
    ):
        op.execute(f"DROP TRIGGER tr_{table_name}_append_only ON {table_name}")
    op.execute("DROP FUNCTION prevent_invoice_financial_evidence_mutation")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_invoices_amounts", "invoices", type_="check")
    op.drop_constraint("ck_invoices_status", "invoices", type_="check")
    op.drop_constraint("ck_invoices_version", "invoices", type_="check")
    op.drop_constraint("ck_invoices_identity_origin", "invoices", type_="check")
    op.drop_constraint("ck_invoices_number", "invoices", type_="check")
    op.drop_constraint("ck_invoices_dates", "invoices", type_="check")
    op.drop_constraint("ck_invoices_currency", "invoices", type_="check")
    op.drop_constraint("ck_invoices_accounting_status", "invoices", type_="check")
    op.drop_constraint("fk_invoices_estimate", "invoices", type_="foreignkey")
    op.drop_constraint("fk_invoices_updated_by", "invoices", type_="foreignkey")
    op.drop_constraint("fk_invoices_location_customer", "invoices", type_="foreignkey")
    op.drop_constraint("fk_invoices_company", "invoices", type_="foreignkey")
    op.drop_constraint("fk_invoices_branch", "invoices", type_="foreignkey")
    op.create_foreign_key(
        op.f("invoices_service_location_id_fkey"),
        "invoices",
        "service_locations",
        ["service_location_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_constraint("uq_invoices_estimate_revision", "invoices", type_="unique")
    op.drop_constraint("uq_invoices_company_number", "invoices", type_="unique")
    op.drop_index("ix_invoices_company_customer_due", table_name="invoices")
    op.drop_index("ix_invoices_company_branch_status_due", table_name="invoices")
    op.alter_column(
        "invoices",
        "total_amount",
        existing_type=sa.Numeric(precision=18, scale=2),
        type_=sa.NUMERIC(precision=14, scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "invoices",
        "tax_amount",
        existing_type=sa.Numeric(precision=18, scale=2),
        type_=sa.NUMERIC(precision=14, scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "invoices",
        "subtotal_amount",
        existing_type=sa.Numeric(precision=18, scale=2),
        type_=sa.NUMERIC(precision=14, scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "invoices",
        "status",
        existing_type=sa.String(length=24),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.drop_column("invoices", "updated_at")
    op.drop_column("invoices", "updated_by_user_id")
    op.drop_column("invoices", "version")
    op.drop_column("invoices", "identity_origin")
    op.drop_column("invoices", "legacy_evidence_missing")
    op.drop_column("invoices", "calculation_digest")
    op.drop_column("invoices", "open_amount")
    op.drop_column("invoices", "taxable_basis")
    op.drop_column("invoices", "discount_amount")
    op.drop_column("invoices", "terms")
    op.drop_column("invoices", "due_date")
    op.drop_column("invoices", "issue_date")
    op.drop_column("invoices", "accounting_status")
    op.drop_column("invoices", "estimate_revision_id")
    op.drop_column("invoices", "estimate_id")
    op.create_check_constraint(
        "ck_invoices_status",
        "invoices",
        "status IN ('draft', 'issued', 'partially_paid', 'paid', 'void')",
    )
    op.create_check_constraint(
        "ck_invoices_amounts",
        "invoices",
        "subtotal_amount >= 0 AND tax_amount >= 0 AND total_amount >= 0 AND total_amount = subtotal_amount + tax_amount",
    )
    op.drop_constraint(
        "ck_invoice_lines_calculations", "invoice_line_items", type_="check"
    )
    op.drop_constraint("ck_invoice_lines_amounts", "invoice_line_items", type_="check")
    op.drop_constraint(
        "fk_invoice_lines_company", "invoice_line_items", type_="foreignkey"
    )
    op.drop_constraint(
        "uq_invoice_lines_position", "invoice_line_items", type_="unique"
    )
    op.alter_column(
        "invoice_line_items",
        "total_amount",
        existing_type=sa.Numeric(precision=18, scale=2),
        type_=sa.NUMERIC(precision=14, scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "invoice_line_items",
        "unit_price",
        existing_type=sa.Numeric(precision=18, scale=4),
        type_=sa.NUMERIC(precision=14, scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "invoice_line_items",
        "quantity",
        existing_type=sa.Numeric(precision=18, scale=6),
        type_=sa.NUMERIC(precision=12, scale=3),
        existing_nullable=False,
    )
    op.drop_column("invoice_line_items", "created_at")
    op.drop_column("invoice_line_items", "evidence")
    op.drop_column("invoice_line_items", "currency")
    op.drop_column("invoice_line_items", "tax_amount")
    op.drop_column("invoice_line_items", "tax_rate_basis_points")
    op.drop_column("invoice_line_items", "tax_policy_version")
    op.drop_column("invoice_line_items", "tax_policy_id")
    op.drop_column("invoice_line_items", "tax_classification_id")
    op.drop_column("invoice_line_items", "taxable")
    op.drop_column("invoice_line_items", "discounted_basis")
    op.drop_column("invoice_line_items", "discount_allocation")
    op.drop_column("invoice_line_items", "title")
    op.drop_column("invoice_line_items", "snapshot_digest")
    op.drop_column("invoice_line_items", "snapshot_id")
    op.drop_column("invoice_line_items", "estimate_line_id")
    op.drop_table("invoice_idempotency")
    op.drop_table("invoice_accounting_posting_receipts")
    op.drop_index("ix_ar_entries_invoice_time", table_name="ar_ledger_entries")
    op.drop_table("ar_ledger_entries")
    op.drop_table("invoice_payment_receipt_evidence")
    op.drop_table("invoice_number_sequences")
    # ### end Alembic commands ###
