"""create day one payments runtime

Revision ID: x9n1j3l5p720
Revises: w8m0i2k4n619
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "x9n1j3l5p720"
down_revision: str | Sequence[str] | None = "w8m0i2k4n619"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

U = postgresql.UUID(as_uuid=True)
M = sa.Numeric(18, 2)
TZ = sa.DateTime(timezone=True)


def upgrade() -> None:
    op.create_table("payment_intents", sa.Column("id", U, primary_key=True), sa.Column("company_id", U, sa.ForeignKey("companies.id", ondelete="RESTRICT"), nullable=False), sa.Column("branch_id", U, nullable=False), sa.Column("customer_id", U, sa.ForeignKey("customers.id", ondelete="RESTRICT"), nullable=False), sa.Column("invoice_id", U), sa.Column("amount", M, nullable=False), sa.Column("currency", sa.String(3), nullable=False), sa.Column("status", sa.String(32), nullable=False), sa.Column("provider", sa.String(64), nullable=False), sa.Column("merchant_account", sa.String(120), nullable=False), sa.Column("opaque_payment_method", sa.String(255), nullable=False), sa.Column("idempotency_key", sa.String(120), nullable=False), sa.Column("request_digest", sa.String(64), nullable=False), sa.Column("provider_idempotency_key", sa.String(120), nullable=False), sa.Column("provider_operation_id", sa.String(255)), sa.Column("version", sa.Integer, nullable=False), sa.Column("created_by_user_id", U, sa.ForeignKey("users.id", ondelete="RESTRICT"), nullable=False), sa.Column("created_at", TZ, nullable=False), sa.Column("updated_at", TZ, nullable=False), sa.ForeignKeyConstraint(["company_id", "branch_id"], ["branches.company_id", "branches.id"], ondelete="RESTRICT"), sa.CheckConstraint("amount > 0 AND currency ~ '^[A-Z]{3}$'"), sa.CheckConstraint("status IN ('created','requires_action','authorized','captured','declined','failed','cancelled','expired','reconciliation_required')"), sa.UniqueConstraint("company_id", "idempotency_key"), sa.UniqueConstraint("company_id", "provider_idempotency_key"), sa.UniqueConstraint("company_id", "id"))
    op.create_index("ix_payment_intents_scope", "payment_intents", ["company_id", "branch_id", "customer_id", "status"])
    op.create_table("payment_attempts", sa.Column("id", U, primary_key=True), sa.Column("company_id", U, nullable=False), sa.Column("intent_id", U, nullable=False), sa.Column("sequence", sa.Integer, nullable=False), sa.Column("operation", sa.String(24), nullable=False), sa.Column("outcome", sa.String(32), nullable=False), sa.Column("provider_operation_id", sa.String(255)), sa.Column("provider_code", sa.String(80)), sa.Column("evidence_digest", sa.String(64), nullable=False), sa.Column("occurred_at", TZ, nullable=False), sa.ForeignKeyConstraint(["company_id", "intent_id"], ["payment_intents.company_id", "payment_intents.id"], ondelete="RESTRICT"), sa.UniqueConstraint("company_id", "intent_id", "sequence"))
    op.create_table("payment_receipts", sa.Column("id", U, primary_key=True), sa.Column("company_id", U, nullable=False), sa.Column("branch_id", U, nullable=False), sa.Column("customer_id", U, nullable=False), sa.Column("intent_id", U, nullable=False), sa.Column("currency", sa.String(3), nullable=False), sa.Column("status", sa.String(32), nullable=False), sa.Column("captured_amount", M, nullable=False), sa.Column("available_amount", M, nullable=False), sa.Column("applied_amount", M, nullable=False), sa.Column("refunded_amount", M, nullable=False), sa.Column("disputed_amount", M, nullable=False), sa.Column("evidence_digest", sa.String(64), nullable=False), sa.Column("version", sa.Integer, nullable=False), sa.Column("captured_at", TZ, nullable=False), sa.ForeignKeyConstraint(["company_id", "intent_id"], ["payment_intents.company_id", "payment_intents.id"], ondelete="RESTRICT"), sa.CheckConstraint("captured_amount >= 0 AND available_amount >= 0 AND applied_amount >= 0 AND refunded_amount >= 0 AND disputed_amount >= 0"), sa.CheckConstraint("captured_amount = available_amount + applied_amount + refunded_amount + disputed_amount"), sa.UniqueConstraint("company_id", "intent_id"), sa.UniqueConstraint("company_id", "id"))
    op.create_table("payment_receipt_events", sa.Column("id", U, primary_key=True), sa.Column("company_id", U, nullable=False), sa.Column("receipt_id", U, nullable=False), sa.Column("event_type", sa.String(48), nullable=False), sa.Column("amount", M, nullable=False), sa.Column("invoice_id", U), sa.Column("external_identity", U), sa.Column("idempotency_key", sa.String(120), nullable=False), sa.Column("evidence_digest", sa.String(64), nullable=False), sa.Column("occurred_at", TZ, nullable=False), sa.ForeignKeyConstraint(["company_id", "receipt_id"], ["payment_receipts.company_id", "payment_receipts.id"], ondelete="RESTRICT"), sa.UniqueConstraint("company_id", "receipt_id", "idempotency_key"))
    op.create_table("payment_refunds", sa.Column("id", U, primary_key=True), sa.Column("company_id", U, nullable=False), sa.Column("branch_id", U, nullable=False), sa.Column("receipt_id", U, nullable=False), sa.Column("amount", M, nullable=False), sa.Column("currency", sa.String(3), nullable=False), sa.Column("status", sa.String(32), nullable=False), sa.Column("reason", sa.Text, nullable=False), sa.Column("idempotency_key", sa.String(120), nullable=False), sa.Column("request_digest", sa.String(64), nullable=False), sa.Column("provider_operation_id", sa.String(255)), sa.Column("evidence_digest", sa.String(64)), sa.Column("requested_by_user_id", U, nullable=False), sa.Column("approved_by_user_id", U), sa.Column("version", sa.Integer, nullable=False), sa.Column("created_at", TZ, nullable=False), sa.ForeignKeyConstraint(["company_id", "receipt_id"], ["payment_receipts.company_id", "payment_receipts.id"], ondelete="RESTRICT"), sa.CheckConstraint("amount > 0"), sa.UniqueConstraint("company_id", "idempotency_key"), sa.UniqueConstraint("company_id", "id"))
    op.create_table("payment_deposits", sa.Column("id", U, primary_key=True), sa.Column("company_id", U, sa.ForeignKey("companies.id", ondelete="RESTRICT"), nullable=False), sa.Column("branch_id", U, nullable=False), sa.Column("currency", sa.String(3), nullable=False), sa.Column("status", sa.String(32), nullable=False), sa.Column("gross_amount", M, nullable=False), sa.Column("destination_reference", sa.String(120), nullable=False), sa.Column("idempotency_key", sa.String(120), nullable=False), sa.Column("evidence_digest", sa.String(64), nullable=False), sa.Column("prepared_by_user_id", U, nullable=False), sa.Column("approved_by_user_id", U), sa.Column("created_at", TZ, nullable=False), sa.CheckConstraint("gross_amount >= 0"), sa.UniqueConstraint("company_id", "idempotency_key"), sa.UniqueConstraint("company_id", "id"))
    op.create_table("payment_deposit_receipts", sa.Column("id", U, primary_key=True), sa.Column("company_id", U, nullable=False), sa.Column("deposit_id", U, nullable=False), sa.Column("receipt_id", U, nullable=False), sa.Column("amount", M, nullable=False), sa.ForeignKeyConstraint(["company_id", "deposit_id"], ["payment_deposits.company_id", "payment_deposits.id"], ondelete="RESTRICT"), sa.ForeignKeyConstraint(["company_id", "receipt_id"], ["payment_receipts.company_id", "payment_receipts.id"], ondelete="RESTRICT"), sa.UniqueConstraint("company_id", "receipt_id"))
    op.create_table("payment_settlements", sa.Column("id", U, primary_key=True), sa.Column("company_id", U, sa.ForeignKey("companies.id", ondelete="RESTRICT"), nullable=False), sa.Column("provider", sa.String(64), nullable=False), sa.Column("merchant_account", sa.String(120), nullable=False), sa.Column("provider_payout_id", sa.String(255), nullable=False), sa.Column("currency", sa.String(3), nullable=False), sa.Column("settlement_date", sa.Date, nullable=False), sa.Column("gross_amount", M, nullable=False), sa.Column("refund_amount", M, nullable=False), sa.Column("dispute_amount", M, nullable=False), sa.Column("fee_amount", M, nullable=False), sa.Column("adjustment_amount", M, nullable=False), sa.Column("net_amount", M, nullable=False), sa.Column("status", sa.String(32), nullable=False), sa.Column("evidence_digest", sa.String(64), nullable=False), sa.Column("received_at", TZ, nullable=False), sa.CheckConstraint("gross_amount - refund_amount - dispute_amount - fee_amount + adjustment_amount = net_amount"), sa.UniqueConstraint("company_id", "provider", "merchant_account", "provider_payout_id"), sa.UniqueConstraint("company_id", "id"))
    op.create_table("payment_reconciliation_exceptions", sa.Column("id", U, primary_key=True), sa.Column("company_id", U, sa.ForeignKey("companies.id", ondelete="RESTRICT"), nullable=False), sa.Column("branch_id", U), sa.Column("entity_type", sa.String(48), nullable=False), sa.Column("entity_id", U, nullable=False), sa.Column("reason_code", sa.String(80), nullable=False), sa.Column("status", sa.String(16), nullable=False), sa.Column("idempotency_key", sa.String(120), nullable=False), sa.Column("evidence_digest", sa.String(64), nullable=False), sa.Column("opened_by_user_id", U), sa.Column("resolved_by_user_id", U), sa.Column("opened_at", TZ, nullable=False), sa.Column("resolved_at", TZ), sa.UniqueConstraint("company_id", "idempotency_key"))
    op.create_table("payment_webhook_receipts", sa.Column("id", U, primary_key=True), sa.Column("company_id", U, sa.ForeignKey("companies.id", ondelete="RESTRICT"), nullable=False), sa.Column("provider", sa.String(64), nullable=False), sa.Column("merchant_account", sa.String(120), nullable=False), sa.Column("provider_event_id", sa.String(255), nullable=False), sa.Column("event_type", sa.String(80), nullable=False), sa.Column("evidence_digest", sa.String(64), nullable=False), sa.Column("secret_version", sa.String(32), nullable=False), sa.Column("allowed_evidence", postgresql.JSONB, nullable=False), sa.Column("received_at", TZ, nullable=False), sa.UniqueConstraint("company_id", "provider", "merchant_account", "provider_event_id"), sa.UniqueConstraint("company_id", "evidence_digest"))
    op.create_table("payment_accounting_posting_receipts", sa.Column("id", U, primary_key=True), sa.Column("company_id", U, sa.ForeignKey("companies.id", ondelete="RESTRICT"), nullable=False), sa.Column("source_event_id", U, nullable=False), sa.Column("journal_id", U, nullable=False), sa.Column("journal_version", sa.Integer, nullable=False), sa.Column("policy_version", sa.String(80), nullable=False), sa.Column("status", sa.String(32), nullable=False), sa.Column("effective_date", sa.Date, nullable=False), sa.Column("posted_at", TZ, nullable=False), sa.UniqueConstraint("company_id", "source_event_id"))


def downgrade() -> None:
    for table in ("payment_accounting_posting_receipts", "payment_webhook_receipts", "payment_reconciliation_exceptions", "payment_settlements", "payment_deposit_receipts", "payment_deposits", "payment_refunds", "payment_receipt_events", "payment_receipts", "payment_attempts"):
        op.drop_table(table)
    op.drop_index("ix_payment_intents_scope", table_name="payment_intents")
    op.drop_table("payment_intents")
