"""create day one accounts payable runtime

Revision ID: y0p2k4m6q831
Revises: x9n1j3l5p720
Create Date: 2026-08-26 23:34:00.817410

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "y0p2k4m6q831"
down_revision: str | Sequence[str] | None = "x9n1j3l5p720"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ap_accounting_posting_receipts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('source_event_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('journal_id', sa.UUID(), nullable=True),
    sa.Column('journal_version', sa.Integer(), nullable=True),
    sa.Column('mapping_version', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'source_event_id', name='uq_ap_posting_receipt_event')
    )
    op.create_table('ap_subledger_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('entry_type', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('evidence_digest', sa.String(length=64), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=False),
    sa.Column('posting_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("entry_type IN ('bill','bill_reversal','credit','credit_application','credit_unapplication','disbursement','disbursement_reversal','correction')", name='ck_ap_subledger_entry_type'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'idempotency_key', name='uq_ap_subledger_idempotency')
    )
    op.create_index('ix_ap_subledger_as_of', 'ap_subledger_entries', ['company_id', 'vendor_id', 'effective_date'], unique=False)
    op.create_table('ap_vendors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('legal_name', sa.String(length=240), nullable=False),
    sa.Column('display_name', sa.String(length=240), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('default_terms', sa.String(length=120), nullable=True),
    sa.Column('provenance', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('active','archived')", name='ck_ap_vendors_status'),
    sa.CheckConstraint('length(btrim(code)) > 0 AND length(btrim(legal_name)) > 0 AND length(btrim(display_name)) > 0', name='ck_ap_vendors_names'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_ap_vendors_company_code'),
    sa.UniqueConstraint('company_id', 'id', name='uq_ap_vendors_company_id')
    )
    op.create_table('ap_bills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('bill_number', sa.String(length=40), nullable=False),
    sa.Column('vendor_document_number', sa.String(length=160), nullable=False),
    sa.Column('normalized_document_number', sa.String(length=160), nullable=False),
    sa.Column('bill_date', sa.Date(), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('terms_snapshot', sa.String(length=120), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('accounting_status', sa.String(length=32), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('open_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('source_system', sa.String(length=40), nullable=False),
    sa.Column('source_identity', sa.String(length=160), nullable=False),
    sa.Column('source_digest', sa.String(length=64), nullable=False),
    sa.Column('evidence_reference', sa.String(length=255), nullable=False),
    sa.Column('current_revision', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('prepared_by_user_id', sa.UUID(), nullable=False),
    sa.Column('approved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('replacement_for_bill_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("accounting_status IN ('pending','posted','reversed','reconciliation_required')", name='ck_ap_bills_accounting_status'),
    sa.CheckConstraint("currency ~ '^[A-Z]{3}$' AND total_amount >= 0 AND open_amount >= 0 AND open_amount <= total_amount", name='ck_ap_bills_amounts'),
    sa.CheckConstraint("status IN ('draft','submitted','approved','posted','rejected','cancelled','partially_paid','paid','credited','reversed')", name='ck_ap_bills_status'),
    sa.CheckConstraint('due_date >= bill_date', name='ck_ap_bills_dates'),
    sa.ForeignKeyConstraint(['company_id', 'branch_id'], ['branches.company_id', 'branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'vendor_id'], ['ap_vendors.company_id', 'ap_vendors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'bill_number', name='uq_ap_bills_company_number'),
    sa.UniqueConstraint('company_id', 'id', name='uq_ap_bills_company_id'),
    sa.UniqueConstraint('company_id', 'source_system', 'source_identity', name='uq_ap_bills_source_identity'),
    sa.UniqueConstraint('company_id', 'vendor_id', 'normalized_document_number', name='uq_ap_bills_vendor_document')
    )
    op.create_index('ix_ap_bills_aging', 'ap_bills', ['company_id', 'vendor_id', 'status', 'due_date'], unique=False)
    op.create_table('ap_disbursements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('available_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('method_category', sa.String(length=40), nullable=False),
    sa.Column('external_reference', sa.String(length=160), nullable=False),
    sa.Column('source_system', sa.String(length=40), nullable=False),
    sa.Column('source_identity', sa.String(length=160), nullable=False),
    sa.Column('evidence_digest', sa.String(length=64), nullable=False),
    sa.Column('recorder_user_id', sa.UUID(), nullable=False),
    sa.Column('approver_user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount > 0 AND available_amount >= 0 AND available_amount <= amount', name='ck_ap_disbursements_amounts'),
    sa.CheckConstraint('recorder_user_id <> approver_user_id', name='ck_ap_disbursements_sod'),
    sa.ForeignKeyConstraint(['company_id', 'vendor_id'], ['ap_vendors.company_id', 'ap_vendors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'id', name='uq_ap_disbursements_company_id'),
    sa.UniqueConstraint('company_id', 'source_system', 'source_identity', name='uq_ap_disbursement_source')
    )
    op.create_table('ap_vendor_credits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('credit_number', sa.String(length=80), nullable=False),
    sa.Column('credit_date', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('available_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('mapping_id', sa.UUID(), nullable=False),
    sa.Column('source_system', sa.String(length=40), nullable=False),
    sa.Column('source_identity', sa.String(length=160), nullable=False),
    sa.Column('source_digest', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount > 0 AND available_amount >= 0 AND available_amount <= amount', name='ck_ap_vendor_credits_amounts'),
    sa.ForeignKeyConstraint(['company_id', 'vendor_id'], ['ap_vendors.company_id', 'ap_vendors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'credit_number', name='uq_ap_vendor_credit_number'),
    sa.UniqueConstraint('company_id', 'id', name='uq_ap_vendor_credits_company_id'),
    sa.UniqueConstraint('company_id', 'source_system', 'source_identity', name='uq_ap_vendor_credit_source')
    )
    op.create_table('ap_vendor_source_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('source_system', sa.String(length=40), nullable=False),
    sa.Column('source_company_id', sa.String(length=160), nullable=False),
    sa.Column('source_vendor_id', sa.String(length=160), nullable=False),
    sa.Column('source_digest', sa.String(length=64), nullable=False),
    sa.Column('mapped_by_user_id', sa.UUID(), nullable=False),
    sa.Column('mapped_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id', 'vendor_id'], ['ap_vendors.company_id', 'ap_vendors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'source_system', 'source_company_id', 'source_vendor_id', name='uq_ap_vendor_source_identity'),
    sa.UniqueConstraint('company_id', 'vendor_id', 'source_system', name='uq_ap_vendor_source_vendor')
    )
    op.create_table('ap_account_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('mapping_key', sa.String(length=120), nullable=False),
    sa.Column('classification', sa.String(length=32), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('policy_version', sa.String(length=80), nullable=False),
    sa.Column('approved_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("classification IN ('expense','prepaid','fixed_asset','inventory_asset','tax','freight','discount','cash','clearing','other')", name='ck_ap_account_mappings_classification'),
    sa.ForeignKeyConstraint(['company_id', 'account_id'], ['accounting_accounts.company_id', 'accounting_accounts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'id', name='uq_ap_account_mappings_company_id'),
    sa.UniqueConstraint('company_id', 'mapping_key', 'effective_from', name='uq_ap_account_mapping_version')
    )
    op.create_table('ap_bill_revisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('bill_id', sa.UUID(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('canonical_digest', sa.String(length=64), nullable=False),
    sa.Column('frozen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id', 'bill_id'], ['ap_bills.company_id', 'ap_bills.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'bill_id', 'revision', name='uq_ap_bill_revision'),
    sa.UniqueConstraint('company_id', 'id', name='uq_ap_bill_revisions_company_id')
    )
    op.create_table('ap_credit_applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('credit_id', sa.UUID(), nullable=False),
    sa.Column('bill_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_ap_credit_applications_amount'),
    sa.ForeignKeyConstraint(['company_id', 'bill_id'], ['ap_bills.company_id', 'ap_bills.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'credit_id'], ['ap_vendor_credits.company_id', 'ap_vendor_credits.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'idempotency_key', name='uq_ap_credit_application_idempotency')
    )
    op.create_table('ap_disbursement_applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('disbursement_id', sa.UUID(), nullable=False),
    sa.Column('bill_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_ap_disbursement_applications_amount'),
    sa.ForeignKeyConstraint(['company_id', 'bill_id'], ['ap_bills.company_id', 'ap_bills.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'disbursement_id'], ['ap_disbursements.company_id', 'ap_disbursements.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'idempotency_key', name='uq_ap_disbursement_application_idempotency')
    )
    op.create_table('ap_duplicate_overrides',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('bill_id', sa.UUID(), nullable=False),
    sa.Column('duplicate_bill_id', sa.UUID(), nullable=False),
    sa.Column('requester_user_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_user_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('evidence_reference', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('requester_user_id <> reviewer_user_id', name='ck_ap_duplicate_override_sod'),
    sa.ForeignKeyConstraint(['company_id', 'bill_id'], ['ap_bills.company_id', 'ap_bills.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'bill_id', name='uq_ap_duplicate_override_bill')
    )
    op.create_table('ap_bill_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('revision_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('mapping_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('purchasing_reference', sa.String(length=255), nullable=True),
    sa.Column('receipt_reference', sa.String(length=255), nullable=True),
    sa.CheckConstraint('position >= 1 AND quantity > 0 AND net_amount >= 0 AND tax_amount >= 0', name='ck_ap_bill_lines_amounts'),
    sa.ForeignKeyConstraint(['company_id', 'mapping_id'], ['ap_account_mappings.company_id', 'ap_account_mappings.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'revision_id'], ['ap_bill_revisions.company_id', 'ap_bill_revisions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'revision_id', 'position', name='uq_ap_bill_line_position')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ap_bill_lines')
    op.drop_table('ap_duplicate_overrides')
    op.drop_table('ap_disbursement_applications')
    op.drop_table('ap_credit_applications')
    op.drop_table('ap_bill_revisions')
    op.drop_table('ap_account_mappings')
    op.drop_table('ap_vendor_source_mappings')
    op.drop_table('ap_vendor_credits')
    op.drop_table('ap_disbursements')
    op.drop_index('ix_ap_bills_aging', table_name='ap_bills')
    op.drop_table('ap_bills')
    op.drop_table('ap_vendors')
    op.drop_index('ix_ap_subledger_as_of', table_name='ap_subledger_entries')
    op.drop_table('ap_subledger_entries')
    op.drop_table('ap_accounting_posting_receipts')
    # ### end Alembic commands ###
