import { useState, type FormEvent } from "react";

import { getOperatorApiError } from "../../api/errors";
import { useSchedulingMutations } from "../../hooks/useScheduling";
import { Alert, Button, Field, Input } from "../../ui";

export function CreateAppointmentPanel({ onClose }: { readonly onClose: () => void }) {
  const mutation = useSchedulingMutations().create;
  const [form, setForm] = useState({ branch: "", customer: "", location: "", start: "", end: "", duration: "60" });
  const submit = (event: FormEvent) => { event.preventDefault(); mutation.mutate({ branch_id: form.branch, customer_id: form.customer, service_location_id: form.location, arrival_window_start_at: new Date(form.start).toISOString(), arrival_window_end_at: new Date(form.end).toISOString(), expected_duration_minutes: Number(form.duration), capacity_units: "1.00", idempotency_key: crypto.randomUUID() }, { onSuccess: onClose }); };
  return <section className="rounded-xl border border-stroke bg-surface p-ui-4 sm:p-ui-6"><h3 className="font-semibold">Create Appointment</h3><p className="mt-1 text-sm text-content-muted">Scheduling validates Company, Customer, Service Location, capacity, and overlap authority.</p><form className="mt-4 grid gap-3 sm:grid-cols-2" onSubmit={submit}><Field label="Branch ID"><Input value={form.branch} onChange={(event) => setForm({ ...form, branch: event.target.value })} required /></Field><Field label="Customer ID"><Input value={form.customer} onChange={(event) => setForm({ ...form, customer: event.target.value })} required /></Field><Field label="Service Location ID"><Input value={form.location} onChange={(event) => setForm({ ...form, location: event.target.value })} required /></Field><Field label="Expected duration (minutes)"><Input type="number" min="1" value={form.duration} onChange={(event) => setForm({ ...form, duration: event.target.value })} required /></Field><Field label="Arrival window start"><Input type="datetime-local" value={form.start} onChange={(event) => setForm({ ...form, start: event.target.value })} required /></Field><Field label="Arrival window end"><Input type="datetime-local" value={form.end} onChange={(event) => setForm({ ...form, end: event.target.value })} required /></Field><div className="flex gap-2 sm:col-span-2"><Button type="submit" loading={mutation.isPending}>Create authoritative Appointment</Button><Button type="button" variant="ghost" onClick={onClose}>Close</Button></div></form>{mutation.error && (() => { const error = getOperatorApiError(mutation.error, "Appointment"); return <Alert className="mt-3" variant="danger" title={error.title}>{error.message}</Alert>; })()}</section>;
}
