import {
  Bot,
  Boxes,
  BriefcaseBusiness,
  CalendarDays,
  ClipboardList,
  FileChartColumn,
  FileText,
  Headphones,
  Landmark,
  Megaphone,
  MonitorCog,
  ShieldCheck,
  Wrench,
  MapPinned,
  LayoutDashboard,
  Settings,
  Users,
} from "lucide-react";

import type { NavigationGroup, NavigationItem } from "./types";

export const navigationCatalog = [
  {
    id: "command-center",
    label: "Command Center",
    path: "/",
    icon: MonitorCog,
    availability: "available",
  },
  {
    id: "mission-control",
    label: "Mission Control",
    path: "/mission-control",
    icon: LayoutDashboard,
    availability: "available",
  },
  {
    id: "customers",
    label: "Customers",
    path: "/customers",
    icon: Users,
    availability: "available",
  },
  {
    id: "technician",
    label: "My day",
    path: "/technician",
    icon: MapPinned,
    availability: "available",
    requiredPermission: "COMPANY_JOB_EXECUTE",
  },
  {
    id: "dispatch",
    label: "Dispatch",
    path: "/dispatch",
    icon: ClipboardList,
    availability: "available",
  },
  {
    id: "scheduling",
    label: "Scheduling",
    path: "/scheduling",
    icon: CalendarDays,
    availability: "available",
    requiredPermission: "COMPANY_SCHEDULING_READ",
  },
  {
    id: "estimates",
    label: "Estimates",
    path: "/estimates",
    icon: FileChartColumn,
    availability: "available",
    requiredPermission: "COMPANY_ESTIMATE_READ",
  },
  {
    id: "price-book",
    label: "Price Book",
    path: "/price-book",
    icon: FileChartColumn,
    availability: "available",
    requiredPermission: "COMPANY_PRICE_BOOK_READ",
  },
  {
    id: "jobs",
    label: "Jobs",
    path: "/jobs",
    icon: BriefcaseBusiness,
    availability: "available",
  },
  {
    id: "engineering",
    label: "Engineering Factory",
    path: "/engineering",
    icon: Wrench,
    availability: "available",
  },
  {
    id: "invoices",
    label: "Invoices",
    path: "/invoices",
    icon: FileText,
    availability: "available",
    requiredPermission: "COMPANY_INVOICE_READ",
  },
  {
    id: "inventory",
    label: "Inventory",
    path: "/inventory",
    icon: Boxes,
    availability: "available",
    requiredPermission: "COMPANY_INVENTORY_READ",
  },
  {
    id: "employees",
    label: "Employees",
    path: "/employees",
    icon: Users,
    availability: "coming-soon",
  },
  {
    id: "administration",
    label: "Administration",
    path: "/administration",
    icon: ShieldCheck,
    availability: "available",
    requiredPermission: "COMPANY_ROLE_READ",
  },
  {
    id: "settings",
    label: "Settings",
    path: "/settings",
    icon: Settings,
    availability: "coming-soon",
  },
  {
    id: "dispatch-ai",
    label: "Dispatch AI",
    path: "/ai/dispatch",
    icon: Bot,
    availability: "coming-soon",
  },
  {
    id: "customer-care-ai",
    label: "Customer Care AI",
    path: "/ai/customer-care",
    icon: Headphones,
    availability: "coming-soon",
  },
  {
    id: "accounting-ai",
    label: "Accounting AI",
    path: "/ai/accounting",
    icon: Landmark,
    availability: "coming-soon",
  },
  {
    id: "marketing-ai",
    label: "Marketing AI",
    path: "/ai/marketing",
    icon: Megaphone,
    availability: "coming-soon",
  },
] as const satisfies readonly NavigationItem[];

const item = (id: NavigationItem["id"]) =>
  navigationCatalog.find((candidate) => candidate.id === id)!;

export const navigationGroups = [
  {
    id: "command-center",
    label: "Command Center",
    items: [item("command-center")],
  },
  {
    id: "operations",
    label: "Operations",
    items: [
      item("customers"),
      item("technician"),
      item("scheduling"),
      item("jobs"),
      item("dispatch"),
      item("estimates"),
      item("price-book"),
      item("invoices"),
      item("inventory"),
    ],
  },
  {
    id: "ai-workforce",
    label: "AI Workforce",
    items: [
      item("engineering"),
      item("dispatch-ai"),
      item("customer-care-ai"),
      item("accounting-ai"),
      item("marketing-ai"),
    ],
  },
  {
    id: "management",
    label: "Management",
    items: [
      item("mission-control"),
      item("employees"),
      item("administration"),
      item("settings"),
    ],
  },
] as const satisfies readonly NavigationGroup[];

export const availableNavigation = navigationCatalog.filter(
  (candidate) => candidate.availability === "available",
);
