import {
  Bot,
  Boxes,
  BriefcaseBusiness,
  CalendarDays,
  Clock3,
  ClipboardList,
  FileChartColumn,
  FileText,
  CreditCard,
  ReceiptText,
  Banknote,
  Workflow,
  Scale,
  Headphones,
  Landmark,
  TrendingUp,
  Sparkles,
  Megaphone,
  MonitorCog,
  ShieldCheck,
  Wrench,
  MapPinned,
  LayoutDashboard,
  Settings,
  BookOpen,
  ScrollText,
  Users,
  BadgeCheck,
} from "lucide-react";

import type { NavigationGroup, NavigationItem } from "./types";

export const navigationCatalog = [
  {
    id: "lia",
    label: "Ask LIA",
    path: "/lia",
    icon: Bot,
    availability: "available",
  },
  {
    id: "command-center",
    label: "Command Center",
    path: "/",
    icon: MonitorCog,
    availability: "available",
  },
  {
    id: "mission-control",
    label: "Mission Control",
    path: "/mission-control",
    icon: LayoutDashboard,
    availability: "available",
  },
  {
    id: "customers",
    label: "Customers",
    path: "/customers",
    icon: Users,
    availability: "available",
  },
  { id: "service-agreements", label: "Service Agreements", path: "/service-agreements", icon: BadgeCheck, availability: "available", requiredPermission: "COMPANY_SERVICE_AGREEMENT_READ" },
  {
    id: "workday",
    label: "My time clock",
    path: "/workday",
    icon: Clock3,
    availability: "available",
    requiredPermission: "COMPANY_TIMEKEEPING_OWN_READ",
  },
  {
    id: "technician",
    label: "My day",
    path: "/technician",
    icon: MapPinned,
    availability: "available",
    requiredPermission: "COMPANY_JOB_EXECUTE",
  },
  {
    id: "dispatch",
    label: "Dispatch",
    path: "/dispatch",
    icon: ClipboardList,
    availability: "available",
  },
  {
    id: "scheduling",
    label: "Scheduling",
    path: "/scheduling",
    icon: CalendarDays,
    availability: "available",
    requiredPermission: "COMPANY_SCHEDULING_READ",
  },
  {
    id: "estimates",
    label: "Estimates",
    path: "/estimates",
    icon: FileChartColumn,
    availability: "available",
    requiredPermission: "COMPANY_ESTIMATE_READ",
  },
  {
    id: "price-book",
    label: "Price Book",
    path: "/price-book",
    icon: FileChartColumn,
    availability: "available",
    requiredPermission: "COMPANY_PRICE_BOOK_READ",
  },
  {
    id: "jobs",
    label: "Jobs",
    path: "/jobs",
    icon: BriefcaseBusiness,
    availability: "available",
  },
  {
    id: "engineering",
    label: "Engineering Factory",
    path: "/engineering",
    icon: Wrench,
    availability: "available",
  },
  {
    id: "invoices",
    label: "Invoices",
    path: "/invoices",
    icon: FileText,
    availability: "available",
    requiredPermission: "COMPANY_INVOICE_READ",
  },
  {
    id: "payments" as NavigationItem["id"],
    label: "Payments",
    path: "/payments",
    icon: CreditCard,
    availability: "available",
    requiredPermission: "COMPANY_PAYMENT_READ",
  },
  {
    id: "payroll",
    label: "Payroll",
    path: "/payroll",
    icon: Banknote,
    availability: "available",
    requiredPermission: "COMPANY_PAYROLL_REPORTING_READ",
  },
  {
    id: "accounts-payable",
    label: "Accounts Payable",
    path: "/accounts-payable",
    icon: ReceiptText,
    availability: "available",
    requiredPermission: "COMPANY_ACCOUNTS_PAYABLE_READ",
  },
  {
    id: "revenue-cycle",
    label: "Revenue cycle",
    path: "/revenue-cycle",
    icon: Workflow,
    availability: "available",
    requiredPermission: "COMPANY_JOB_READ",
  },
  {
    id: "financial-reports",
    label: "Financial Reports",
    path: "/financial-reports",
    icon: Scale,
    availability: "available",
    requiredPermission: "COMPANY_ACCOUNTING_REPORT_READ",
  },
  {
    id: "business-economics",
    label: "Business Economics",
    path: "/business-economics",
    icon: TrendingUp,
    availability: "available",
    requiredPermission: "COMPANY_ECONOMICS_MEASUREMENT_READ",
  },
  {
    id: "economics-administration",
    label: "Economics Administration",
    path: "/business-economics/administration",
    icon: Settings,
    availability: "available",
    requiredPermission: "COMPANY_ECONOMICS_POLICY_READ",
  },
  {
    id: "luminary",
    label: "Luminary",
    path: "/luminary",
    icon: Sparkles,
    availability: "available",
    requiredPermission: "COMPANY_LUMINARY_READ",
  },
  {
    id: "inventory",
    label: "Inventory",
    path: "/inventory",
    icon: Boxes,
    availability: "available",
    requiredPermission: "COMPANY_INVENTORY_READ",
  },
  {
    id: "assets",
    label: "Assets & Fleet",
    path: "/assets",
    icon: Wrench,
    availability: "available",
    requiredPermission: "COMPANY_ASSET_READ",
  },
  {
    id: "purchasing",
    label: "Purchasing",
    path: "/purchasing",
    icon: ClipboardList,
    availability: "available",
    requiredPermission: "COMPANY_PURCHASING_READ",
  },
  {
    id: "employees",
    label: "Employees",
    path: "/employees",
    icon: Users,
    availability: "available",
    requiredPermission: "COMPANY_WORKFORCE_READ",
  },
  {
    id: "owner-operations",
    label: "Owner Operations",
    path: "/owner-operations",
    icon: ShieldCheck,
    availability: "available",
    requiredPermission: "COMPANY_ADMINISTER",
  },
  {
    id: "audit",
    label: "Audit history",
    path: "/audit",
    icon: ScrollText,
    availability: "available",
    requiredPermission: "COMPANY_AUDIT_READ",
  },
  {
    id: "reports",
    label: "Report Center",
    path: "/reports",
    icon: FileChartColumn,
    availability: "available",
  },
  {
    id: "operator-guide",
    label: "Operator guide",
    path: "/operator-guide",
    icon: BookOpen,
    availability: "available",
  },
  {
    id: "administration",
    label: "Administration",
    path: "/administration",
    icon: ShieldCheck,
    availability: "available",
    requiredPermission: "COMPANY_ROLE_READ",
  },
  {
    id: "settings",
    label: "Settings",
    path: "/settings",
    icon: Settings,
    availability: "coming-soon",
  },
  {
    id: "dispatch-ai",
    label: "Dispatch AI",
    path: "/ai/dispatch",
    icon: Bot,
    availability: "coming-soon",
  },
  {
    id: "customer-care-ai",
    label: "Customer Care AI",
    path: "/ai/customer-care",
    icon: Headphones,
    availability: "coming-soon",
  },
  {
    id: "accounting-ai",
    label: "Accounting AI",
    path: "/ai/accounting",
    icon: Landmark,
    availability: "coming-soon",
  },
  {
    id: "marketing-ai",
    label: "Marketing AI",
    path: "/ai/marketing",
    icon: Megaphone,
    availability: "coming-soon",
  },
] as const satisfies readonly NavigationItem[];

const item = (id: NavigationItem["id"]) =>
  navigationCatalog.find((candidate) => candidate.id === id)!;

export const navigationGroups = [
  {
    id: "command-center",
    label: "Command Center",
    items: [item("command-center")],
  },
  {
    id: "operations",
    label: "Operations",
    items: [
      item("customers"),
      item("service-agreements"),
      item("technician"),
      item("workday"),
      item("scheduling"),
      item("jobs"),
      item("dispatch"),
      item("estimates"),
      item("price-book"),
      item("invoices"),
      item("payments" as NavigationItem["id"]),
      item("payroll"),
      item("revenue-cycle"),
      item("accounts-payable"),
      item("financial-reports"),
      item("inventory"),
      item("purchasing"),
    ],
  },
  {
    id: "ai-workforce",
    label: "AI Workforce",
    items: [
      item("lia"),
      item("engineering"),
      item("dispatch-ai"),
      item("customer-care-ai"),
      item("accounting-ai"),
      item("marketing-ai"),
    ],
  },
  {
    id: "management",
    label: "Management",
    items: [
      item("mission-control"),
      item("owner-operations"),
      item("employees"),
      item("reports"),
      item("audit"),
      item("operator-guide"),
      item("administration"),
      item("settings"),
    ],
  },
] as const satisfies readonly NavigationGroup[];

export const availableNavigation = navigationCatalog.filter(
  (candidate) => candidate.availability === "available",
);
